declare class VendaWEB extends MouraPageAngular {
    ItensVenda: SiSMoura.Core.Entity.VendaWebRetorno[];
    private _telaPagamento;
    readonly TelaPagamento: ConcluirPagamento;
    private _telaComanda;
    readonly TelaComanda: ComandaVenda;
    readonly grdProd: MouraGridViewJS;
    readonly btnCancelarVenda: MouraButton;
    readonly btnConcluirVenda: MouraButton;
    readonly txtVendedor: MouraTextBoxProcura;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtQuantidade: MouraTextBox;
    readonly txtValorUnitario: MouraTextBox;
    readonly txtSubTotal: MouraTextBox;
    readonly txtTotal: MouraTextBox;
    readonly mdConcluir: MouraModal;
    readonly IsPagamentoAberto: boolean;
    readonly btnCancelarItem: MouraButton;
    readonly mdMaisOpcoes: MouraModal;
    readonly btnOpcoes: MouraButton;
    readonly btnOpcGravarComanda: MouraButton;
    readonly hdnProdutoAtivo: HTMLInputElement;
    readonly mdPDV: MouraModal;
    readonly cboPDV: MouraComboBox;
    readonly cboCaixa: MouraComboBox;
    readonly btnOKPDV: MouraButton;
    readonly btnPgPrincipalPDV: MouraButton;
    readonly dvPrincipalVenda: HTMLDivElement;
    ProdutoAtivo: SiSMoura.Core.Entity.VendaWebRetorno;
    readonly hdnInformacoesVenda: HTMLInputElement;
    InfVenda: SiSMoura.Core.Entity.InformacoesVendaRetorno;
    readonly hdnConfigVenda: HTMLInputElement;
    Configuracoes: SiSMoura.Core.Entity.Venda_Perfil;
    protected IsTelaIniciada(): boolean;
    protected Init(): void;
    NovaVenda(): void;
    protected VerificaCaixaAberto(): void;
    protected FocoNovaVenda(): void;
    protected LimparCamposInformarProduto(): void;
    protected OnClickBotaoOKInf(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoPaginaPrincipal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelectedIndexChangedPDV(s: any, e: any): void;
    protected CarregarCaixasAbertos(): void;
    protected OnPesquisouProduto(s: any, e: any): void;
    protected OnMensagemRetornoProduto(e: MsgBoxResultEventArgs): void;
    protected OnKeyPressProduto(s: any, e: MouraTextBoxProcuraKeyPressEventArgs): void;
    protected OnChangeValores(): void;
    protected OnKeyDownUnitario(e: any): void;
    protected AdicionarProdutoInformadoNaTela(): boolean;
    protected CalculaSubTotal(): void;
    protected CalculaTotalVenda(): void;
    protected OnClickBotaoConcluir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ConcluirVenda(): void;
    protected ValidarItemAdicionar(codigoProduto: number, nomeProduto: string, quantidade: number, unitario: number): boolean;
    protected AdicionarProdutoVenda(produtoEntity: SiSMoura.Core.Entity.VendaWebRetorno, quantidade: number, unitario: number, codVendedor: number): boolean;
    protected ProximoItem(): number;
    protected OnClickCancelarVenda(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CancelarVenda(): void;
    protected OnSelecionouOpcaoCancelarVenda(e: MsgBoxResultEventArgs): void;
    protected CriarAtalhosVenda(): void;
    protected KeyF11(e: KeyboardEvent): void;
    protected KeyF8(e: KeyboardEvent): void;
    protected KeyF3(e: KeyboardEvent): void;
    protected CancelaTeclasBrowser(e: KeyboardEvent): void;
    protected KeyF5(e: KeyboardEvent): void;
    protected CriarAtalhoVenda(atalho: string, funcaoExecutar: () => void, context: any): void;
    protected OnFechouModalPagamento(s: any, e: any): void;
    protected OnFechouModalOpcoes(s: any, e: any): void;
    protected OnClickBotaoCancelarItem(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CancelarItem(): void;
    protected OnRetornoInputCancelarItem(e: InputBoxResultEventArgs): void;
    protected OnClickMaisOpcoes(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoGravarComanda(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected GravarComanda(): void;
}
declare var vendaWEB: VendaWEB;
//# sourceMappingURL=VendaWEB.d.ts.map