declare class C_MDFe extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Fiscal_Mdfe> {
    private codNota;
    readonly hdnCodigo: HTMLInputElement;
    readonly cboSerie: MouraComboBox;
    Mdfe: any;
    readonly tab: MouraTabPanel;
    readonly cboTipoEmitente: MouraComboBox;
    Carregamento: any;
    ListaLocalCarregamento: any[];
    readonly grdUFCarregamento: MouraGridViewJSEditavel;
    Percurso: any;
    ListaUFPercurso: any[];
    readonly grdUFPercurso: MouraGridViewJSEditavel;
    Emitente: any;
    readonly txtFone_DDD1: MouraTextBoxTelefone;
    readonly txtCNPJ: MouraTextBoxCPF;
    Veiculo: any;
    Proprietario: any;
    readonly txtRNTRCProp: MouraTextBox;
    readonly cboTipoProp: MouraComboBox;
    readonly cboUFProp: MouraComboBox;
    readonly txtCPF: MouraTextBoxCPF;
    readonly txtNomeProp: MouraTextBox;
    readonly lstTipo: MouraRadioButtonList;
    readonly txtIEProp: MouraTextBox;
    Condutor: any;
    ListaCondutores: any[];
    readonly grdCondutor: MouraGridViewJSEditavel;
    Reboque: any;
    ListaReboque: any[];
    readonly grdReboque: MouraGridViewJSEditavel;
    readonly cboTipoPropReb: MouraComboBox;
    readonly cboTipoCReb: MouraComboBox;
    readonly txtRNTRCReb: MouraTextBox;
    readonly cboUFPropReb: MouraComboBox;
    readonly txtNomePropReb: MouraTextBox;
    readonly lstlTipoReb: MouraRadioButtonList;
    readonly txtCpfReb: MouraTextBoxCPF;
    readonly txtIEReb: MouraTextBox;
    CIOT: any;
    ListaCIOT: any[];
    readonly txtCpfCnpjCIOT: MouraTextBoxCPF;
    readonly grdCIOT: MouraGridViewJSEditavel;
    Contratante: any;
    ListaContratantes: any[];
    readonly txtCpfCnpjContratante: MouraTextBoxCPF;
    readonly grdContratantes: MouraGridViewJSEditavel;
    Pedagio: any;
    ListaPedagio: any[];
    readonly txtCpfCnpjResp: MouraTextBoxCPF;
    readonly grdPedagio: MouraGridViewJSEditavel;
    Seguro: any;
    ListaSeguro: any[];
    readonly mdSeguro: MouraModal;
    readonly grdSeguro: MouraGridViewJSEditavel;
    readonly cboResponsavelSeguro: MouraComboBox;
    Documento: any;
    readonly mtpDocumentos: MouraTabPanel;
    readonly cboMunDoc: MouraComboBox;
    readonly cboUFDoc: MouraComboBox;
    MunicipioDesc: any;
    ListaMunDescarregamento: any[];
    readonly grdCidadeDesc: MouraGridViewJSEditavel;
    CTE: any;
    ListaCte: any[];
    readonly grdCte: MouraGridViewJSEditavel;
    Lacre_Transporte: any;
    ListaLacreUnidTranspCte: any[];
    Unidade_Transporte: any;
    ListaUnidadeTransporteCTe: any[];
    readonly cboTipoUnTransp: MouraComboBox;
    readonly grdLacresTranspCte: MouraGridViewJSEditavel;
    readonly grdUnTranspCTe: MouraGridViewJSEditavel;
    Nfe: any;
    ListaNFe: any[];
    Unidade_Nfe: any;
    Lacre_Nfe: any;
    ListaLacreUnidTranspNFe: any[];
    ListaUnidadeTransporteNFe: any[];
    readonly grdLacresTranspNFe: MouraGridViewJSEditavel;
    readonly grdNFe: MouraGridViewJSEditavel;
    readonly grdUnTranspNFe: MouraGridViewJSEditavel;
    readonly cboTipoUnTranspNFe: MouraComboBox;
    Referenciado: any;
    ListaMdfe: any[];
    readonly btnAdicionaMDFe: MouraButton;
    readonly grdUnTranspMDFe: MouraGridViewJSEditavel;
    readonly grdLacresTranspMDFe: MouraGridViewJSEditavel;
    readonly cboTipoUnTranspMDFe: MouraComboBox;
    readonly grdMdfeRef: MouraGridViewJSEditavel;
    readonly tpMdfeRef: MouraTabPage;
    readonly agpMdfeRef: MouraAgrupamento;
    Lacre: any;
    ListaLacre: any[];
    readonly grdLacres: MouraGridViewJSEditavel;
    Autorizado: any;
    ListaAutDownload: any[];
    readonly txtCpfAut: MouraTextBoxCPF;
    readonly grdAutoD: MouraGridViewJSEditavel;
    Informacoes: any;
    readonly mdTransmitirNFe: MouraModal;
    TransmitirNFe: any;
    readonly mdEventosMDFe: MouraModal;
    Evento: any;
    readonly mdEncerrar: MouraModal;
    Encerrar: any;
    readonly cboUFEncerramento: MouraComboBox;
    readonly mdReboque: MouraModal;
    readonly mdPedagio: MouraModal;
    readonly mdCTe: MouraModal;
    readonly mdNFe: MouraModal;
    readonly mdMdfe: MouraModal;
    readonly cboMunLocalCarregamento: MouraComboBox;
    readonly cboMunDesc: MouraComboBox;
    readonly cboMunEncerramento: MouraComboBox;
    readonly grdDescarreg: MouraGridViewJSEditavel;
    readonly grdCarreg: MouraGridViewJSEditavel;
    ListaCarregamento: any[];
    Carregamento_Arquivario: any;
    Descarregamento_Arquivario: any;
    ListaDesCarregamento: any[];
    readonly grdComboio: MouraGridViewJSEditavel;
    readonly grdUnidades: MouraGridViewJSEditavel;
    ListaComboio: any[];
    Comboio: any;
    Aquaviario: any;
    Unidade: any;
    ListaCargaVazia: any[];
    Lacre_Mdfe: any;
    ListaLacreUnidTranspMDFe: any[];
    Unidade_Mdfe: any;
    ListaUnidadeTransporteMDFe: any[];
    readonly cboUFReb: MouraGridViewJSEditavel;
    readonly cboTipoEvento: MouraComboBox;
    readonly txtdataEncerrar: MouraTextBoxData;
    protected Init(): void;
    OnPageLoad(): void;
    protected MudouEmpresa(): void;
    protected MudouSerie(oldValue: any, newValue: any): void;
    protected MudouFormulario(): void;
    protected MudouModalidade(): void;
    protected ProprietarioNaoEmitente(): void;
    protected ReboqueProprietarioNaoEmitente(): void;
    protected MudouUFCarregamento(): void;
    protected MudouUFDescarregamento(): void;
    protected MudouUFDocumentos(): void;
    protected MudouUFEncerramento(): void;
    protected carregouUF(d: any): void;
    protected carregouUFDesc(d: any): void;
    protected carregouUFDoc(d: any): void;
    protected carregouUFEncerramento(d: any): void;
    OnClickBotaoMenos(): void;
    OnClickBotaoMais(): void;
    protected OnClickBotaoAdicionaReboque(): void;
    protected OnClickBotaoOkReboque(): void;
    protected OnClickBotaoIncluirUnidadeCTe(): void;
    protected OnClickBotaoIncluirUnidadeNFe(): void;
    protected OnClickBotaoIncluirUnidadeMDFe(): void;
    protected OnClickBotaoAdicionaPedagio(): void;
    OnClickBotaoGerenciarNFe(): void;
    protected OnClickBotaoAdicionaCte(): void;
    protected OnClickBotaoAdicionaNFe(): void;
    protected OnClickBotaoAdicionaMDFe(): void;
    protected OnClickBotaoIncluirLacreNFe(): void;
    protected OnClickBotaoIncluirLacreMDFe(): void;
    protected OnClickBotaoIncluirLacreCTe(): void;
    OnClickBotaoEventosMDFe(): void;
    protected OnClickBotaoEncerrarMDFe(): void;
    protected OnClickBotaoEncerrar(): boolean;
    protected OnClickBotaoConfirmarEvento(): boolean;
    protected OnClickBotaoTransmitirMDFe(): void;
    protected OnClickBotaoConsultarMDFe(): void;
    protected OnClickBotaoImprimirMDFe(): void;
    protected OnClickBotaoOkPedagio(): void;
    protected OnClickBotaoOkCte(): void;
    protected OnClickBotaoOkNFe(): void;
    protected OnClickBotaoOkMDFe(): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Fiscal_Mdfe): void;
    protected OnAntesGravar(): boolean;
    protected PreencherXMLNota(entidade: SiSMoura.Core.Entity.Fiscal_Mdfe): void;
    protected Limpar(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Fiscal_Mdfe): void;
    protected LimparItensGrades(): void;
    protected LimparListas(): void;
    protected LimparCiot(): void;
    protected LimparContratante(): void;
    protected LimparAutorizados(): void;
    protected LimparMdReboque(): void;
    protected LimparMdPedagio(): void;
    protected LimparMdCTe(): void;
    protected LimparMdNFe(): void;
    protected LimparMdMDFe(): void;
    protected validandoAutorizados(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoContratante(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUFCarregamento(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUFPercurso(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoCIOT(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoCondutor(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoReboque(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoMunicipioDescarregamento(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoCTe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoNFe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoMDFe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUnTranspCTe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoCarregamento(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoDescarregamento(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoComboio(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUnidadeCargaVazia(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUnTranspNFe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUnTranspMDFe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoPedagio(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoLacre(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoLacreCTe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoLacreNFe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoLacreMDFe(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoUnidade(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ValidandoSeguro(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected MudouTipoCIOT(newValue: any, oldValue: any): void;
    protected MudouTipoContratantes(newValue: any, oldValue: any): void;
    protected MudouTipoAutorizados(newValue: any, oldValue: any): void;
    protected MudouTipoPedagio(newValue: any, oldValue: any): void;
    protected MudouTipoProprietario(newValue: any, oldValue: any): void;
    protected MudouTipoReboque(newValue: any, oldValue: any): void;
    protected PreencherEmitente(Entity: SiSMoura.Core.Entity.Fiscal_Mdfe): void;
    protected PreencherNumeroNota(Entity: SiSMoura.Core.Entity.Fiscal_Mdfe): void;
    protected OnMtpDocumentosTabChanged(s: any, e: DevExpress.Web.Scripts.ASPxClientTabControlTabEventArgs): void;
    protected OnTabTabChanged(s: any, e: DevExpress.Web.Scripts.ASPxClientTabControlTabEventArgs): void;
    private VerificarTabVisible;
    protected OnAntesDeletar(): boolean;
    protected IsSerieValida(): boolean;
    protected OnClickBotaoAdicionaSeguro(): void;
    protected OnClickBotaoOkSeguro(): void;
    protected LimparMdSeguro(): void;
    protected OnNFeExcluida(): void;
    protected OnCTeExcluida(): void;
}
declare var c_MDFe: C_MDFe;
//# sourceMappingURL=C_MDFe.d.ts.map