declare class C_Prospeccao extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Franquia_Prospeccao> {
    readonly lblArquivoDownload: MouraLabel;
    readonly fpXML: MouraFileUploadJS;
    readonly accExperiencia: MouraAccordion;
    PathArquivoImportado: string;
    readonly GridDependente: MouraGridViewJSEditavel;
    readonly GridEscolaridade: MouraGridViewJSEditavel;
    readonly gridBens: MouraGridViewJSEditavel;
    readonly grdAnexos: MouraGridViewJSEditavel;
    readonly txtCep: MouraTextBoxCep;
    Franquia_Anexo: SiSMoura.Core.Entity.Franquia_Prospeccao_Anexo;
    Franquia_Prospeccao_Anexo: SiSMoura.Core.Entity.Franquia_Prospeccao_Anexo[];
    Franquia_Prospeccao_Bem: any;
    Franquia_Prospeccao_Bens: any[];
    Franquia_Curso: any;
    Franquia_Prospeccao_Curso: any[];
    Franquia_Dependente: any;
    Franquia_Prospeccao_Dependente: any[];
    readonly hdnCaminhoSessao: HTMLInputElement;
    protected Init(): void;
    protected OnSelecionouItemBem(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    OnPageLoad(): void;
    protected OnSelecionouItem(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected MudouExperienciaEmpresarial(): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected OnAntesGravar(): boolean;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected OnConsultarCEP(s: any, e: MouraTextBoxCepPesquisouEventArgs): void;
    protected OnValidandoDependentes(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnLimpouDependentes(): void;
    protected OnValidandoEscolaridade(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnLimpouEscolaridade(): void;
    protected OnValidandoBens(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnLimpouBens(): void;
    protected OnValidandoAnexos(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnLimpouAnexos(): void;
    protected OnFileUploadXMLCompleted(s: any, e: any): void;
    protected PreencherGradeDependente(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected PreencherGradeCurso(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected PreencherGradeBens(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected PreencherGradeAnexo(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected criarEntidadePersonalizados(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected OnDepoisSetEntidade(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): void;
    protected GetAcao(): number;
    protected Trocar_Tag(mensagem: string): string;
    protected EnviarEmail(infoEmail: SiSMoura.Core.Entity.FranquiaProspeccao_Email_Retorno, msgNova: string): boolean;
    protected EnviarSms(Entity: SiSMoura.Core.Entity.Franquia_Prospeccao): boolean;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
}
declare var c_Prospeccao: C_Prospeccao;
//# sourceMappingURL=C_Prospeccao.d.ts.map