declare class C_RegImp_Angular extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Fiscal_Regra_Imposto_Geral> {
    Contador: any;
    Contadores: any[];
    readonly grid: MouraGridViewJSEditavel;
    readonly cboExigibilidade: MouraComboBox;
    readonly txtDecreto: MouraTextBoxProcura;
    readonly txtGrupo_Fiscal: MouraTextBoxProcura;
    readonly txtTipoRegra: MouraTextBoxProcura;
    readonly cboCalculo_PIS: MouraComboBox;
    readonly cboST_PIS: MouraComboBox;
    readonly cboST_PIS_Entrada: MouraComboBox;
    readonly cboCalculo_COFINS: MouraComboBox;
    readonly cboST_COFINS: MouraComboBox;
    readonly cboST_COFINS_Entrada: MouraComboBox;
    readonly cboCalculo_IPI: MouraComboBox;
    readonly cboCalculo_Ipi_Saida: MouraComboBox;
    readonly cboST_IPI: MouraComboBox;
    readonly cboSt_IPI_Saida: MouraComboBox;
    readonly chkSemCalIPI: MouraCheckBox;
    readonly cboIncentivo: MouraComboBox;
    readonly cboCfopServico: MouraComboBox;
    readonly cboListaServico: MouraComboBox;
    readonly chkISS_Retido: MouraCheckBox;
    readonly txtDescricaoServico: MouraTextBox;
    readonly cboUF_Entrada: MouraComboBox;
    readonly txtTaxaTributaria: MouraTextBoxProcura;
    readonly cboModalidade_ST: MouraComboBox;
    readonly cboCFOP: MouraComboBox;
    readonly cboCFOPEn: MouraComboBox;
    readonly cboCfopEntradaDevolucao: MouraComboBox;
    readonly cboCSOSN: MouraComboBox;
    readonly cboCSTEn: MouraComboBox;
    readonly cboSituacao: MouraComboBox;
    readonly cboUF_Saida: MouraComboBox;
    readonly chkSubstituicao_IVA: MouraCheckBox;
    readonly txtCodigoICMS: MouraTextBox;
    readonly hdContador: HTMLInputElement;
    readonly tabCadastro: MouraTabPanel;
    OnPageLoad(): void;
    protected Init(): void;
    protected OnDepoisGravar(): boolean;
    protected OnAntesGravar(): boolean;
    protected OnAntesDeletar(): boolean;
    protected Gravar(): boolean;
    protected Gravar_Regra_ICMS(): boolean;
    protected OnST_COFINS_EntradaMudou(): void;
    protected OnST_COFINSMudou(): void;
    protected OnST_PISMudou(): void;
    protected OnST_PIS_EntradaMudou(): void;
    protected VerificaBase(cst: number): void;
    protected Limpar_Campos_ST(): void;
    protected OnUF_EntradaMudou(): void;
    protected OnTipoRegraProcurou(): void;
    protected OnCodigoICMSProcurou(): void;
    protected PreencherAbaICMS(codigo: number, contador: number): void;
    protected OnGrupoFiscalProcurou(): void;
    protected PreencherTela(): void;
    protected PreencherDadosGrid(Codigo: number, Grupo: number): void;
    protected ExcluirRegistro(): boolean;
    protected OnValidando(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Fiscal_Regra_Imposto_Geral): boolean;
    protected LimparCamposEntidade(limparCampoCodigo: Boolean, alterarVisibiliadeAbas: Boolean): void;
    protected LimparAbaICMS(): void;
}
declare var c_RegImp_Angular: C_RegImp_Angular;
//# sourceMappingURL=C_RegImp_Angular.d.ts.map