declare class C_ConEmp extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Empresa_Configuracoes> {
    readonly Grid: MouraGridViewJSEditavel;
    readonly gridSetor: MouraGridViewJSEditavel;
    readonly txtEmpresa: MouraTextBoxProcura;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtCluster: MouraTextBoxProcura;
    readonly txtTipoEmpresa: MouraTextBoxProcura;
    readonly lstDias: MouraCheckBoxList;
    readonly txtData: MouraTextBoxData;
    readonly txtHoraDifInicial: MouraTextBoxHora;
    readonly txtHoraDifFinal: MouraTextBoxHora;
    readonly txtHoraInicial: MouraTextBoxHora;
    readonly txtHoraFinal: MouraTextBoxHora;
    Horarios: SiSMoura.Core.Entity.Animais_Funcionamento_Empresa_HorarioRetorno[];
    Horario: SiSMoura.Core.Entity.Animais_Funcionamento_Empresa_HorarioRetorno;
    HorariosDif: SiSMoura.Core.Entity.Animais_Funcionamento_Empresa_HorarioRetorno[];
    HorarioDif: SiSMoura.Core.Entity.Animais_Funcionamento_Empresa_HorarioRetorno;
    Setores: SiSMoura.Core.Entity.Empresa_Setor[];
    Setor: SiSMoura.Core.Entity.Empresa_Setor;
    readonly GridServico: MouraGridViewJSEditavel;
    readonly GridSala: MouraGridViewJSEditavel;
    readonly GridDiferenciado: MouraGridViewJSEditavel;
    readonly GridHorarioServico: MouraGridViewJSEditavel;
    readonly lstDiasServico: MouraCheckBoxList;
    readonly txtHoraInicialServico: MouraTextBoxHora;
    readonly txtHoraFinalServico: MouraTextBoxHora;
    readonly txtServico: MouraTextBoxProcura;
    readonly txtSubGrupo: MouraTextBoxProcura;
    readonly txtSetorEmpresa: MouraTextBoxProcura;
    readonly txtSala: MouraTextBoxProcura;
    Servicos: SiSMoura.Core.Entity.Animais_Servico_Atendimento[];
    Servico: SiSMoura.Core.Entity.Animais_Servico_Atendimento;
    readonly mdHorarioServico: MouraModal;
    readonly mdSalas: MouraModal;
    HorariosServico: SiSMoura.Core.Entity.Animais_Servico_Atendimento_Horario[];
    HorarioServico: SiSMoura.Core.Entity.Animais_Servico_Atendimento_Horario;
    Salas: SiSMoura.Core.Entity.Animais_Sala_Setor[];
    Sala: SiSMoura.Core.Entity.Animais_Sala_Setor;
    readonly btnNovo: MouraButton;
    ItemAtualSetor: SiSMoura.Core.Entity.Empresa_Setor;
    ItemAtual: SiSMoura.Core.Entity.Animais_Servico_Atendimento;
    readonly btnOK: MouraButton;
    readonly btnOKSala: MouraButton;
    protected Init(): void;
    protected OnSalaAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnClickCancelar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnLimpouItemServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnLimpouItem(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnMudouEmpresa(): void;
    OnPageLoad(): void;
    protected VerificarExistencia(empresa: number): void;
    protected OnValidandoAlteracaoHorarioServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected PreencherHorarios(Entidade: SiSMoura.Core.Entity.Animais_Funcionamento_Empresa): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Empresa_Configuracoes): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Empresa_Configuracoes): void;
    protected PreencherServicos(Entidade: SiSMoura.Core.Entity.Animais_Servico_Atendimento): void;
    protected OnValidandoAlteracaoSetor(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnValidandoAlteracaoSala(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnValidandoAlteracaoHorarioDiferenciado(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnValidandoAlteracao(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnValidandoAlteracaoServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnAntesGravar(): boolean;
    protected OnClicouBotaoLinhaSetor(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClicouBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected AbrirModalSala(item: SiSMoura.Core.Entity.Empresa_Setor): void;
    protected AbrirModalServico(item: SiSMoura.Core.Entity.Animais_Servico_Atendimento): void;
    protected OnClicOk(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClicOkSala(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
}
declare const c_ConEmp: C_ConEmp;
//# sourceMappingURL=C_ConEmp.d.ts.map