declare class C_ConOng extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Contrato_Ong> {
    private PATH_DOCUMENTOS_CONTRATO_ONG;
    private validouDataContratoAdocao;
    private validouDataCancelamentoContratoAdocao;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly sgnContrato: MouraSignaturePad;
    readonly cboMotivoCancelamento: MouraComboBox;
    readonly txtUsuario: MouraTextBoxProcura;
    readonly txtDataCadastro: MouraTextBoxData;
    readonly txtDataAdocao: MouraTextBoxData;
    readonly btnEmitirContrato: MouraButton;
    readonly btnEnviarEmailContrato: MouraButton;
    readonly btnAnexos: MouraButton;
    readonly dlgAnexo: MouraModalAnexo;
    readonly cboPossuiOutrosAnimais: MouraComboBox;
    readonly txtQuantosAnimaisPossui: MouraTextBox;
    readonly btnCancelarContrato: MouraButton;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtPetONG: MouraTextBoxProcuraProprietarioAnimal;
    readonly dlgMotivoCancelamento: MouraModal;
    readonly txtMdlMotivoCanc: MouraTextBox;
    readonly btnMldMotivoCancConfirmar: MouraButton;
    readonly btnMldMotivoCancCancelar: MouraButton;
    readonly btnAssinatura: MouraButton;
    readonly hndUsuarioAutorizouCancelamento: HTMLInputElement;
    OnPageLoad(): void;
    protected Init(): void;
    protected OnSalvouAssinatura(s: any, e: any): void;
    private OnBtnAssinaturaClick;
    private ColetarAssinaturaCliente;
    catch(ex: any): void;
    protected OnCboMotivoCancelamento(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboPossuiAnimaisChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnAntesDeletar(): boolean;
    protected OnAntesBuscarExistente(): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Animais_Contrato_Ong): void;
    protected OnDepoisProcurouAnimal(s: any, e: MouraEventHandler): void;
    protected OnAntesGravar(): boolean;
    protected OnDepoisLimpar(): void;
    protected OnClickBotaonEnviarEmailContrato(s: any, e: MouraClickEventArgs): void;
    protected OnClickBotaoImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private OnBtnAnexoClick;
    private HabilitarCampos;
    protected OnTxtAnimalOngProcurou(s: MouraTextBoxProcuraRetornoProcura, e: MouraEventArgs): void;
    protected OnTxtProprietarioOngProcurou(s: MouraTextBoxProcuraRetornoProcura, e: MouraEventArgs): void;
    protected OnTxtProprietarioAdotanteProcurou(s: MouraTextBoxProcuraRetornoProcura, e: MouraEventArgs): void;
    private OnBtnCancelarContratoClick;
    private validouMotivoCancelamentoDevolucao;
    private onBtnMdlMotivoCancConfirmar;
    private onBtnMdlMotivoCancCancelar;
    private EnviarEmailContrato;
}
declare var c_ConOng: C_ConOng;
//# sourceMappingURL=C_ConOng.d.ts.map