declare class ModalProcura extends MouraControl {
    private campos;
    private COOKIE_CLIENTE;
    Campos: CampoProcura[];
    readonly BotaoPesquisar: HTMLButtonElement;
    readonly HiddenBackup: HTMLInputElement;
    readonly hdnEngine: HTMLInputElement;
    Engine: string;
    readonly hdnComboClientID: HTMLInputElement;
    ComboClientID: string;
    readonly hdnUsarCallBackPanel: HTMLInputElement;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    UsarCallBackPanel: boolean;
    readonly hdnUsarComboEmpresa: HTMLInputElement;
    UsarComboEmpresa: boolean;
    readonly hdnExibirCheckInativo: HTMLInputElement;
    ExibirCheckBoxInativo: boolean;
    readonly hdnSomenteAtivos: HTMLInputElement;
    SomenteAtivos: boolean;
    readonly hdnCriouColunas: HTMLInputElement;
    CriouColunas: boolean;
    readonly Modal: DevExpress.Web.Scripts.ASPxPopupControl;
    readonly HiddenParametros: HTMLInputElement;
    readonly hdnParametrosProcura: HTMLInputElement;
    readonly hdnCampoID: HTMLInputElement;
    readonly hdnEmpresaVisible: HTMLInputElement;
    readonly DivCampos: HTMLDivElement;
    readonly divGrade: HTMLDivElement;
    readonly grdProc: MouraGridViewJS;
    readonly Callback: DevExpress.Web.Scripts.ASPxClientCallbackPanel;
    readonly chkInativos: MouraCheckBox;
    readonly dvLabelCliente: JQuery<HTMLElement>;
    constructor(id: string);
    protected IniciarEventos(): void;
    Modal_Closing(s: DevExpress.Web.Scripts.ASPxClientControl, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    Abrir(engine: string): void;
    IniciarCamposProcura(): void;
    setFocoCampoProcura(): void;
    criarCampo(): void;
    protected criarCampoTipo(divTipo: any, tipo: any): void;
    GetValoresCampos(): any[];
    private isSomenteAtivosProcura;
    protected pesquisar(): void;
    protected OnPesquisouSucesso(retorno: any): void;
    protected OnPesquisouErro(erro: JQueryXHR): void;
    protected OnSelecionouLinhaJS(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnCellClickJS(s: any, e: any): void;
    protected SelecionarRegistro(valorSelecionado: string): void;
    protected OnKeyDownGridJS(s: any, e: any): void;
    protected OnRowsDblClickJS(s: any, e: any): void;
    protected OnComboChange(ev: JQueryEventObject): void;
    protected OnPesquisarClick(): void;
    protected OnTextboxBlur(): void;
    protected CorrigirHeightGradeJS(): void;
    protected OnGridCallBackError(s: DevExpress.Web.Scripts.ASPxClientGridView, e: DevExpress.Web.Scripts.ASPxClientCallbackErrorEventArgs): void;
    protected OnSelecionouCheckBoxInativo(): void;
    protected OnKeyDownModal(): void;
    protected OnESCTela(): void;
    protected IsProcuraCliente(): boolean;
    protected OnGridCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
}
//# sourceMappingURL=ModalProcura.d.ts.map