declare class MouraBaixaPagarJS extends MouraControl {
    BaixouConta: MouraGenericEventHandler<any, MouraEventArgs>;
    readonly dadosCheque: MouraDadosChequeJS;
    readonly centrosCusto: MouraCentroCustoPagarJS;
    readonly pnModal: MouraModal;
    readonly lblTotalAPagar: MouraLabel;
    readonly cboFormaPagamento: MouraComboBox;
    readonly txtNumeroDocumento: MouraTextBox;
    readonly txtContaContabil: MouraTextBoxProcura;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly cboGerar: DevExpress.Web.Scripts.ASPxClientComboBox;
    readonly txtDataCredito: MouraTextBoxData;
    readonly txtValor: MouraTextBox;
    readonly btnOK: MouraButton;
    readonly btnCancelar: MouraButton;
    readonly btnAdicionar: MouraButton;
    readonly grd: MouraGridViewJS;
    readonly chkLancamentoIndividual: MouraCheckBox;
    readonly optDadosConta: MouraRadioButtonList;
    readonly hdnFormaPagamento: HTMLInputElement;
    readonly hdnValorJuros: HTMLInputElement;
    readonly hdnValorDesconto: HTMLInputElement;
    readonly hdnCodigos: HTMLInputElement;
    readonly hdnCodigo: HTMLInputElement;
    readonly hdnCodUsuario: HTMLInputElement;
    readonly hdnTela: HTMLInputElement;
    readonly hdnObservacao: HTMLInputElement;
    readonly hdnDataBaixa: HTMLInputElement;
    readonly hdnNumeroDocBancario: HTMLInputElement;
    readonly hdnVencimentoResiduos: HTMLInputElement;
    readonly hdnValorCotacao: HTMLInputElement;
    readonly hdnIsBaixaLote: HTMLInputElement;
    FormasPagamento: SiSMoura.Core.Entity.ContasPagarPagamento[];
    Codigos: number[];
    protected IniciarEventos(): void;
    private OnBtnAdicionarClick;
    protected AdicionarPagamento(chequeCodigo: number, chequeAlterarSituacao: number, chequeContaCorrente: string, valorCheque: number): void;
    protected PreencherGrade(): void;
    protected OnClickCancelar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOk(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private OnGridExcluiuItem;
    protected OnPesquisouContaContabil(): void;
    protected MudouLancamentoIndividual(): void;
    protected BloquearDadosConta(): void;
    protected MudouDadosConta(): void;
    protected LimparCampos(): void;
    protected validarPagamento(): boolean;
    MostrarBaixa(Codigo: number, Tela: string, codUsuario: number, valorAPagar: number, contaContabilPadrao: number, contaCorrentePadrao: string, observacao: string, valorJuros: number, valorDesconto: number, dataBaixa: Date, numeroDocBancario: string, vencimentoResiduo: Date, valorCotacao: number, formaPgtoPadrao: number): void;
    Mostrar(Codigos: number[], Tela: string, codUsuario: number, valorAPagar: number, contaContabilPadrao: number, contaCorrentePadrao: string, observacao: string, valorJuros: number, valorDesconto: number, dataBaixa: Date, numeroDocBancario: string): void;
    protected BaixarContaIndividual(): void;
    protected BaixarContaLote(): void;
    protected TerminouBaixaLote(): void;
    protected Terminou(codConta: number): void;
    private OnInformouCheque;
    private OnInformouCentroCusto;
}
//# sourceMappingURL=MouraBaixaPagarJS.d.ts.map