declare class C_Client extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Cliente> {
    private itens;
    DadosAnimais: SiSMoura.Core.Entity.AnimaisCadastroRetorno[];
    readonly tab: MouraTabPanel;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly btnPreco: MouraButton;
    readonly txtCPF: MouraTextBoxCPF;
    readonly lstTipo: MouraRadioButtonList;
    readonly txtRG: MouraTextBox;
    readonly txtCep: MouraTextBoxCep;
    readonly txtCodPostal: MouraTextBox;
    readonly txtEndereco: MouraTextBox;
    readonly txtComplemento: MouraTextBox;
    readonly txtBairro: MouraTextBox;
    readonly txtNumero: MouraTextBox;
    readonly txtCidade: MouraTextBoxProcura;
    readonly txtFantasia: MouraTextBoxProcura;
    readonly txtApelido: MouraTextBoxProcura;
    readonly btnAssinatura: MouraButton;
    readonly btnIncluirAnimal: MouraButton;
    readonly sgnPessoa: MouraSignaturePad;
    readonly btnConsultarCliente: MouraButton;
    readonly btnCadastrarAnimal: MouraButton;
    readonly cboProfissional: DevExpress.Web.Scripts.ASPxClientComboBox;
    readonly cboClinica: DevExpress.Web.Scripts.ASPxClientComboBox;
    readonly cboContribuinteICMS: MouraComboBox;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly grdAni: MouraGridViewJS;
    readonly Mapa: MouraGoogleMaps;
    readonly btnProcurarEndereco: MouraButton;
    readonly btnTracarRota: MouraButton;
    readonly hdnCodigo: HTMLInputElement;
    readonly hdnEnderecoEmpresa: HTMLInputElement;
    readonly urlDescProdCliente: HTMLInputElement;
    readonly hdnCidadeEmpresa: HTMLInputElement;
    readonly hdnNumeroEmpresa: HTMLInputElement;
    readonly btnProdutosContinuos: MouraButton;
    readonly mdProdutosContinuos: MouraModal;
    readonly grdProdutosContinuos: MouraGridViewJSEditavel;
    readonly txtAnimal: MouraTextBoxProcura;
    readonly chkBloquearCrediario: MouraCheckBox;
    readonly txtProduto: MouraTextBoxProcura;
    readonly optTipo: MouraRadioButtonList;
    ProdutosContinuos: SiSMoura.Core.Entity.ClienteProdutoContinuoRetorno[];
    ProdutoContinuo: SiSMoura.Core.Entity.ClienteProdutoContinuoRetorno;
    readonly cboSexo: MouraComboBox;
    readonly lblTotalAtendimentos: MouraLabel;
    readonly agp1: HTMLInputElement;
    readonly EnvioSms: MouraSMS;
    readonly EnvioWhatsApp: MouraWhatsApp;
    readonly EnvioEmail: MouraEmail;
    readonly txtNome: MouraTextBox;
    readonly chkConsumidorFinal: MouraCheckBox;
    readonly lstEmpresasONG: MouraListBoxEmpresa;
    protected Init(): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    OnPageLoad(): void;
    protected OnPesquisouEntity(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouDadosAnimal(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnSetouProdutoContinuo(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnLimpouProdutoContinuo(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnValidandoProdutoContinuo(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAntesGravarCliente(s: any, e: MouraAntesGravarEventArgs): void;
    protected OnComboBoxClinicaChange(): void;
    protected MudouTipo(newValue: any, oldValue: any): void;
    protected MudouTipoProduto(newValue: any, oldValue: any): void;
    protected consultarCPF(): void;
    protected OnClicouOpcaoMsgBoxCPF(resultado: MsgBoxResultEventArgs): void;
    protected OnClicouOpcaoMsgBoxFornecedorCPF(resultado: MsgBoxResultEventArgs): void;
    protected OnClicouOKMsgBoxCPFInvalido(resultado: MsgBoxResultEventArgs): void;
    protected OnConsultarCEP(s: any, e: MouraTextBoxCepPesquisouEventArgs): void;
    protected OnClickProcurarEndereco(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickPreco(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private ProcurarEndereco;
    protected CarregarAnimais(codProprietario: number): void;
    protected CarregarProdutosContinuos(codProprietario: number): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Cliente): void;
    private CarregarEmpresasOng;
    protected AtualizarTotalAtendimentos(): void;
    protected OnDepoisSetEntidade(Entidade: SiSMoura.Core.Entity.Cliente): void;
    protected criarEntidadePersonalizados(Entidade: SiSMoura.Core.Entity.Cliente): void;
    protected OnAntesGravar(): boolean;
    private PreencherProdutos;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Cliente): void;
    protected OnClickTracarRota(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickProdutosContinuos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAssinatura(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickIncluirAnimal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSalvouAssinatura(s: any, e: any): void;
    private TracarRota;
    protected OnClickLinhaGrade(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnSelecionouLinhaGrade(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickCadastrarAnimal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnRetornouDlgModal(s: any, e: MouraTelaModalRetornouEventArgs): void;
    protected OnClickEnviarSMS(): void;
    protected OnClickEnviarWhatsApp(): void;
    protected OnClickEnviarEmail(): void;
    protected OnTxtCPFProcurou(s: any, e: MouraTextBoxCPFPesquisouEventArgs): void;
    protected OnCheckBoxIsOngChanged(): void;
}
declare var c_Client: C_Client;
//# sourceMappingURL=C_Client.d.ts.map