declare class C_Promoc extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Produto_Promocao> {
    readonly Grid: MouraGridViewJS;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtDesconto: MouraTextBox;
    readonly txtPromocao: MouraTextBox;
    readonly btnImportar: MouraButton;
    readonly btnProrrogar: MouraButton;
    readonly btnFechar: MouraButton;
    readonly btnGerar: MouraButton;
    readonly btnGravarProrrogar: MouraButton;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly lstSemana: MouraCheckBoxList;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtPeriodoProrrogar: MouraTextBoxPeriodo;
    readonly cboSituacao: MouraComboBox;
    readonly gridProrrogar: MouraGridViewJS;
    readonly gridDias: MouraGridViewJS;
    readonly gridEmpresas: MouraGridViewJS;
    readonly txtDataProrrogar: MouraTextBoxData;
    readonly cboEmpresaProrrogar: MouraComboBoxEmpresa;
    readonly lstSemanaProrrogar: MouraCheckBoxList;
    readonly hdnExistente: HTMLInputElement;
    readonly hdnBuscando: HTMLInputElement;
    readonly mdProrrogar: MouraModal;
    readonly mdDetalhes: MouraModal;
    protected Init(): void;
    protected OnGridCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnClickBotaoGerar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoAbrirAtualizacaoPreco(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnTextBoxDescontoChange(): void;
    protected OnTextBoxPromocaoChange(): void;
    protected OnCboSituacao(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected Calcular_Valor(): void;
    protected Calcular_PCento(): void;
    protected OnGridSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected Preencher_Grade_Detalhes(promoc: any): void;
    OnPageLoad(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Produto_Promocao): void;
    protected OnAntesGravar(): boolean;
    protected Preencher_Grade_Prorrogar(): void;
    protected OnClickBotaoFechar(): void;
    protected OnClickBotaoProrrogar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Calcular_PCentoExistente(Entity: SiSMoura.Core.Entity.Produto_Promocao): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Produto_Promocao): boolean;
    protected OnDepoisGravar(): boolean;
    protected VerificarPromocaoExistente(): void;
    protected PreencherPromocaoEmpresa(): void;
    protected PreencherPromocaoSemana(): void;
    protected RespostaExistente(result: MsgBoxResultEventArgs): void;
    protected GravarPromocaoProrrogar(): void;
    protected PreencherGrade(): void;
    protected Limpar_Modal_Prorrogar(): void;
}
declare var c_Promoc: C_Promoc;
//# sourceMappingURL=C_Promoc.d.ts.map