declare class C_AnimalAvaliacao extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Avaliacao> {
    readonly gridAlimentacao: MouraGridViewJSEditavel;
    readonly gridEndogard: MouraGridViewJSEditavel;
    readonly gridAvalicao: MouraGridViewJSEditavel;
    readonly gridVacinas: MouraGridViewJS;
    readonly gridGlicopan: MouraGridViewJSEditavel;
    readonly gridOutros: MouraGridViewJSEditavel;
    readonly gridEffipro: MouraGridViewJSEditavel;
    readonly btnImprimir: MouraButton;
    readonly btnCancelar: MouraButton;
    readonly btnOK: MouraButton;
    readonly btnImprimirBranco: MouraButton;
    readonly lstPeriodo: MouraRadioButtonList;
    readonly btnAvaliacao: MouraButton;
    readonly cboTipo: MouraComboBox;
    readonly tabAvaliacao: MouraTabPanel;
    readonly btnMarcar: MouraButton;
    readonly btnDesmarcar: MouraButton;
    Alimentacoes: SiSMoura.Core.Entity.Animais_Avaliacao_Alimento[];
    Avaliacao_Periodica: SiSMoura.Core.Entity.Animais_Avaliacao_Periodica[];
    Lista_Effipro: SiSMoura.Core.Entity.Animais_Avaliacao_Effipro[];
    Effipro: SiSMoura.Core.Entity.Animais_Avaliacao_Effipro;
    Lista_Glicopan: SiSMoura.Core.Entity.Animais_Avaliacao_Glicopan[];
    Vacinas: SiSMoura.Core.Entity.AnimaisVacinaRetorno[];
    Lista_Endogard: SiSMoura.Core.Entity.Animais_Avaliacao_Endogard[];
    Lista_Outros: SiSMoura.Core.Entity.Animais_Avaliacao_Outros[];
    Avaliacao: SiSMoura.Core.Entity.Animais_Avaliacao_Periodica;
    Alimentacao: SiSMoura.Core.Entity.Animais_Avaliacao_Alimento;
    Endogard: SiSMoura.Core.Entity.Animais_Avaliacao_Endogard;
    Glicopan: SiSMoura.Core.Entity.Animais_Avaliacao_Glicopan;
    readonly txtObservacao: MouraTextBox;
    readonly txtAnimal: MouraTextBoxProcura;
    readonly txtAtendenteAvaliacaoPeriodica: MouraTextBoxProcura;
    readonly txtAtendenteEndogard: MouraTextBoxProcura;
    readonly txtAtendenteDrontal: MouraTextBoxProcura;
    readonly txtDataEndogard: MouraTextBoxData;
    readonly txtData: MouraTextBoxData;
    readonly txtDataGlicopan: MouraTextBoxData;
    readonly lstNDose: MouraRadioButtonList;
    readonly mdAvaliacao: MouraModal;
    readonly chkOlhos: MouraCheckBox;
    readonly chkOrelhas: MouraCheckBox;
    readonly chkUnhas: MouraCheckBox;
    readonly chkCirurgia: MouraCheckBox;
    readonly chkFocinho: MouraCheckBox;
    readonly chkMucosas: MouraCheckBox;
    readonly chkHigiene: MouraCheckBox;
    readonly chkFezes: MouraCheckBox;
    readonly chkApatia: MouraCheckBox;
    readonly chkEctoparasitas: MouraCheckBox;
    readonly chkRef_Tosse: MouraCheckBox;
    readonly lblData: MouraLabel;
    protected Init(): void;
    protected OnClickEndogardNovo(): void;
    protected OnClickAdicionarAvaliacao(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickAdicionarAlimentacao(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickAdicionarOutros(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickAdicionarGlicopan(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickAdicionarEffipro(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickAdicionar(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    OnPageLoad(): void;
    protected OnClickMarcar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickDesmarcar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected MarcarDesmarcar(checked: boolean): void;
    protected OnClickCancelar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private _Contador;
    protected OnLimpouEndogard(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnValidandoEndogardGrade(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnGridSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnComboBoxTipoChange(): void;
    protected AlterarAbas(Tipo: string): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Avaliacao): void;
    protected preencherDataAtual(Entity: SiSMoura.Core.Entity.Animais_Avaliacao): void;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Animais_Avaliacao): void;
    protected PreencherVacinas(): void;
    protected VerificarAvaliacaoExistente(): void;
    protected PreencherAvaliacao(Animal: number): void;
    protected OnClickImprimirAvaliacao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirAvaliacaoBranco(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Imprimir(emBranco: boolean): void;
    protected OnAntesGravar(): boolean;
}
declare const c_AnimalAvaliacao: C_AnimalAvaliacao;
//# sourceMappingURL=C_AnimalAvaliacao.d.ts.map