declare class C_EntPar extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Entrega_Parcial> {
    Entrega: any;
    Entrega_Itens: any[];
    Pagamento: any;
    Pagamentos: any[];
    Data_Dia: any;
    Data_Hora: any;
    readonly txtHora: MouraTextBoxHora;
    readonly txtData: MouraTextBoxData;
    readonly optFiltro: MouraRadioButtonList;
    readonly txtVenda: MouraTextBoxProcura;
    readonly txtCliente: MouraTextBoxProcura;
    readonly txtOrcamento: MouraTextBoxProcura;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly btnCarregar: MouraButton;
    readonly btnOkPagto: MouraButton;
    readonly btnCancelarPagto: MouraButton;
    readonly btnPagamento: MouraButton;
    readonly mdPagamento: MouraModal;
    readonly btnEntregaTotal: MouraButton;
    readonly grdProdutos: MouraGridViewJSEditavel;
    readonly grdPagamento: MouraGridViewJSEditavel;
    readonly lblValorTotalEntrega: MouraLabel;
    readonly lblValorTotal: MouraLabel;
    readonly lblQtdePendente: MouraLabel;
    readonly lblQtdeEntrega: MouraLabel;
    readonly lblQtde: MouraLabel;
    readonly lblPagtoRestante: MouraLabel;
    readonly dvPrincipalVenda: HTMLDivElement;
    readonly cboFormaPagto: MouraComboBox;
    readonly btnImprimir: MouraButton;
    protected Init(): void;
    protected cliente: number;
    OnPageLoad(): void;
    protected CancelarPagamento(): void;
    protected PagamentoOk(): void;
    protected KeyF7(e: KeyboardEvent): void;
    protected FormaPagamento(codPamgamento: any): void;
    private totalPendente;
    protected CalcularTotalFaltante(): number;
    protected onProcurou(s: any, e: any): void;
    protected OnProcurouOrcamento(s: any, e: any): void;
    protected OnValidandoPagamento(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    private flag;
    private flagQtde;
    protected OnValidandoCampos(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Entrega_Parcial): void;
    protected OnDepoisLimpar(): void;
    OnClickBotaoEntregaTotal(): void;
    OnClickBotaoPagamento(): void;
    OnClickBotaoCarregar(): void;
    protected contasReceber: any[];
    CarregarItensVenda(codVenda: number, codEntrega: number): any;
    CarregarItensOrcamento(codOrcamento: number, codEntrega: number): any;
    VerificarVendaPDV(codVenda: number): any;
    VerificarProdutos(): any;
    protected OnAntesGravar(): boolean;
    protected OnAntesDeletar(): boolean;
    protected OnFiltroChange(): void;
    protected PreencherCampos(): void;
    converterPagamento(): void;
    converterEntregaParcialItem(): void;
    protected OnClickImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Imprimir(codEntrega: number, codModelo: number): void;
}
declare var c_EntPar: C_EntPar;
//# sourceMappingURL=C_EntPar.d.ts.map