declare class C_Entreg extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Entrega> {
    private vendas;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtVenda: MouraTextBoxProcura;
    readonly txtOrcamento: MouraTextBoxProcura;
    readonly txtData: MouraTextBoxData;
    readonly txtMotorista: MouraTextBoxProcura;
    readonly txtPlaca: MouraTextBox;
    readonly txtTransportadora: MouraTextBoxProcura;
    readonly txtObservacao: MouraTextBox;
    readonly cboSituacao: MouraComboBox;
    readonly cboTipo: DevExpress.Web.Scripts.ASPxClientComboBox;
    readonly hdnTipo: HTMLInputElement;
    readonly txtOrdem: MouraTextBox;
    readonly txtVolume: MouraTextBox;
    readonly grid: MouraGridViewJSEditavel;
    Vendas: SiSMoura.Core.Entity.VendaRetorno[];
    readonly btnCusto: MouraButton;
    readonly lblCodigo: MouraLabel;
    readonly lblData: MouraLabel;
    readonly lblPlaca: MouraLabel;
    readonly lblMotorista: MouraLabel;
    readonly mdCusto: MouraModal;
    readonly btnSalvarDistancia: MouraButton;
    readonly txtItem: MouraTextBox;
    readonly txtConta: MouraTextBoxProcura;
    readonly txtValor: MouraTextBox;
    readonly lblPorcentagemValor: MouraLabel;
    readonly txtObs: MouraTextBox;
    readonly grdCusto: MouraGridViewJSEditavel;
    Custos: SiSMoura.Core.Entity.Entrega_CustoRetorno[];
    readonly btnSalvarCustos: MouraButton;
    readonly lblValor_Vendas: MouraLabel;
    readonly lblCusto_Entrega: MouraLabel;
    readonly lblPorcentagem_Total: MouraLabel;
    readonly mdImportarVendas: MouraModal;
    readonly btnImportarVendas: MouraButton;
    readonly btnGerarVendas: MouraButton;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtVendedor: MouraTextBoxProcura;
    readonly txtCidade: MouraTextBoxProcura;
    readonly chkVendasOrcamento: MouraCheckBox;
    readonly cboZonaVenda: MouraComboBox;
    readonly grdVendas: MouraGridViewJS;
    readonly btnOk: MouraButton;
    readonly mdImportarVendasNf: MouraModal;
    readonly btnImportarVendasNf: MouraButton;
    readonly btnGerarVendasNf: MouraButton;
    readonly txtNf: MouraTextBox;
    readonly cboEmpresa: HTMLSelectElement;
    readonly cboSerie: MouraComboBox;
    readonly grdVendasNf: MouraGridViewJS;
    readonly btnOkNf: MouraButton;
    readonly btnImprimir: MouraButton;
    readonly btnImprimirProduto: MouraButton;
    readonly btnImpressaoCompleta: MouraButton;
    readonly chkValorImpressao: MouraCheckBox;
    protected Init(): void;
    protected OnAntesGravarEntrega(s: any, e: MouraAntesGravarEventArgs): void;
    protected OnPesquisouVenda(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouOrcamento(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnComboBoxTipoChange(): void;
    protected CarregarVenda(codVenda: number, tipo: number, ordem: number, volume: number): any;
    protected AtribuiPorcentagem(): void;
    protected OnClickIncluirCusto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnCustoAdicionado(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnGridLimpouItem(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnClickIncluirVenda(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAntesGravar(): boolean;
    private PreencherGrupos;
    private PreencherCustos;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Entrega): void;
    protected LimparModalImpVendas(): void;
    protected LimparModalImpVendasNf(): void;
    protected CarregarCusto(codEntrega: number): any;
    protected MostrarModalCusto(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CalculaLabels(): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Entrega): void;
    protected CarregarItem(): void;
    protected SalvarDistancia(): void;
    protected SalvarCusto(): void;
    protected MostrarModalImpVendas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected GerarVendas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ImportarVendasSelecionadas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected MostrarModalImpVendasNf(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected GerarVendasNf(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ImportarVendasNfSelecionadas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Imprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ImprimirProduto(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ImprimirCompleta(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnFechouMdImportarVendas(s: any, e: MouraEventHandler): void;
    protected OnFechouMdImportarVendasNf(s: any, e: MouraEventHandler): void;
}
declare const c_Entreg: C_Entreg;
//# sourceMappingURL=C_Entreg.d.ts.map