declare class C_PBaixa extends MouraPageAngular {
    Conta_Pagar: SiSMoura.Core.Entity.Contas_Pagar;
    readonly Grid: MouraGridViewJS;
    readonly btnBaixar: MouraButton;
    readonly btnLimpar: MouraButton;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly cboDocMercantil: MouraComboBox;
    readonly txtDataVencimento: MouraTextBoxData;
    readonly lblCalculadaEmDolar: MouraLabel;
    readonly lblValorCotacao: MouraLabel;
    readonly txtValorNominal: MouraTextBox;
    readonly lblEmpresa: MouraLabel;
    readonly lblValorOriginal: MouraLabel;
    readonly lblValorResidio: MouraLabel;
    readonly btnCancelarResiduo: MouraButton;
    readonly btnOkResiduo: MouraButton;
    readonly txtDesconto: MouraTextBox;
    readonly txtJuros: MouraTextBox;
    readonly txtValorPago: MouraTextBox;
    readonly txtValorTotal: MouraTextBox;
    readonly txtDataVencimentoResiduo: MouraTextBoxData;
    readonly mdResiduo: MouraModal;
    readonly BaixaPagar: MouraBaixaPagarJS;
    readonly hdnCodConta: HTMLInputElement;
    protected Init(): void;
    OnPageLoad(): void;
    protected MudouDesconto(): void;
    protected MudouJuros(): void;
    protected OnPesquisouCodigo(): void;
    protected PreencherTela(codConta: number): void;
    protected ObterContaCorrente(codContaCorrente: number): void;
    protected OnGridSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickLimpar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOkResiduo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarResiduo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected LimparCampos(): void;
    protected OnClickBaixar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected PreencherGrade(): void;
    protected OnPesquisouFornecedor(): void;
    protected ValidarBaixa(): void;
    protected VerificarContaPagar(): void;
    protected OnCarregouFuncaoSenhaDarBaixa(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnCarregouFuncaoBloquearBaixaPagar(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected VerificarResiduo(): void;
    protected BaixarConta(): void;
    protected OnCboEmpresaChange(): void;
    protected calculaTotalBaixaReceber(): void;
    private OnBaixouConta;
}
declare var c_PBaixa: C_PBaixa;
//# sourceMappingURL=C_PBaixa.d.ts.map