interface ParcelaPendente {
    Codigo: number;
    Fornecedor: number;
    Data_Emissao: Date;
    Parcela: number;
    Data_Vencimento: Date;
    Valor: number;
    Conta_Corrente: string;
    Conta_Contabil: number;
}
declare class C_PCadas extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Contas_Pagar> {
    protected isContinuarAlterarParcelas: boolean;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly txtContaContabil: MouraTextBoxProcura;
    readonly txtValor: MouraTextBox;
    readonly txtJurosPorc: MouraTextBox;
    thi: any;
    readonly grid: MouraGridViewJS;
    readonly hdnFornecedor: HTMLInputElement;
    readonly hdnPago: HTMLInputElement;
    readonly hdnData: HTMLInputElement;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly btnEmitirAutorizacao: MouraButton;
    readonly btnBaixar: MouraButton;
    readonly grdContas: MouraGridViewJS;
    readonly hdnURL: HTMLInputElement;
    readonly hdnConfiguracoesBloquearClienteEmpresa: HTMLInputElement;
    readonly btnReplicar: MouraButton;
    readonly mdReplicar: MouraModal;
    readonly mdAlterarParcelas: MouraModal;
    readonly grdAlterarParcelas: MouraGridViewJSEditavel;
    readonly btnGravarParcelas: MouraButton;
    readonly btnSairParcelas: MouraButton;
    Parcela: any;
    Parcelas: any[];
    readonly txtQtdeParcela: MouraTextBox;
    readonly cboDias: MouraComboBox;
    readonly txtDias: MouraTextBox;
    readonly txtN_DocBancarioReplicar: MouraTextBox;
    Replicas: SiSMoura.Core.Entity.ContasPagarReplicadoRetorno[];
    readonly grdReplicar: MouraGridViewJSEditavel;
    readonly btnOkReplicar: MouraButton;
    readonly btnCancelarReplica: MouraButton;
    readonly grdRateioCentroCusto: MouraGridViewJSEditavel;
    Custos: SiSMoura.Core.Entity.CentroDeCustoRetorno[];
    readonly txtCentroCusto: MouraTextBoxProcura;
    readonly txtValorCentroCusto: MouraTextBox;
    readonly rdTipoRateio: MouraRadioButtonList;
    readonly txtTipoLancamentoContabil_hdnEmpresaContabil: HTMLInputElement;
    readonly txtTipoLancamentoContabil: MouraTextBoxProcuraConfiguracaoContabil;
    readonly dlgAnexo: MouraModalAnexo;
    readonly btnAnexos: MouraButton;
    readonly cboEmpOrigem: MouraComboBox;
    private mudarEmpresa;
    readonly lblFornecedor: MouraLabel;
    flagAlterouParcelas: boolean;
    flagPrimeiraVez: boolean;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnAntesAbrirProcuraTipoLancamento(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    PreencherEmpresaContabil(codEmpresa: any): void;
    flag: boolean;
    protected OnPesquisandoContaContabil(e: MouraEventHandler): void;
    protected MudouContaCorrente(newValue: any, oldValue: any): void;
    protected VerificarCentroCustoGrade(newValue: any, oldValue: any): void;
    protected MudouTipoDias(): void;
    protected OnDepoisBuscarCentroCusto(): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected OnAntesClickBotaoNovo(s: any, e: any): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Contas_Pagar): void;
    protected OnAntesSetEntidade(eventArg: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Contas_Pagar>): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Contas_Pagar): void;
    protected SelecionarRegistro(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnAntesGravar(): boolean;
    protected OnSelecionouOpcaoMsgBoxData(result: MsgBoxResultEventArgs): void;
    protected OnAntesDeletar(): boolean;
    protected OnDepoisBuscarFornecedor(): void;
    protected PreencherGridContas(): void;
    protected OnDepoisAlterarJuros(): void;
    protected OnProcurouTxtTipoLancamentoContabil(): void;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisAlterarValor(): void;
    private CalculaValor;
    protected MostrarModalReplica(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnNovoReplica(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnClickIncluirReplica(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickReplicar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecionouOpcaoMsgBox(result: MsgBoxResultEventArgs): void;
    protected Replicar(): void;
    protected OnReplicouSucesso(d: any): void;
    protected OnErroReplicou(error: JQueryXHR): void;
    protected CancelarReplica(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CarregarCentroCusto(codCentroCusto: number): any;
    protected OnClickIncluirCusto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnCustoAdicionado(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private PreencherCustos;
    protected OnClickBtnEmitirAutorizacao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnBaixar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnAntesAbrirProcuraContaContabil(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnDepoisBuscarContaContabil(): void;
    protected VerificarContabilEmpresa(codContabil: any, contaCorrente: String): boolean;
    private ClicouAnexo;
    private LimparPastaTempAnexos;
    protected AlterarParcelasPendentes(d: any): void;
    protected ContinuarAlterandoParcelas(): void;
    protected SetColunasEditaveis(): void;
    protected OnEditouGridAlterarParcelas(s: MouraGridViewJS, e: MouraGridViewJSItemEventArgs): void;
    protected OnGravouAlterarParcelas(): void;
    protected OnSairParcelas(): void;
}
declare const c_PCadas: C_PCadas;
//# sourceMappingURL=C_PCadas.d.ts.map