declare class C_PLote extends MouraPageRelacaoAngular {
    private somaColuna;
    private counter;
    readonly AccordionFiltros: MouraAccordion;
    readonly mdBaixar: MouraBaixaPagarJS;
    Conta_Pagar: SiSMoura.Core.Entity.Contas_Pagar;
    readonly grid: MouraGridViewJS;
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly txtContaContabil: MouraTextBoxProcura;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly btnFecharImpCheque: MouraButton;
    readonly btnImprimirCheque: MouraButton;
    readonly mdCheque: MouraModal;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly btnBaixar: MouraButton;
    readonly lblValorCheque: MouraLabel;
    readonly lblValorExtenso: MouraLabel;
    readonly cboModeloImpressao: MouraComboBox;
    readonly cboContaCorrenteC: MouraContaCorrenteCombo;
    readonly txtNumeroCheque: MouraTextBox;
    readonly txtNominal: MouraTextBox;
    readonly txtDataEmissaoCheque: MouraTextBoxData;
    readonly lblData: MouraLabel;
    readonly btnEmitirCheque: MouraButton;
    NomeCidade: String;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnListEmpresaChange(): void;
    protected MudouContaCorrente(): void;
    protected OnAntesAbrirProcuraContaContabil(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnDepoisBuscarContaContabil(): void;
    protected LimparDadosBaixa(): void;
    protected OnClickFecharImpCheque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirCheque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ValidarCheque(): boolean;
    protected OnClickBaixar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnEmitirCheque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected BaixarConta(): void;
    protected OnCarregouFuncaoSenhaDarBaixa(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected PreencherGrade(): void;
    protected validarCamposFiltro(): boolean;
    protected OnPesquisouFornecedor(): void;
    protected LimparCamposImpressaoCheque(): void;
    protected MudouDataEmissaoCheque(): void;
    protected LimparCampos(): void;
    private OnBaixouConta;
    private CalculateCustomSummary;
    private CellPrepared;
    private OnSelecionouLinha;
}
declare const c_PLote: C_PLote;
//# sourceMappingURL=C_PLote.d.ts.map