declare class C_Ajuste extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Fiscal_Tipo_Ajuste> {
    Ajustes: SiSMoura.Core.Entity.Fiscal_Tipo_Ajuste_Contabil[];
    Ajuste: SiSMoura.Core.Entity.Fiscal_Tipo_Ajuste_Contabil;
    AjustesRetorno: SiSMoura.Core.Entity.Fiscal_Tipo_Ajuste_ContabilRetorno[];
    AjusteRetorno: SiSMoura.Core.Entity.Fiscal_Tipo_Ajuste_ContabilRetorno;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtDescricao: MouraTextBox;
    readonly cboImposto: MouraComboBox;
    readonly cboOperacao: MouraComboBox;
    readonly txtCodigoAjuste: MouraTextBox;
    readonly txtContaDebito: MouraTextBoxProcuraContabil;
    readonly txtContaCredito: MouraTextBoxProcuraContabil;
    readonly txtHistorico: MouraTextBoxProcura;
    readonly Grid: MouraGridViewJS;
    readonly txtContaCredito_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDebito_hdnEmpresaContabil: HTMLInputElement;
    readonly hdnEmpresa: HTMLInputElement;
    readonly cboTipoOperacao: MouraComboBox;
    readonly txtCodigoSubItem: MouraTextBox;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly GridContabil: MouraGridViewJSEditavel;
    readonly btnAdicionar: MouraButton;
    readonly btnLimpar: MouraButton;
    protected Init(): void;
    OnPageLoad(): void;
    protected MudouZero(Padrao: any): void;
    PreencherEmpresaContabil(): void;
    ValidaCamposContabeis(): void;
    protected ValidarCampos(): void;
    protected OnContaCreditoAntesAbrirProcura(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaCreditoPesquisando(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebitoAntesAbrirProcura(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebitoPesquisando(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnAdicionandoComando(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected ClickLimpar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    LimparCamposContabeis(): void;
    protected OnAntesGravar(): boolean;
    protected validarContabil(): boolean;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisLimpar(): void;
    protected OnDepoisDeletar(): boolean;
    protected OnAntesDeletar(): boolean;
    protected OnDepoisPesquisar(s: any, e: MouraDepoisPesquisarEventArgs): void;
    protected BuscarGrade(): void;
    protected OnGrdSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdContabilSelecionou(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    private ValidaCampoContabil;
}
declare var c_Ajuste: C_Ajuste;
//# sourceMappingURL=C_Ajuste.d.ts.map