declare class C_Consig_Angular extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Consig> {
    private codigo;
    private posicao;
    private verifica;
    private somarQtde;
    private gravou;
    readonly grid: MouraGridViewJSEditavel;
    readonly gridImportar: MouraGridViewJS;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtQuantidade: MouraTextBox;
    readonly lblConsig: MouraLabel;
    readonly rblLote: MouraRadioButtonList;
    readonly cboLote: MouraComboBox;
    readonly txtCodigoConsig: MouraTextBoxProcura;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtAjudante: MouraTextBoxProcura;
    readonly cboProdImport: MouraComboBox;
    readonly chkImportarDadosCliente: MouraCheckBox;
    readonly txtDataCadastro: MouraTextBoxData;
    readonly txtDataVencimento: MouraTextBoxData;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtVendedor: MouraTextBoxProcura;
    readonly cboDeposito: MouraComboBox;
    readonly cboTipoConsig: MouraComboBox;
    readonly lblValidade: MouraLabel;
    readonly txtCliente: MouraTextBoxProcura;
    readonly mdImportar: MouraModal;
    readonly btnImportarConsig: MouraButton;
    readonly btnGerar: MouraButton;
    readonly btnImprimirCupom: MouraButton;
    readonly btnImprimirMeiaFolha: MouraButton;
    readonly btnImportar: MouraButton;
    Itens: any[];
    ItensConsignacao: any;
    OnPageLoad(): void;
    Init(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Consig): void;
    protected LimparCampoProduto(): void;
    protected LimparModal(): void;
    protected OnDepoisClickNovo(): boolean;
    private PreencherGrade;
    private ValidarVendedorAjudante;
    private ValidarProduto;
    private ValidarCliente;
    private VerificaConsignacaoExistente;
    private ValidarAlteracaoConsignacao;
    private ValidaTelaAbertaUsuario;
    private ValidarExclusaoGrade;
    private ValidarDocumentoRepetido;
    private ValidarConsignacaoFinalizada;
    private ValidarPreencherEntidade;
    private VerificaValidadeLote;
    private ValidarCamposModal;
    private IsControlado;
    private VerificaDeposito;
    private OnAntesExcluir;
    private ExcluiuItem;
    private AdicionandoItem;
    private OnClicouBotaoNovoProduto;
    OnAntesNovo(): boolean;
    private OnBuscouProduto;
    private PreencherLote;
    private MudouIndexCboLote;
    private MudouIndexRblLote;
    private MudouIndexCboDeposito;
    OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Consig): void;
    PreencherEntidade(codigo: string): void;
    private OnBuscouCliente;
    private OnClicouImportConsig;
    private OnClicouGerar;
    private OnClicouImprimir;
    private OnClicouImprimirMeiaFolha;
    private OnClicouImportar;
    private GetValoresRowsSelecionadas;
    private PintarLinhas;
    private gridImportar_SelecionouLinha;
    protected OnAntesGravar(): boolean;
    protected OnDepoisGravar(): boolean;
}
declare const c_Consig_Angular: C_Consig_Angular;
//# sourceMappingURL=C_Consig_Angular.d.ts.map