declare class R_LanCon extends MouraPageRelacaoAngular {
    readonly AccordionFiltros: MouraAccordion;
    readonly txtContaCredito_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDedito_hdnEmpresaContabil: HTMLInputElement;
    readonly hdnLancamento: HTMLInputElement;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly txtContaCredito: MouraTextBoxProcuraContabil;
    readonly txtContaDebito: MouraTextBoxProcuraContabil;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtConta: MouraTextBoxProcuraContabil;
    readonly btnLancamento: MouraButton;
    readonly btnLimpar: MouraButton;
    readonly btnOk: MouraButton;
    readonly btnPesquisaAvancada: MouraButton;
    readonly btnFechar: MouraButton;
    readonly Grid: MouraGridViewJS;
    readonly Grid_DC: MouraGridViewJS;
    readonly txtLancamentoInicial: MouraTextBox;
    readonly txtLancamentoFinal: MouraTextBox;
    readonly txtDocumento: MouraTextBox;
    readonly txtValor: MouraTextBox;
    readonly txtHistorico: MouraTextBoxProcura;
    readonly txtPessoa: MouraTextBoxProcura;
    readonly lblTotalCredito: MouraLabel;
    readonly lblTotalDebito: MouraLabel;
    readonly lblTotalCreditoDC: MouraLabel;
    readonly lblTotalDebitoDC: MouraLabel;
    readonly mdPesquisaAvancada: MouraModal;
    readonly btnManutencaoEmLote: MouraButton;
    readonly mdlManutencaoEmLote: MouraModal;
    readonly GridManutencaoLote: MouraGridViewJS;
    readonly btnCancelar: MouraButton;
    readonly cboCampo: MouraComboBox;
    readonly txtExibicao: MouraTextBox;
    readonly txtCampoData: MouraTextBoxData;
    readonly txtCampoDocumento: MouraTextBox;
    readonly txtCampoDebito: MouraTextBoxProcuraContabil;
    readonly txtCampoCredito: MouraTextBoxProcuraContabil;
    readonly txtCampoValor: MouraTextBox;
    readonly txtCampoHistorico: MouraTextBoxProcura;
    readonly txtCampoDescricaoHistorico: MouraTextBox;
    readonly btnMarcarTodos: MouraButton;
    readonly btnDesmarcarTodos: MouraButton;
    readonly btnAlterar: MouraButton;
    readonly btnExcluir: MouraButton;
    RelacaoLancamentosManutencaoLote: SiSMoura.Core.Entity.Contabil_ManutencaoLote_PesquisaRetorno[];
    RelacaoLancamentos: SiSMoura.Core.Entity.ContabilPesquisaRetorno[];
    protected Init(): void;
    PreencherEmpresaContabil(): void;
    private LANCAMENTO;
    protected OnRetornouTelaModalCadastro(s: any, e: MouraTelaModalRetornouEventArgs): void;
    protected OnClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected PreencherGrade(): void;
    protected Preencher(): void;
    protected LimparModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected LimparCampos(): void;
    protected OnClickBotaoPesquisa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoOkPesquisa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoFecharPesquisa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoCadastro(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OncClickBotaoManutencaoEmLote(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoCancelar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnAlterouValor(): void;
    protected GetLancamentos(): void;
    protected OnMarcarTodos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnDesmarcarTodos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected GetRowsSelecionadas(campo: string): any[];
    protected OnAlterarLancamentosManutencaoLote(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnExcluirLancamentosManutencaoLote(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private onTxtDebitoProcurou;
    private onTxtCreditoProcurou;
    protected ValidarCamposModalManutencaoLote(): void;
    protected LimparCamposManutencaoLote(): void;
    protected AlterarRegistrosManutencaoLote(): void;
    protected ExcluirRegistrosManutencaoLote(): void;
    protected OnMsgBoxResponse(e: MsgBoxResultEventArgs): void;
    protected OnContaAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaDebitoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebitoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaCreditoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaCreditoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
}
declare var r_LanCon: R_LanCon;
//# sourceMappingURL=R_LanCon.d.ts.map