declare class C_Chekin extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Checkin> {
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtHora: MouraTextBoxHora;
    readonly txtData: MouraTextBoxData;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly cboSituacao: MouraComboBox;
    readonly cboLocal: MouraComboBox;
    readonly hdnSituacaoPadrao: HTMLInputElement;
    readonly hdnLocalPadrao: HTMLInputElement;
    readonly mdHistoricoCompleto: MouraModal;
    readonly txtHistorico: MouraTextBox;
    readonly cboIndicacao: MouraComboBox;
    readonly cboIndicacaoPara: MouraComboBox;
    readonly txtProfissionalIndicado: MouraTextBoxProcura;
    readonly txtNomeIndicacao: MouraTextBox;
    readonly txtTelefoneIndicacao: MouraTextBoxTelefone;
    readonly btnHistoricoCompleto: MouraButton;
    readonly btnFinalizar: MouraButton;
    readonly btnImprimir: MouraButton;
    readonly btnHistoricoImprimirMatricial: MouraButton;
    readonly btnHistoricoVisualizarWord: MouraButton;
    readonly txtConvenio: MouraTextBoxProcura;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnMudouData(): void;
    protected AlterarEntidadeData(): void;
    protected OnTxtDataChanged(): void;
    protected OnTxtHoraChanged(): void;
    protected OnCboLocalChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboIndicacaoChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboIndicacaoParaChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected AlteraVisibleIndicacao(opcao: string): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected AtualizarGrid(): void;
    protected SelecionarRegistro(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnAntesGravar(): boolean;
    protected OnAntesBuscarExistente(): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Animais_Checkin): void;
    protected CancelaValidacaoIndicacao(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Checkin): void;
    protected SetValoresPadroes(): void;
    protected OnClickBotaoHistoricoCompleto(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected HistoricoCompletoAnimal(): void;
    protected OnClickBotaoFinalizar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected FinalizarCheckin(codCheckIn: number, codCliente: number): void;
    protected OnSelecionouOpcaoFinalizar(e: MsgBoxResultEventArgs): void;
    protected OnClickImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickHistoricoImprimirMatricial(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnProcurouConvenio(s: any, e: any): void;
    protected VerificarElegibilidadePlano(codAnimal: number): void;
    protected IsConvenioProprio(codConvenio: number): boolean;
    protected OnClickHistoricoImprimirWord(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
}
declare var c_Chekin: C_Chekin;
//# sourceMappingURL=C_Chekin.d.ts.map