export * from './cliente.service';
import { ClienteService } from './cliente.service';
export * from './fiscal.service';
import { FiscalService } from './fiscal.service';
export * from './internoConfig.service';
import { InternoConfigService } from './internoConfig.service';
export * from './login.service';
import { LoginService } from './login.service';
export * from './mai.service';
import { MaiService } from './mai.service';
export * from './master.service';
import { MasterService } from './master.service';
export * from './masterLogado.service';
import { MasterLogadoService } from './masterLogado.service';
export * from './modalProcura.service';
import { ModalProcuraService } from './modalProcura.service';
export * from './mouraAccordion.service';
import { MouraAccordionService } from './mouraAccordion.service';
export * from './mouraButton.service';
import { MouraButtonService } from './mouraButton.service';
export * from './mouraCampo.service';
import { MouraCampoService } from './mouraCampo.service';
export * from './mouraCheckBox.service';
import { MouraCheckBoxService } from './mouraCheckBox.service';
export * from './mouraComboBox.service';
import { MouraComboBoxService } from './mouraComboBox.service';
export * from './mouraComboBoxEmpresa.service';
import { MouraComboBoxEmpresaService } from './mouraComboBoxEmpresa.service';
export * from './mouraControl.service';
import { MouraControlService } from './mouraControl.service';
export * from './mouraEmail.service';
import { MouraEmailService } from './mouraEmail.service';
export * from './mouraFileUpload.service';
import { MouraFileUploadService } from './mouraFileUpload.service';
export * from './mouraGridView.service';
import { MouraGridViewService } from './mouraGridView.service';
export * from './mouraLabel.service';
import { MouraLabelService } from './mouraLabel.service';
export * from './mouraMenu.service';
import { MouraMenuService } from './mouraMenu.service';
export * from './mouraMenuItem.service';
import { MouraMenuItemService } from './mouraMenuItem.service';
export * from './mouraModal.service';
import { MouraModalService } from './mouraModal.service';
export * from './mouraRadioButtonList.service';
import { MouraRadioButtonListService } from './mouraRadioButtonList.service';
export * from './mouraSMS.service';
import { MouraSMSService } from './mouraSMS.service';
export * from './mouraSelecaoDeImpressora.service';
import { MouraSelecaoDeImpressoraService } from './mouraSelecaoDeImpressora.service';
export * from './mouraTabPage.service';
import { MouraTabPageService } from './mouraTabPage.service';
export * from './mouraTabPanel.service';
import { MouraTabPanelService } from './mouraTabPanel.service';
export * from './mouraTextBox.service';
import { MouraTextBoxService } from './mouraTextBox.service';
export * from './mouraTextBoxCPF.service';
import { MouraTextBoxCPFService } from './mouraTextBoxCPF.service';
export * from './mouraTextBoxCep.service';
import { MouraTextBoxCepService } from './mouraTextBoxCep.service';
export * from './mouraTextBoxData.service';
import { MouraTextBoxDataService } from './mouraTextBoxData.service';
export * from './mouraTextBoxProcura.service';
import { MouraTextBoxProcuraService } from './mouraTextBoxProcura.service';
export * from './mouraTextBoxTelefone.service';
import { MouraTextBoxTelefoneService } from './mouraTextBoxTelefone.service';
export * from './pdvMobile.service';
import { PdvMobileService } from './pdvMobile.service';
export * from './pedidos.service';
import { PedidosService } from './pedidos.service';
export * from './petMouraAplicativoCliente.service';
import { PetMouraAplicativoClienteService } from './petMouraAplicativoCliente.service';
export * from './petMouraAplicativoInterno.service';
import { PetMouraAplicativoInternoService } from './petMouraAplicativoInterno.service';
export * from './principal.service';
import { PrincipalService } from './principal.service';
export * from './sismoura.service';
import { SismouraService } from './sismoura.service';
export * from './siteInterno.service';
import { SiteInternoService } from './siteInterno.service';
export * from './testeAngular.service';
import { TesteAngularService } from './testeAngular.service';
export * from './testeHtml.service';
import { TesteHtmlService } from './testeHtml.service';
export const APIS = [ClienteService, FiscalService, InternoConfigService, LoginService, MaiService, MasterService, MasterLogadoService, ModalProcuraService, MouraAccordionService, MouraButtonService, MouraCampoService, MouraCheckBoxService, MouraComboBoxService, MouraComboBoxEmpresaService, MouraControlService, MouraEmailService, MouraFileUploadService, MouraGridViewService, MouraLabelService, MouraMenuService, MouraMenuItemService, MouraModalService, MouraRadioButtonListService, MouraSMSService, MouraSelecaoDeImpressoraService, MouraTabPageService, MouraTabPanelService, MouraTextBoxService, MouraTextBoxCPFService, MouraTextBoxCepService, MouraTextBoxDataService, MouraTextBoxProcuraService, MouraTextBoxTelefoneService, PdvMobileService, PedidosService, PetMouraAplicativoClienteService, PetMouraAplicativoInternoService, PrincipalService, SismouraService, SiteInternoService, TesteAngularService, TesteHtmlService];
