/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';


import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MouraSMSService {

    protected basePath = 'http://localhost:38306';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param commandArgument 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraSMSGetMensagemSalvaSMS(commandArgument: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public mouraSMSGetMensagemSalvaSMS(commandArgument: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public mouraSMSGetMensagemSalvaSMS(commandArgument: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public mouraSMSGetMensagemSalvaSMS(commandArgument: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (commandArgument === null || commandArgument === undefined) {
            throw new Error('Required parameter commandArgument was null or undefined when calling mouraSMSGetMensagemSalvaSMS.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (commandArgument !== undefined && commandArgument !== null) {
            queryParameters = queryParameters.set('commandArgument', <any>commandArgument);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/controles/Dialogs/MouraSMS/GetMensagemSalvaSMS`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param commandArgument 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraSMSGetMensagemSalvaSMS_1(commandArgument: string, observe?: 'body', reportProgress?: boolean): Observable<string>;
    public mouraSMSGetMensagemSalvaSMS_1(commandArgument: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<string>>;
    public mouraSMSGetMensagemSalvaSMS_1(commandArgument: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<string>>;
    public mouraSMSGetMensagemSalvaSMS_1(commandArgument: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (commandArgument === null || commandArgument === undefined) {
            throw new Error('Required parameter commandArgument was null or undefined when calling mouraSMSGetMensagemSalvaSMS_1.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (commandArgument !== undefined && commandArgument !== null) {
            queryParameters = queryParameters.set('commandArgument', <any>commandArgument);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<string>(`${this.basePath}/api/MouraSMS/GetMensagemSalvaSMS`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraSMSIndex(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public mouraSMSIndex(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public mouraSMSIndex(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public mouraSMSIndex(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/controles/Dialogs/MouraSMS/Index`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraSMSIndex_2(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public mouraSMSIndex_2(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public mouraSMSIndex_2(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public mouraSMSIndex_2(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/MouraSMS/Index`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
