/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa } from '../model/siSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class MouraTextBoxCepService {

    protected basePath = 'http://localhost:38306';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraTextBoxCepIndex(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public mouraTextBoxCepIndex(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public mouraTextBoxCepIndex(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public mouraTextBoxCepIndex(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/controles/Campos/MouraTextBoxCep/Index`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraTextBoxCepIndex_1(observe?: 'body', reportProgress?: boolean): Observable<any>;
    public mouraTextBoxCepIndex_1(observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public mouraTextBoxCepIndex_1(observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public mouraTextBoxCepIndex_1(observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<any>(`${this.basePath}/api/MouraTextBoxCep/Index`,
            {
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param cep 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraTextBoxCepPesquisarEndereco(cep: string, observe?: 'body', reportProgress?: boolean): Observable<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>;
    public mouraTextBoxCepPesquisarEndereco(cep: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>>;
    public mouraTextBoxCepPesquisarEndereco(cep: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>>;
    public mouraTextBoxCepPesquisarEndereco(cep: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cep === null || cep === undefined) {
            throw new Error('Required parameter cep was null or undefined when calling mouraTextBoxCepPesquisarEndereco.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cep !== undefined && cep !== null) {
            queryParameters = queryParameters.set('cep', <any>cep);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>(`${this.basePath}/controles/Campos/MouraTextBoxCep/PesquisarEndereco`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param cep 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public mouraTextBoxCepPesquisarEndereco_2(cep: string, observe?: 'body', reportProgress?: boolean): Observable<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>;
    public mouraTextBoxCepPesquisarEndereco_2(cep: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>>;
    public mouraTextBoxCepPesquisarEndereco_2(cep: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>>;
    public mouraTextBoxCepPesquisarEndereco_2(cep: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (cep === null || cep === undefined) {
            throw new Error('Required parameter cep was null or undefined when calling mouraTextBoxCepPesquisarEndereco_2.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (cep !== undefined && cep !== null) {
            queryParameters = queryParameters.set('cep', <any>cep);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SiSMouraCoreEntityMouraTextBoxCEPRetornoPesquisa>(`${this.basePath}/api/MouraTextBoxCep/PesquisarEndereco`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
