/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Inject, Injectable, Optional }                      from '@angular/core';
import { HttpClient, HttpHeaders, HttpParams,
         HttpResponse, HttpEvent }                           from '@angular/common/http';
import { CustomHttpUrlEncodingCodec }                        from '../encoder';

import { Observable }                                        from 'rxjs/Observable';

import { SiSMouraCoreEntityConexaoMoura } from '../model/siSMouraCoreEntityConexaoMoura';

import { BASE_PATH, COLLECTION_FORMATS }                     from '../variables';
import { Configuration }                                     from '../configuration';


@Injectable()
export class SismouraService {

    protected basePath = 'http://localhost:38306';
    public defaultHeaders = new HttpHeaders();
    public configuration = new Configuration();

    constructor(protected httpClient: HttpClient, @Optional()@Inject(BASE_PATH) basePath: string, @Optional() configuration: Configuration) {
        if (basePath) {
            this.basePath = basePath;
        }
        if (configuration) {
            this.configuration = configuration;
            this.basePath = basePath || configuration.basePath || this.basePath;
        }
    }

    /**
     * @param consumes string[] mime-types
     * @return true: consumes contains 'multipart/form-data', false: otherwise
     */
    private canConsumeForm(consumes: string[]): boolean {
        const form = 'multipart/form-data';
        for (const consume of consumes) {
            if (form === consume) {
                return true;
            }
        }
        return false;
    }


    /**
     * 
     * 
     * @param token 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sismouraGetConexaoRetaguarda(token: string, observe?: 'body', reportProgress?: boolean): Observable<SiSMouraCoreEntityConexaoMoura>;
    public sismouraGetConexaoRetaguarda(token: string, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SiSMouraCoreEntityConexaoMoura>>;
    public sismouraGetConexaoRetaguarda(token: string, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SiSMouraCoreEntityConexaoMoura>>;
    public sismouraGetConexaoRetaguarda(token: string, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (token === null || token === undefined) {
            throw new Error('Required parameter token was null or undefined when calling sismouraGetConexaoRetaguarda.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('Token', <any>token);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SiSMouraCoreEntityConexaoMoura>(`${this.basePath}/api/Sismoura/GetConexaoRetaguarda`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param token 
     * @param pdv 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sismouraGetConexaoSismouraWeb(token: string, pdv: number, observe?: 'body', reportProgress?: boolean): Observable<SiSMouraCoreEntityConexaoMoura>;
    public sismouraGetConexaoSismouraWeb(token: string, pdv: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<SiSMouraCoreEntityConexaoMoura>>;
    public sismouraGetConexaoSismouraWeb(token: string, pdv: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<SiSMouraCoreEntityConexaoMoura>>;
    public sismouraGetConexaoSismouraWeb(token: string, pdv: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (token === null || token === undefined) {
            throw new Error('Required parameter token was null or undefined when calling sismouraGetConexaoSismouraWeb.');
        }

        if (pdv === null || pdv === undefined) {
            throw new Error('Required parameter pdv was null or undefined when calling sismouraGetConexaoSismouraWeb.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (token !== undefined && token !== null) {
            queryParameters = queryParameters.set('Token', <any>token);
        }
        if (pdv !== undefined && pdv !== null) {
            queryParameters = queryParameters.set('Pdv', <any>pdv);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<SiSMouraCoreEntityConexaoMoura>(`${this.basePath}/api/Sismoura/GetConexaoSismouraWeb`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param codProduto 
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sismouraGetUrlsFotosProduto(codProduto: number, observe?: 'body', reportProgress?: boolean): Observable<Array<string>>;
    public sismouraGetUrlsFotosProduto(codProduto: number, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<Array<string>>>;
    public sismouraGetUrlsFotosProduto(codProduto: number, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<Array<string>>>;
    public sismouraGetUrlsFotosProduto(codProduto: number, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (codProduto === null || codProduto === undefined) {
            throw new Error('Required parameter codProduto was null or undefined when calling sismouraGetUrlsFotosProduto.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codProduto !== undefined && codProduto !== null) {
            queryParameters = queryParameters.set('codProduto', <any>codProduto);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
            'application/json',
            'text/json',
            'application/xml',
            'text/xml'
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
        ];

        return this.httpClient.get<Array<string>>(`${this.basePath}/api/Sismoura/GetUrlsFotosProduto`,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

    /**
     * 
     * 
     * @param codProduto 
     * @param foto Foto nova do produto
     * @param observe set whether or not to return the data Observable as the body, response or events. defaults to returning the body.
     * @param reportProgress flag to report request and response progress.
     */
    public sismouraUploadFotoProduto(codProduto: number, foto: Blob, observe?: 'body', reportProgress?: boolean): Observable<any>;
    public sismouraUploadFotoProduto(codProduto: number, foto: Blob, observe?: 'response', reportProgress?: boolean): Observable<HttpResponse<any>>;
    public sismouraUploadFotoProduto(codProduto: number, foto: Blob, observe?: 'events', reportProgress?: boolean): Observable<HttpEvent<any>>;
    public sismouraUploadFotoProduto(codProduto: number, foto: Blob, observe: any = 'body', reportProgress: boolean = false ): Observable<any> {

        if (codProduto === null || codProduto === undefined) {
            throw new Error('Required parameter codProduto was null or undefined when calling sismouraUploadFotoProduto.');
        }

        if (foto === null || foto === undefined) {
            throw new Error('Required parameter foto was null or undefined when calling sismouraUploadFotoProduto.');
        }

        let queryParameters = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        if (codProduto !== undefined && codProduto !== null) {
            queryParameters = queryParameters.set('codProduto', <any>codProduto);
        }

        let headers = this.defaultHeaders;

        // to determine the Accept header
        let httpHeaderAccepts: string[] = [
        ];
        const httpHeaderAcceptSelected: string | undefined = this.configuration.selectHeaderAccept(httpHeaderAccepts);
        if (httpHeaderAcceptSelected != undefined) {
            headers = headers.set('Accept', httpHeaderAcceptSelected);
        }

        // to determine the Content-Type header
        const consumes: string[] = [
            'application/form-data'
        ];

        const canConsumeForm = this.canConsumeForm(consumes);

        let formParams: { append(param: string, value: any): void; };
        let useForm = false;
        let convertFormParamsToString = false;
        // use FormData to transmit files using content-type "multipart/form-data"
        // see https://stackoverflow.com/questions/4007969/application-x-www-form-urlencoded-or-multipart-form-data
        useForm = canConsumeForm;
        if (useForm) {
            formParams = new FormData();
        } else {
            formParams = new HttpParams({encoder: new CustomHttpUrlEncodingCodec()});
        }

        if (foto !== undefined) {
            formParams = formParams.append('Foto', <any>foto) || formParams;
        }

        return this.httpClient.post<any>(`${this.basePath}/api/Sismoura/UploadFotoProduto`,
            convertFormParamsToString ? formParams.toString() : formParams,
            {
                params: queryParameters,
                withCredentials: this.configuration.withCredentials,
                headers: headers,
                observe: observe,
                reportProgress: reportProgress
            }
        );
    }

}
