declare class C_Loca extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Locacao_Equipamento> {
    readonly txtCodigo: MouraTextBoxProcura;
    readonly tab: MouraTabPanel;
    readonly btnImprimirContrato: MouraButton;
    readonly cboSituacao: MouraComboBox;
    readonly lblUltimaLocacao: MouraLabel;
    readonly txtCliente: MouraTextBoxProcura;
    readonly txtPeriodoLocacao: MouraTextBoxPeriodo;
    readonly txtDataLocacao: MouraTextBoxData;
    readonly txtHoraLocacao: MouraTextBoxHora;
    readonly cboTipoCobranca: MouraComboBox;
    readonly txtPrevisaoDevolucao: MouraTextBoxData;
    readonly agp1: HTMLInputElement;
    readonly txtCNPJCPF: MouraTextBoxCPF;
    readonly txtRG: MouraTextBox;
    readonly txtCEPLocatario: MouraTextBoxCep;
    readonly txtCEPObra: MouraTextBoxCep;
    readonly txtProduto: MouraTextBoxProcura;
    readonly cboDeposito: MouraComboBox;
    readonly btnEstoque: MouraButton;
    readonly lblEstoqueAtual: MouraLabel;
    readonly txtPrecoLocacao: MouraTextBox;
    readonly txtQuantidade: MouraTextBox;
    readonly txtDescontoUnitario: MouraTextBox;
    readonly txtDescontoUnitarioPorc: MouraTextBox;
    readonly txtDescontoR: MouraTextBox;
    readonly txtDescontoRPorc: MouraTextBox;
    readonly txtDeslocamentoEntrega: MouraTextBox;
    readonly txtDeslocamentoRetirada: MouraTextBox;
    Produto: any;
    Produtos: any[];
    readonly grdProdutos: MouraGridViewJSEditavel;
    readonly lblTotalFinal: MouraLabel;
    Conta: any;
    Contas: any[];
    Indenizacao: any;
    Indenizacoes: any[];
    readonly grdContasPagar: MouraGridViewJSEditavel;
    readonly txtDocMercantil: MouraTextBoxProcura;
    readonly txtParcela: MouraTextBox;
    readonly txtFormaRecebimento: MouraTextBoxProcura;
    readonly txtContaContabil: MouraTextBoxProcura;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly txtValor: MouraTextBox;
    readonly txtDataVencimento: MouraTextBoxData;
    readonly txtPeriodoLocacaoCobranca: MouraTextBoxPeriodo;
    readonly grdIndenizacao: MouraGridViewJSEditavel;
    readonly txtDocMercantilInd: MouraTextBoxProcura;
    readonly txtParcelaInd: MouraTextBox;
    readonly txtFormaRecebimentoInd: MouraTextBoxProcura;
    readonly txtContaContabilInd: MouraTextBoxProcura;
    readonly cboContaCorrenteInd: MouraContaCorrenteCombo;
    readonly txtValorInd: MouraTextBox;
    readonly txtDataVencimentoInd: MouraTextBoxData;
    readonly cboMotivoInd: MouraComboBox;
    readonly btnFichaDevolucao: MouraButton;
    readonly btnSolicitacaoRetirada: MouraButton;
    readonly txtHoraDevolucao: MouraTextBoxHora;
    readonly txtDataDevolucao: MouraTextBoxData;
    readonly txtDescricaoAvarias: MouraTextBox;
    readonly lstDeclaracoes: MouraRadioButtonList;
    Devolucao: any;
    Devolucoes: any[];
    readonly grdDevolucao: MouraGridViewJSEditavel;
    readonly btnFichaManutencao: MouraButton;
    readonly txtHoraManutencao: MouraTextBoxHora;
    readonly txtDataManutencao: MouraTextBoxData;
    Manutencao: any;
    Manutencoes: any[];
    readonly grdEquipamento: MouraGridViewJSEditavel;
    readonly btnFichaSubstituicao: MouraButton;
    readonly txtEquipamento: MouraTextBoxProcura;
    readonly cboDepositoSubstituicao: MouraComboBox;
    readonly btnEstoqueSubstituicao: MouraButton;
    readonly lblEstoqueAtualSubstituicao: MouraLabel;
    readonly txtPrecoLocacaoSubstituicao: MouraTextBox;
    readonly txtDescontoUnitarioSubstituicao: MouraTextBox;
    readonly txtDescontoUnitarioPorcSubstituicao: MouraTextBox;
    readonly txtHoraSubstituicao: MouraTextBoxHora;
    readonly txtDataSubstituicao: MouraTextBoxData;
    EquipamentoRemover: any;
    EquipamentosRemover: any[];
    readonly grdEquipamentoRemover: MouraGridViewJSEditavel;
    EquipamentoAdicionar: any;
    EquipamentosAdicionar: any[];
    readonly grdEquipamentosAdicionar: MouraGridViewJSEditavel;
    readonly mdEstoque: MouraModal;
    readonly lblProduto: MouraLabel;
    readonly grdDepositoEstoque: MouraGridViewJS;
    readonly mdImprimir: MouraModal;
    readonly lblImprimir: MouraLabel;
    readonly grdImprimir: MouraGridViewJS;
    readonly txtClienteObra: MouraTextBoxProcuraClienteObra;
    readonly txtNomeObra: MouraTextBox;
    readonly txtEnderecoObra: MouraTextBox;
    readonly txtNumeroObra: MouraTextBox;
    readonly txtComplementoObra: MouraTextBox;
    readonly txtBairroObra: MouraTextBox;
    readonly txtCidadeObra: MouraTextBoxProcura;
    readonly txtContato: MouraTextBox;
    readonly txtTelefoneObra: MouraTextBoxTelefone;
    Obra: any;
    private respostaEstoque;
    private ProdutosExistentesLocacao;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Locacao_Equipamento): void;
    protected CarregarAbas(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected OnAntesGravar(): boolean;
    protected PreencherProdutos(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): boolean;
    protected PreencherContasReceber(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): void;
    protected PreencherIndenizacoes(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): void;
    protected PreencherDevolucoes(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): SiSMoura.Core.Entity.Locacao_Equipamento_Devolucao;
    protected PreencherManutencoes(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): void;
    protected PreencherSubstituicoes(entidade: SiSMoura.Core.Entity.Locacao_Equipamento): boolean;
    protected ValidarAbasVisiveis(): void;
    protected AtualizarUltimaLocacao(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Locacao_Equipamento): void;
    protected LimparEquipamento(): void;
    protected LimparObra(): void;
    protected OnClickFichaDevolucao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickFichaManutencao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickFichaSubstituicao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirFatura(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): boolean;
    protected OnClickSolicitacaoRetirada(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirDoc(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickImprimirContrato(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Imprimir(codLocacao: number, codModelo: number, codTransacao: number): void;
    protected OnClickEstoque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickEstoqueSubstituicao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnConsultarCEPLocatario(s: any, e: MouraTextBoxCepPesquisouEventArgs): void;
    protected OnConsultarCEPObra(s: any, e: MouraTextBoxCepPesquisouEventArgs): void;
    protected MudouTipo(newValue: any, oldValue: any): void;
    protected MudouDeclaracao(newValue: any, oldValue: any): void;
    protected OnPesquisouCliente(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouProduto(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouEquipamento(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnValidandoEstoqueProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnValidandoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnValidandoItemSubstituicao(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnLimpandoItemContasPagar(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnLimpandoItemIndenizacao(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected LimparCamposIndenizacao(): void;
    protected OnValidandoItemContasPagar(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnValidandoItemIndenizacao(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAdiciouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected totalizarProdutos(entidade?: SiSMoura.Core.Entity.Locacao_Equipamento, gravando?: boolean): boolean;
    protected RetornaValorCalculado(valor: number): number;
    protected AtualizarEstoqueAtual(): void;
    protected AtualizarEstoqueAtualSubstituicao(): void;
    protected OnExcluindoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnGrdProdutosSelecionouItem(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OngrdDepositoEstoqueSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdEquipamentosAdicionarSelecionouItem(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private flag;
    protected OnEditandoItemDevolucao(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnComboBoxDepositoChange(): void;
    protected OnComboBoxDepositoSubstituicaoChange(): void;
    protected OnTxtPrecoLocacaoChange(): void;
    protected OnTxtPrecoLocacaoSubstituicaoChange(): void;
    protected OnTxtDescontoUnitarioChange(): void;
    protected OnTxtDescontoUnitarioSubstituicaoChange(): void;
    protected OnTxtDescontoUnitarioPorcChange(): void;
    protected OnTxtDescontoUnitarioPorcSubstituicaoChange(): void;
    protected OnTxtDescontoRChange(): void;
    protected OnTxtDescontoRPorcChange(): void;
    protected OnTxtDeslocRetiradaChange(): void;
    protected OnTxtDeslocEntregaChange(): void;
    protected GetTotal(): number;
    protected OnDataDevolucaoChange(): void;
    protected OnHoraDevolucaoChange(): void;
    protected OnDataManutencaoChange(): void;
    protected OnHoraManutencaoChange(): void;
    protected OnDataSubstituicaoChange(): void;
    protected OnHoraSubstituicaoChange(): void;
    protected OnPeriodoLocacaoInicioChange(): number;
    protected OnPeriodoLocacaoFimChange(): void;
    protected AlterarEntidadeData(data: Date, hora: Date): Date;
    protected OnTxtClienteObraProcurouObra(s: MouraTextBoxProcuraClienteObra, e: MouraEventArgs): void;
    protected PreencherObra(retorno: any): void;
}
declare var c_Loca: C_Loca;
//# sourceMappingURL=C_Loca.d.ts.map