declare class R_PlaEst extends MouraPageRelacaoAngular {
    readonly AccordionFiltros: MouraAccordion;
    private isLoad;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly lblValorTotal: MouraLabel;
    readonly txtFornecedorPedido: MouraTextBoxProcura;
    readonly hdnURLPedido: HTMLInputElement;
    readonly hdnURLConsultaVenda: HTMLInputElement;
    readonly hdnCodPedido: HTMLInputElement;
    readonly txtProduto: MouraTextBoxProcura;
    readonly MouraTabPanel1: MouraTabPanel;
    readonly cboConsidererProdutos: MouraComboBox;
    readonly chkConsiderarEstoqueMinimo: MouraCheckBox;
    readonly chkPreencherProdutoSugestaoCompra: MouraCheckBox;
    readonly chkConsiderarEstoqueMaximo: MouraCheckBox;
    readonly chkNaoCalcularSeguranca: MouraCheckBox;
    readonly chkProdutoFarmaciaPopular: MouraCheckBox;
    readonly chkApenasMaiorZero: MouraCheckBox;
    readonly txtGrupoLista: MouraTextBoxProcuraComLista;
    readonly txtSubGrupoLista: MouraTextBoxProcuraComLista;
    readonly txtMarca: MouraTextBoxProcuraComLista;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboDeposito: MouraComboBox;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly lstDeposito: MouraCheckBoxList;
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly txtProjecao: MouraTextBox;
    readonly lblA: MouraLabel;
    readonly lblB: MouraLabel;
    readonly lblC: MouraLabel;
    readonly grid: MouraGridViewJS;
    readonly gridConsolidado: MouraGridViewJS;
    readonly cboFormaPagamento: MouraComboBox;
    readonly btnGerarPedido: MouraButton;
    readonly mdDiscriminar: MouraModal;
    readonly grdDiario: MouraGridViewJS;
    readonly grdMensal: MouraGridViewJS;
    readonly accCadastro: MouraAccordion;
    readonly txtReferencia: MouraTextBox;
    readonly txtLinha: MouraTextBoxProcura;
    readonly txtCor: MouraTextBoxProcura;
    protected Init(): void;
    OnPageLoad(): void;
    protected validarData(): void;
    protected OnComboBoxEmpresaChange(): void;
    protected ValidarAbaConsolidado(): boolean;
    protected AlteraDeposito(): void;
    protected OnPesquisouFornecedorPedido(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouFornecedor(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoLinhaConsolidado(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected ValidarProdutoInativoEmpresa(): void;
    protected OnAntesAbrirProcuraProd(s: MouraTextBoxProcura, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnPesquisouProduto(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    private ValidarProdutoFornecedor;
    protected ValidarFornocedorEmpresa(): void;
    protected PreencherGrade(): void;
    protected OnGerouGrade(d: any): void;
    protected LimparCampos(): void;
    private OnTabChange;
    private CalcularTotal;
    private DiscriminarVenda;
    private DiscriminarVendaConsolidado;
    private OnDepoisEditarItem;
    private OnDepoisEditarItemConsolidado;
    protected GerarPedido(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected GerarPedidoIndividualizado(): void;
    protected GerarPedidoConsolidado(): void;
    protected OnRepostaVisualizarPedido(result: MsgBoxResultEventArgs): void;
}
declare var r_PlaEst: R_PlaEst;
//# sourceMappingURL=R_PlaEst.d.ts.map