declare class C_RBaixa extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Contas_Receber> {
    private creditoCliente;
    private verificouData;
    private verificouResiduo;
    private verificouPedirSenha;
    readonly BaixaReceber: MouraBaixaReceberJS;
    readonly grid: MouraGridViewJS;
    readonly txtCliente: MouraTextBoxProcura;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly mdResiduo: MouraModal;
    readonly mdCredito: MouraModal;
    readonly btnCancelarResiduo: MouraButton;
    readonly btnLimpar: MouraButton;
    readonly btnBaixar: MouraButton;
    readonly btnOkResiduo: MouraButton;
    readonly btnOkCredito: MouraButton;
    readonly txtCodigo: MouraTextBoxProcura;
    Valor: any;
    Residuo: any;
    Credito: any;
    readonly txtMulta: MouraTextBox;
    Init(): void;
    OnPageLoad(): void;
    OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Contas_Receber): void;
    Limpar(): void;
    private OnClickLimpar;
    private OnClickCancelarResiduo;
    private CalculaTotalBaixaReceber;
    private PreencherGrade;
    private OnClickBaixar;
    private OnProcurouCliente;
    private OnMudouEmpresa;
    private GetValorCredito;
    private IsContaReceberEmpresas;
    ValidarCamposObrigatorios(): boolean;
    private BaixarContaReceber;
    private ValidarCredito;
    private ValidarResiduo;
    private ValidarBaixa;
    private BaixarConta;
    private OnBaixouConta;
    private ImprimirRecibo;
    private OnClickOkResiduo;
    private OnClickOkCredito;
    private OnSelecionouLinha;
    private ObterPorcentagemMulta;
    private CalularPorcentagemMulta;
}
declare const c_RBaixa: C_RBaixa;
//# sourceMappingURL=C_RBaixa.d.ts.map