declare var jKanban: any;
declare class C_SprintP extends MouraPageRelacaoAngular {
    readonly AccordionFiltros: MouraAccordion;
    readonly cboSprint: MouraComboBox;
    readonly cboStaus: MouraComboBox;
    readonly txtDescricao: MouraTextBox;
    readonly txtPeriodoSprint: MouraTextBoxPeriodo;
    readonly txtPeriodoAnalise: MouraTextBoxPeriodo;
    readonly txtPeriodoDesenvolvimento: MouraTextBoxPeriodo;
    readonly chkFreelancer: MouraCheckBox;
    readonly chkLiberacaoMensal: MouraCheckBox;
    readonly DivKambam: JQuery<HTMLElement>;
    readonly btnCadastro: MouraButton;
    readonly btnFecharSprint: MouraButton;
    readonly mdCadastro: MouraModal;
    readonly cboPeriodoSprint: MouraComboBox;
    readonly txtAtividade: MouraTextBoxProcura;
    readonly txtProgramador: MouraTextBoxProcura;
    readonly grdAtividades: MouraGridViewJS;
    readonly grdProgramadores: MouraGridViewJS;
    readonly btnSalvarSprint: MouraButton;
    readonly btnFecharInf: MouraButton;
    readonly btnAdicionarAtividade: MouraButton;
    readonly mdInf: MouraModal;
    readonly lblDataCadInf: MouraLabel;
    readonly lblDiasDesenv: MouraLabel;
    readonly btnConsultarAtividade: MouraButton;
    readonly grdKanban: MouraGridViewJS;
    Sprint: SiSMoura.Core.Entity.Console_Sprint;
    Atividade: SiSMoura.Core.Entity.ConsoleAtividadeInformacoesRetorno;
    DadosAtividade: SiSMoura.Core.Entity.ConsoleAtividadeInformacoesRetorno;
    readonly IsLiderProgramacao: boolean;
    readonly mdProcurarAtividades: MouraModal;
    readonly grdAtv: MouraGridViewJS;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtCliente: MouraTextBoxProcura;
    protected LimparCampos(): void;
    Info: any;
    readonly chkTransbordo: MouraCheckBox;
    readonly chkPodeAtrasar: MouraCheckBox;
    readonly optTipo: MouraRadioButtonList;
    readonly agpSprint: MouraAgrupamento;
    readonly chkExibirFinalizadas: MouraCheckBox;
    readonly btnAlterarHoras: MouraButton;
    readonly mdTransbordo: MouraModal;
    readonly lblAtividadeTransbordo: MouraLabel;
    readonly lblProgramadorOriginalTransbordo: MouraLabel;
    readonly cboSprintTransbordo: MouraComboBox;
    readonly txtProgramadorTransbordo: MouraTextBoxProcura;
    readonly chkPodeAtrasarTransbordo: MouraCheckBox;
    readonly btnConfirmarTransbordo: MouraButton;
    readonly btnFecharTransbordo: MouraButton;
    OnPageLoad(): void;
    protected AlterouData(newValue: any, oldValue: any): void;
    protected kanban: any;
    protected Init(): void;
    protected HabilitaCampos(): void;
    protected OnAlterouOptTipo(s: any, e: any): void;
    protected OnAlterouCheckFinalizado(s: any, e: any): void;
    protected AlterarTipo(atualizarGrid: boolean): void;
    protected PreencherComboStatus(): void;
    protected PreencherComboSprint(): void;
    PreencherGrade(): void;
    protected OnClickCadastro(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CalculaTotaisSprint(): void;
    protected CalcularHorasProgramadores(diasDesenvolvimento: number): void;
    protected GetSomaHorasUtilizadasProgramador(codProgramador: number): number;
    protected GetItemProgramador(codProgramador: number): SiSMoura.Core.Entity.SprintProgramadorRetorno;
    protected OnClickSalvarSprint(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected FecharModalCadastro(): void;
    protected OnPesquisouAtividade(s: any, e: any): void;
    protected OnClickAdicionarAtividade(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected AdicionarAtividade(verificarProgramadorHoras: boolean): void;
    protected OnClickFecharSprint(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnIndexChangedSprint(s: any, e: any): void;
    protected OnIndexChangedPeriodo(s: any, e: any): void;
    protected ConsultarAtividade(codAtividade: number): void;
    protected OnSelecionouLinhaAtividade(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnExcluiuAtividade(s: any, e: any): void;
    protected OnExclindoAtividade(s: any, e: MouraGridViewJSItemCancelavelEventArgs): void;
    protected OnEditandoItemProgramadores(s: any, e: any): void;
    protected OnEditouItemProgramadores(s: any, e: any): void;
    protected OnGridCellPreparedProgramadores(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnClickFecharModalInf(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickConsultarAtividade(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickProcurarAtividades(): void;
    protected OnClickRelacaoAtividades(): void;
    protected OnClicouLinhaRelacao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnSelecionouLinhaKanban(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnSelecionouLinhaRelacao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickFinalizarPlanejamento(): void;
    protected OnClickAlterarHoras(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnGridAtividadesCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnGridKanbamCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnClickFecharTransbordo(s: any, e: MouraClickEventArgs): void;
    protected OnClickSalvarTransbordo(s: any, e: MouraClickEventArgs): void;
    protected PreencherComboSprintTransbordo(): void;
    protected OnClickBotaoLinhaAtividade(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoLinhaKanban(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected AbrirTelaTransbordoAtividade(codAtividade: number, codProgramador: number, nomeProgramador: string): void;
}
declare var c_SprintP: C_SprintP;
//# sourceMappingURL=C_SprintP.d.ts.map