declare class C_ContPlan extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Contrato_Plano> {
    private PATH_DOCUMENTOS_HOSPEDAGEM;
    private isContratoFilhote;
    private isMudouTipoPlano;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly cboPlano: MouraComboBox;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly lblTempoContrato: MouraLabel;
    readonly grdTriagemItens: MouraGridViewJS;
    readonly txtProfissional_Responsavel: MouraTextBoxProcura;
    readonly txtDataTriagem: MouraTextBoxData;
    readonly txtTriagemProcura: MouraTextBoxProcura;
    readonly txtParcelas: MouraTextBox;
    readonly txtVencimentoInicial: MouraTextBoxData;
    readonly txtValorContrato: MouraTextBox;
    readonly cboTipoDias: MouraComboBox;
    readonly cboScore: MouraComboBox;
    readonly txtDias: MouraTextBox;
    readonly txtContaContabil: MouraTextBoxProcura;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly btnGerar: MouraButton;
    readonly grdParcelas: MouraGridViewJS;
    readonly lblStatusContrato: MouraLabel;
    readonly lblDescricaoPontuacao: MouraLabel;
    CarenciasServicos: SiSMoura.Core.Entity.Animais_Contrato_Plano_Carencias[];
    CarenciaServico: SiSMoura.Core.Entity.Animais_Contrato_Plano_Carencias;
    readonly hdnConfigPetz: HTMLInputElement;
    readonly ConfigPetz: SiSMoura.Core.Entity.Petz_Configuracao_Integracao;
    readonly URLStoom: string;
    readonly txtPeriodo_Vigencia: MouraTextBoxPeriodo;
    readonly txtValorMensalidade: MouraTextBox;
    readonly btnEmitirContrato: MouraButton;
    readonly cboModelo: MouraComboBox;
    readonly btnAnexos: MouraButton;
    readonly dlgAnexo: MouraModalAnexo;
    readonly grdServicoCarencia: MouraGridViewJSEditavel;
    readonly txtServico: MouraTextBoxProcura;
    readonly cboTipoCobranca: MouraComboBox;
    readonly mdmdCancelamento: MouraModal;
    readonly txtValorPago: MouraTextBox;
    readonly txtParcelaAtual: MouraTextBox;
    readonly txtParcelaDevolver: MouraTextBox;
    readonly txtValorTotalDevolver: MouraTextBox;
    readonly btnCancelarContrato: MouraButton;
    protected Init(): void;
    protected OnMudouCobranca(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected VerificaExistenciaServico(codServico: number): boolean;
    protected OnValidandoItemCarencia(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected EditouTriagem(s: any, e: any): void;
    protected ValidandoTriagem(s: any, e: any): void;
    private OnBtnAnexoClick;
    protected OnClickBotaoImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnTxtTriagemProcuraProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Contrato_Plano): void;
    OnPageLoad(): void;
    protected CarregarParcelasGeradas(): void;
    protected OnAlterouPlano(): void;
    protected CalcularTotalPontos(): number;
    protected AlterarValorPlano(entity: SiSMoura.Core.Entity.Animais_Contrato_Plano): void;
    protected OnAntesGravar(): boolean;
    protected isContratoSalvo(): boolean;
    private flagPagamento;
    protected OnClickBotaoFecharModal(): void;
    protected OnClickCancelarContratoAnual(): void;
    protected OnClickBotaoPagamento(): void;
    protected OnDepoisGravar(): boolean;
    protected IniciarPagamento(pessoa: SiSMoura.Core.Entity.PessoaBasicoRetorno): void;
    protected OnClickBotaoCancelarPagamento(): void;
    protected OnClickAlterarPagamento(): void;
    protected GetDadosAnimal(codAnimal: number): SiSMoura.Core.Entity.AnimaisCadastroBasicoRetorno;
    protected OnClickEmailAlterarPagamento(): void;
    protected OnClickAtualizarStatus(): void;
    protected OnAntesBuscarExistente(): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Animais_Contrato_Plano): void;
    protected IsBloquearContrato(Entidade: SiSMoura.Core.Entity.Animais_Contrato_Plano): boolean;
    protected HabilitaCamposPagamento(habilitar: boolean): void;
    protected AtualizarStatusContrato(entity: SiSMoura.Core.Entity.Animais_Contrato_Plano): void;
    protected OnPesquisouPet(s: any, e: any): void;
    protected OnFechouModalPagamento(s: any, e: any): void;
    protected AtualizarDadosTela(): void;
}
declare const c_ContPlan: C_ContPlan;
//# sourceMappingURL=C_ContPlan.d.ts.map