declare class C_ComPed extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Pedido_Compra> {
    private itens;
    private finalizado;
    readonly hdnAprovado: HTMLInputElement;
    readonly lblUltimoPedido: MouraLabel;
    readonly lblDuplicataMsg: MouraLabel;
    readonly lblEstoqueAtual: MouraLabel;
    readonly lblProduto: MouraLabel;
    readonly lblTotalFinal: MouraLabel;
    readonly cboDeposito: MouraComboBox;
    readonly cboSituacaoPedido: MouraComboBox;
    readonly btnCancelarDup: MouraButton;
    readonly btnOkDuplicatas: MouraButton;
    readonly txtFornecedorD: MouraTextBoxProcura;
    readonly txtDataEmissaoD: MouraTextBoxData;
    readonly btnGerar: MouraButton;
    readonly txtParcelas: MouraTextBox;
    readonly txtDescricaoProduto: MouraTextBox;
    readonly txtDias: MouraTextBox;
    readonly cboTipoDias: MouraComboBox;
    readonly txtVencInicial: MouraTextBoxData;
    readonly txtContaContabil: MouraTextBoxProcura;
    readonly cboFormaPagamentoD: MouraComboBox;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly cboDocMercantil: MouraComboBox;
    readonly txtNDocBancario: MouraTextBox;
    Parcelas: SiSMoura.Core.Entity.PedidoCompraDuplicata[];
    readonly txtCodigo: MouraTextBoxProcura;
    readonly hdnPedido: HTMLInputElement;
    readonly hdnFinalizado: HTMLInputElement;
    readonly hdnFormaPagamento: HTMLInputElement;
    readonly hdnProdutoSelecionado: HTMLInputElement;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtCotacao: MouraTextBoxProcura;
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly txtEmail: MouraTextBoxProcura;
    readonly txtFornecedorE: MouraTextBoxProcura;
    readonly lblUltCompra: MouraLabel;
    readonly txtQuantidade: MouraTextBox;
    readonly txtPrecoCusto: MouraTextBox;
    readonly txtDescontoUnitario: MouraTextBox;
    readonly txtDescontoUnitarioPorc: MouraTextBox;
    readonly txtICMS: MouraTextBox;
    readonly txtIPIPorc: MouraTextBox;
    readonly txtIPI: MouraTextBox;
    readonly hdnEmpresa: HTMLInputElement;
    readonly grdProdutos: MouraGridViewJSEditavel;
    readonly grdParcelas: MouraGridViewJS;
    Produtos: SiSMoura.Core.Entity.PedidoProdutoRetorno[];
    Produto: SiSMoura.Core.Entity.PedidoProdutoRetorno;
    readonly txtDescontoR: MouraTextBox;
    readonly txtDescontoPorc: MouraTextBox;
    readonly txtDescontoPorc_2: MouraTextBox;
    readonly txtDescontoPorc_3: MouraTextBox;
    readonly btnDuplicatas: MouraButton;
    readonly btnFinalizarEntrega: MouraButton;
    readonly btnExportarArquivo: MouraButton;
    readonly btnAprovar: MouraButton;
    readonly btnEnviarEmail: MouraButton;
    readonly btnImportarSolicitacao: MouraButton;
    readonly btnPlanejamentoCompra: MouraButton;
    readonly hdnURLPlanejamento: HTMLInputElement;
    readonly btnImprimir: MouraButton;
    readonly btnEstoque: MouraButton;
    readonly mdEstoque: MouraModal;
    readonly mdDuplicatas: MouraModal;
    readonly mdImportarSolicitacao: MouraModal;
    readonly grdDepositoEstoque: MouraGridViewJS;
    readonly btnImprimirApenasNChegaram: MouraButton;
    readonly mdImprimirApenasNChegaram: MouraModal;
    readonly grdImprimirApenasNChegaram: MouraGridViewJS;
    readonly btnHistoricoProduto: MouraButton;
    readonly mdHistoricoProduto: MouraModal;
    readonly grdHistoricoDoProduto: MouraGridViewJS;
    readonly lstTipoHistorico: MouraRadioButtonList;
    readonly chkPedidosAprovados: MouraCheckBox;
    readonly chkPedidosVinculadosEntradaProduto: MouraCheckBox;
    readonly lblHistoricoProduto: MouraLabel;
    readonly txtValorFrete: MouraTextBox;
    readonly cboFormaPagamento: MouraComboBox;
    readonly lblNotasJaChegaram: MouraLabel;
    readonly btnImportarProdutos: MouraButton;
    readonly mdImpProdCompra: MouraModal;
    readonly cboDepositoImp: MouraComboBox;
    readonly txtFornecedorImp: MouraTextBoxProcura;
    readonly txtGrupoImp: MouraTextBoxProcura;
    readonly txtSubGrupoImp: MouraTextBoxProcura;
    readonly txtReferenciaImp: MouraTextBox;
    readonly txtLinhaImp: MouraTextBoxProcura;
    readonly txtCorImp: MouraTextBoxProcura;
    readonly txtMarcaImp: MouraTextBoxProcura;
    readonly btnGerarImp: MouraButton;
    readonly grdImportarProdutos: MouraGridViewJSEditavel;
    readonly btnConcluirImp: MouraButton;
    ImpProd: any;
    ImpProds: any[];
    protected Init(): void;
    OnPageLoad(): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected SelecionarRegistro(s: any, e: MouraGridViewSelecionouEventArgs): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Pedido_Compra): void;
    protected IniciarCamposProduto(): void;
    protected PreencherComboFormaPagamento(entidade: SiSMoura.Core.Entity.Pedido_Compra): void;
    private verificadoAutorizacaoAprovar;
    protected OnAntesSetEntidade(eventArg: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Pedido_Compra>): void;
    private alterarBotaoEmail;
    private alterarBotaoImprimirApenasNChegaram;
    private alterarBotaoFinalizarEntrega;
    private alterarBotaoAprovar;
    private alterarBotaoEstoque;
    private alterarBotaoOkDuplicata;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Pedido_Compra): void;
    protected OnComboBoxEmpresaChange(): void;
    protected OnComboBoxDepositoChange(): void;
    protected OnComboBoxFormaPagamentoChange(): void;
    protected OnComboBoxTipoDiasChange(): void;
    protected AtualizarDeposito(): void;
    protected AtualizarEstoqueAtual(): void;
    protected AtualizarUltimoPedido(): void;
    protected OnPesquisouCotacao(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected ValidarProdutoInativoEmpresa(): void;
    private ValidarProdutoFornecedor;
    protected OnPesquisouContaContabil(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouDadosProduto(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected ValidarFornocedorEmpresa(): void;
    protected OnPesquisouFornecedorE(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnPesquisouFornecedor(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    private AtualizarDataUltimaCompra;
    protected OnTxtIPIPorcChange(): void;
    protected OnTxtIPIChange(): void;
    protected OnTxtPrecoCustoChange(): void;
    protected OnTxtDescontoUnitarioChange(): void;
    protected OnTxtDescontoUnitarioPorcChange(): void;
    protected OnTxtDescontoRChange(): void;
    protected OnTxtDescontoPorcChange(): void;
    protected OnTxtValorFreteChange(): void;
    protected OnSetouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnLimpouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnValidandoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnExcluindoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected onItemGridExcluiuSucesso(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAdiciouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAdicionandoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected totalizarProdutos(entidade?: SiSMoura.Core.Entity.Pedido_Compra): boolean;
    protected GetTotal(): number;
    protected GetDescontoUnitarioTotal(): number;
    protected GetIPITotal(): number;
    protected GetICMSTotal(): number;
    protected OnClickFinalizar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAprovar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Aprovar(): void;
    protected OnRepostaAprovarPedido(result: MsgBoxResultEventArgs): void;
    protected OnRepostaFinalizarPedido(result: MsgBoxResultEventArgs): void;
    protected ValidarBotaoValidar(): void;
    protected ValidarEstadoBotoes(): void;
    protected ValidarBotaoFinalizar(): void;
    protected VerificarAutorizacaoAprovar(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnClickImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickExportar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickPlanejamentoEstoque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImportarSolicitacao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickEstoque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarDuplicata(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOKDuplicata(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickGerarDuplicata(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickDuplicata(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnDepoisEditarItem(s: any, e: MouraGridViewJSItemEventArgs): void;
    protected OnClickImprimirApenasNChegaram(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickHistoricoProduto(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnlstTipoHistoricoChange(): void;
    protected OnCheckPedidosAprovadosChange(): void;
    protected OnCheckPedidosVinculadosChange(): void;
    protected LimparCamposHistoricoProduto(): void;
    protected PreencherHistoricoProduto(): void;
    protected OnGrdProdutosSelecionouItem(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAntesGravar(): boolean;
    private PreencherProdutos;
    protected OnDepoisGravar(): boolean;
    protected OnAntesDeletar(): boolean;
    protected RetornaNotasJaChegaram(): string;
    protected AtualizaTotal(): void;
    protected OntxtProdutoChange(): void;
    protected LimparModalImportarProdutos(): void;
    protected OnClicouImportarProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnFechouMdImportar(e: MouraEventHandler): void;
    protected OnClicouGerarImportarProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClicouConcluirImportarProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnValidandoGrdImportar(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnDescPorcImportarChange(entity: any): void;
    protected OnDescRealImportarChange(entity: any): void;
    protected OnIPIPorcImportarChange(entity: any): void;
    protected OnIPIRealImportarChange(entity: any): void;
}
declare var c_ComPed: C_ComPed;
//# sourceMappingURL=C_ComPed.d.ts.map