declare class C_ChCada extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Cheques> {
    readonly cboSituacaoFiltro: MouraComboBox;
    readonly cboContaCorrente: MouraContaCorrenteCombo;
    readonly cboSituacao: MouraComboBox;
    readonly Grid: MouraGridViewJS;
    readonly GridConsulta: MouraGridViewJS;
    readonly GridHistorico: MouraGridViewJS;
    readonly txtBanco: MouraTextBox;
    readonly txtNomeTitular: MouraTextBox;
    readonly btnConsultar: MouraButton;
    readonly btnGerarHistorico: MouraButton;
    readonly btnOkBaixaCheque: MouraButton;
    readonly btnFecharConsulta: MouraButton;
    readonly mdConsulta: MouraModal;
    readonly mdBaixaCheque: MouraModal;
    readonly txtAgencia: MouraTextBox;
    readonly txtConta: MouraTextBox;
    readonly txtCPF: MouraTextBoxCPF;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtEnviado: MouraTextBoxProcura;
    readonly txtCliente: MouraTextBoxProcura;
    readonly cboTipo: MouraComboBox;
    readonly txtVenda: MouraTextBox;
    Filtro: any;
    readonly txtTipoLancamentoBaixa_hdnEmpresaContabil: HTMLInputElement;
    readonly txtTipoLancamentoBaixa: MouraTextBoxProcuraConfiguracaoContabil;
    readonly txtTipoLancamento_hdnEmpresaContabil: HTMLInputElement;
    readonly txtTipoLancamento: MouraTextBoxProcuraConfiguracaoContabil;
    protected Init(): void;
    PreencherEmpresaContabil(codEmpresa: any): void;
    OnPageLoad(): void;
    protected OnProcurarClienteCPF(): void;
    protected MudouTipo(newValue: any, oldValue: any): void;
    protected MudarLabelComponente(componente: MouraCampo, novoTexto: string): void;
    protected OnPesquisouCliente(): void;
    protected OnPesquisouEnviado(): void;
    protected OnPesquisouLancamento(): void;
    protected ProcurouLancamentoBaixa(): void;
    protected OnClickFecharConsulta(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBaixaCheque(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickGerarHistorico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickConsultar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected MudouVenda(): void;
    protected MudouContaCorrente(): void;
    protected MudouSituacao(): void;
    protected MudouFiltro(): void;
    protected OnAntesGravar(): boolean;
    protected OnRespondeuMensagemExistente(result: MsgBoxResultEventArgs): void;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Cheques): void;
    protected PreencherGridHistorico(): void;
    protected PreencherGridConsulta(): void;
    protected GetCadastrados(): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Cheques): void;
}
declare const c_ChCada: C_ChCada;
//# sourceMappingURL=C_ChCada.d.ts.map