/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityFiscalNfce { 
    codigo?: number;
    nf?: number;
    chaveAcesso?: string;
    digitoChave?: number;
    dataArquivo?: Date;
    nomeArquivo?: string;
    protocoloEnvio?: string;
    digestEnvio?: string;
    dataEnvio?: Date;
    mensagemEnvio?: string;
    codigoFiscalNf?: number;
    empresa?: number;
    situacao?: string;
    dataSituacao?: Date;
    protocoloAutorizacao?: string;
    dataAutorizacao?: Date;
    ambiente?: string;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
