/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SismouraWebViewVendaCartaoMobile } from './sismouraWebViewVendaCartaoMobile';
import { SismouraWebViewVendaItemMobile } from './sismouraWebViewVendaItemMobile';


export interface SismouraWebViewVendaMobile { 
    codPDV?: number;
    codigo?: number;
    cliente?: number;
    nomeCliente?: string;
    cPFCliente?: string;
    data?: Date;
    subTotal?: number;
    valorDesconto?: number;
    valorAcrescimo?: number;
    totalFinal?: number;
    valorDinheiro?: number;
    valorChequeVista?: number;
    valorChequePrazo?: number;
    valorCliente?: number;
    valorTicket?: number;
    valorCartao?: number;
    valorTroco?: number;
    vendedor?: number;
    dadosCartao?: Array<SismouraWebViewVendaCartaoMobile>;
    itens?: Array<SismouraWebViewVendaItemMobile>;
}
