/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityAnimaisVeterinarioApiRetorno { 
    codigo?: number;
    nome?: string;
    tipoProfissional?: number;
    apelido?: string;
    mostrar?: boolean;
    urlFoto?: string;
    servicosPrestados?: Array<number>;
}
