/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityCartaoRecebido } from './siSMouraCoreEntityCartaoRecebido';
import { SiSMouraCoreEntityCheques } from './siSMouraCoreEntityCheques';
import { SiSMouraCoreEntityFiscalNf } from './siSMouraCoreEntityFiscalNf';
import { SiSMouraCoreEntityPessoa } from './siSMouraCoreEntityPessoa';
import { SiSMouraCoreEntityPostoBombaAbastecimento } from './siSMouraCoreEntityPostoBombaAbastecimento';
import { SiSMouraCoreEntitySatNf } from './siSMouraCoreEntitySatNf';
import { SiSMouraCoreEntityUsuario } from './siSMouraCoreEntityUsuario';
import { SiSMouraCoreEntityVendaCrediario } from './siSMouraCoreEntityVendaCrediario';
import { SiSMouraCoreEntityVendaItem } from './siSMouraCoreEntityVendaItem';
import { SiSMouraCoreEntityVendaPagamento } from './siSMouraCoreEntityVendaPagamento';
import { SiSMouraCoreEntityVendaTefDedicado } from './siSMouraCoreEntityVendaTefDedicado';
import { SiSMouraCoreEntityVendaTefDiscado } from './siSMouraCoreEntityVendaTefDiscado';


export interface SiSMouraCoreEntityVenda { 
    codigo?: number;
    cliente?: number;
    vendedor?: number;
    operador?: number;
    caixa?: number;
    pdv?: number;
    caixaInterno?: number;
    deposito?: number;
    clienteDelivery?: number;
    codVeiculo?: number;
    ecf?: number;
    codigoEntrega?: number;
    data?: Date;
    desconto?: number;
    cancelada?: boolean;
    dataCancelada?: Date;
    valorDinheiro?: number;
    valorChequeVista?: number;
    valorChequePrazo?: number;
    valorCartao?: number;
    valorTicket?: number;
    valorCliente?: number;
    cupomFiscal?: boolean;
    motivoCancelamento?: string;
    motorista?: string;
    placa?: string;
    condicaoPagamento?: number;
    codigoCupomFiscal?: number;
    nomeCliente?: string;
    cpfCliente?: string;
    km?: number;
    tipoImpressao?: string;
    acrescimo?: number;
    vendaPrecoCusto?: string;
    comandaMesa?: string;
    qtdePonto?: number;
    valorPonto?: number;
    valorContraVale?: number;
    cdc?: number;
    cdcDias?: number;
    vistaPrazo?: string;
    numeroEntrega?: number;
    enderecoCliente?: string;
    ccf?: number;
    dependente?: string;
    textoFinal?: string;
    dataCupom?: Date;
    cdcFator?: number;
    valorCredito?: number;
    notaFiscal?: number;
    valorCreditoUtilizado?: number;
    trocaOrigem?: number;
    versaoSistema?: string;
    numeroChamada?: number;
    foneCliente?: string;
    pontosUtilizados?: number;
    pedidoExterno?: string;
    emitiuVinculado?: string;
    comissionado?: number;
    mensagemFinalInformada?: string;
    comissaoComissionado?: number;
    pafDav?: string;
    pafPv?: string;
    pafDavTitulo?: string;
    pafCupomFiscalDav?: string;
    autorizacaoDatasus?: string;
    nomeParticipante?: string;
    cpfCnpjParticipante?: string;
    crmPrescritor?: string;
    ufPrescritor?: string;
    dataEmissaoPrescricao?: Date;
    valorFpCliente?: number;
    valorCartaoCredito?: number;
    valorCartaoDebito?: number;
    valorImpostos?: number;
    valorFpGoverno?: number;
    tefPassou?: string;
    roteadorPuxou?: boolean;
    usuarioCancelou?: number;
    usuarioLiberouDesconto?: number;
    carro?: string;
    entrega?: boolean;
    autorizacaoRedecon?: string;
    entregue?: boolean;
    quantidadePessoasMesa?: number;
    descontoManual?: boolean;
    encomendaSemanal?: boolean;
    ecfGt?: string;
    nomeComputador?: string;
    empresa?: number;
    pafMd5?: string;
    valorTroca?: number;
    textoIbpt?: string;
    produtos?: Array<SiSMouraCoreEntityVendaItem>;
    cartoes?: Array<SiSMouraCoreEntityCartaoRecebido>;
    vendaPagamentos?: Array<SiSMouraCoreEntityVendaPagamento>;
    cheques?: Array<SiSMouraCoreEntityCheques>;
    tefDedicadoList?: Array<SiSMouraCoreEntityVendaTefDedicado>;
    tefDiscadoList?: Array<SiSMouraCoreEntityVendaTefDiscado>;
    postoBombaAbastecimentoList?: Array<SiSMouraCoreEntityPostoBombaAbastecimento>;
    vendaCrediario?: SiSMouraCoreEntityVendaCrediario;
    satNf?: SiSMouraCoreEntitySatNf;
    fiscalNf?: SiSMouraCoreEntityFiscalNf;
    hash?: string;
    clienteEntity?: SiSMouraCoreEntityPessoa;
    vendedorEntity?: SiSMouraCoreEntityUsuario;
    usuarioLogadoEntity?: SiSMouraCoreEntityUsuario;
    codigoCFe?: number;
    codigoOrcamento?: number;
    contaReceberBaixada?: boolean;
    descontoPorcentagem?: number;
    isVendaPdvNet?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
