/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreCommonBanco } from './siSMouraCoreCommonBanco';
import { SiSMouraCoreEntityEmpresa } from './siSMouraCoreEntityEmpresa';
import { SiSMouraCoreEntityEmpresaRetorno } from './siSMouraCoreEntityEmpresaRetorno';
import { SiSMouraCoreEntityUsuarioLoginRetorno } from './siSMouraCoreEntityUsuarioLoginRetorno';
import { SismouraWebViewMouraMenu } from './sismouraWebViewMouraMenu';


export interface SismouraWebViewLoginControllerLoginRetorno { 
    usuario?: SiSMouraCoreEntityUsuarioLoginRetorno;
    empresa?: SiSMouraCoreEntityEmpresa;
    empresas?: Array<SiSMouraCoreEntityEmpresaRetorno>;
    menus?: Array<SismouraWebViewMouraMenu>;
    versao?: string;
    banco?: SiSMouraCoreCommonBanco;
}
