/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityFiscalNfProdutoAnilha } from './siSMouraCoreEntityFiscalNfProdutoAnilha';
import { SiSMouraCoreEntityFiscalRegraImposto } from './siSMouraCoreEntityFiscalRegraImposto';


export interface SiSMouraCoreEntityFiscalNFProdutoRetorno { 
    id?: string;
    item?: number;
    codigoProduto?: number;
    descricaoProduto?: string;
    quantidade?: number;
    valorUnitario?: number;
    valorSubTotal?: number;
    valorDesconto?: number;
    valorDescontoPorcentagem?: number;
    valorOutros?: number;
    cfop?: string;
    ncm?: string;
    unidade?: string;
    _CEST?: string;
    cst?: string;
    baseIcms?: number;
    aliquotaICMS?: number;
    valorIcms?: number;
    _IVA?: number;
    baseIcmsST?: number;
    aliquotaICMSST?: number;
    valorIcmsST?: number;
    stIpi?: string;
    baseIPI?: number;
    aliquotaIPI?: number;
    valorIpi?: number;
    codEnquadramentoIPI?: string;
    stPis?: string;
    aliquotaPis?: number;
    basePis?: number;
    valorPis?: number;
    stCofins?: string;
    aliquotaCofins?: number;
    baseCofins?: number;
    valorCofins?: number;
    aliquotaII?: number;
    baseII?: number;
    valorII?: number;
    valorTributos?: number;
    valorCreditoSN?: number;
    porcentagemCreditoSN?: number;
    modalidadeBaseICMS?: number;
    motivoDesoneracao?: number;
    modalidadeBaseICMSST?: number;
    numeroDI?: string;
    codExportador?: number;
    dataRegistro?: string;
    _UF?: string;
    local?: string;
    dataDesembaraco?: string;
    adicao?: string;
    codFabricante?: string;
    descontoImportacao?: number;
    aliquotaFCP?: number;
    valorFCP?: number;
    aliquotaFCPST?: number;
    valorFCPST?: number;
    percentualIPIDevolvido?: number;
    valorIPIDevolvido?: number;
    produtoAnilhas?: Array<SiSMouraCoreEntityFiscalNfProdutoAnilha>;
    valorAliqFed?: number;
    valorAliqEst?: number;
    valorAliqMun?: number;
    regraImposto?: SiSMouraCoreEntityFiscalRegraImposto;
    vlrICMSDesonerado?: number;
    motivoDesoneracaoICMS?: number;
    motivoDesoneracaoICMSDescricao?: string;
    porcentagemBaseICMSST?: number;
    codigoBeneficioFiscal?: string;
}
