/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityEmpresasApiRetorno { 
    codigo?: number;
    razaoSocial?: string;
    fantasia?: string;
    CNPJ?: string;
    endereco?: string;
    numeroEndereco?: string;
    bairro?: string;
    cidadeCodigo?: number;
    cidadeNome?: string;
    cidadeEstado?: string;
    padrao?: boolean;
    distancia?: number;
    enderecoOrigemResolvido?: string;
    favorita?: boolean;
    mostrar?: boolean;
    urlFoto?: string;
}
