/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityCartaoRecebido { 
    codigo?: number;
    cartao?: number;
    venda?: number;
    recebimento?: number;
    vencimento?: Date;
    valor?: number;
    valorFinal?: number;
    codigoTroca?: number;
    descontado?: number;
    juros?: number;
    descontadoParcela?: number;
    dataEmissao?: Date;
    cliente?: number;
    situacao?: number;
    orcamento?: number;
    lancamento?: number;
    lancamentoCodigo?: number;
    lancamentoTipo?: number;
    os?: number;
    nsu?: string;
    descricaoCartaoTefDedicado?: string;
    bandeiraCartaoTefDedicado?: number;
    operadoraCartaoTefDedicado?: string;
    codigoBaixaReceber?: number;
    parcela?: number;
    conciliado?: boolean;
    valorBrutoConciliado?: number;
    valorLiquidoConciliado?: number;
    dataPagamentoComissao?: Date;
    gerarLancamento?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
