/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityExactSalesContatoExact { 
    id?: number;
    email?: string;
    nome?: string;
    cargo?: string;
    telEmpresa?: string;
    tel2Empresa?: string;
    tipoMensageiro?: string;
    idMensageiro?: string;
}
