/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntitySatNfItem } from './siSMouraCoreEntitySatNfItem';
import { SiSMouraCoreEntitySatNfPagamento } from './siSMouraCoreEntitySatNfPagamento';
import { SiSMouraCoreEntitySatNfXml } from './siSMouraCoreEntitySatNfXml';


export interface SiSMouraCoreEntitySatNf { 
    codigo?: number;
    codCfe?: string;
    codSat?: number;
    venda?: number;
    vendedor?: number;
    codCliente?: number;
    nome?: string;
    cpfCnpj?: string;
    endereco?: string;
    numero?: string;
    bairro?: string;
    cep?: string;
    municipio?: string;
    uf?: string;
    dataEmissao?: Date;
    baseIcms?: number;
    valorIcms?: number;
    baseSubst?: number;
    valorSubst?: number;
    totalProduto?: number;
    valorDesconto?: number;
    outrasDespesas?: number;
    valorBaseIss?: number;
    valorIss?: number;
    valorTroco?: number;
    valorTotal?: number;
    valorPis?: number;
    valorCofins?: number;
    valorTotalIbpt?: number;
    cancelado?: boolean;
    chaveCfe?: string;
    assinaturaQrcode?: string;
    situacao?: string;
    mensagemRetorno?: string;
    ispendenteenvio?: boolean;
    codPdv?: number;
    importado?: boolean;
    codCfeCancelamento?: string;
    chaveAcessoCancelamento?: string;
    satNfXml?: SiSMouraCoreEntitySatNfXml;
    satPagamentos?: Array<SiSMouraCoreEntitySatNfPagamento>;
    satItens?: Array<SiSMouraCoreEntitySatNfItem>;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
