/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityVendaPagamento { 
    venda?: number;
    parcela?: number;
    dataVencimento?: Date;
    valor?: number;
    autorizacaoAfapi?: number;
    documentoMercantil?: number;
    documentoBancario?: number;
    autorizacaoOrgcard?: string;
    cdc?: boolean;
    nDocMerc?: string;
    id?: number;
    contaCorrente?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
