/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityConsolePdvmovelDispositivo { 
    codigo?: number;
    cliente?: number;
    descricao?: string;
    dispositivo?: string;
    id?: string;
    tipo?: number;
    status?: number;
    dataInclusao?: Date;
    codigoPDV?: number;
    deposito?: number;
    casaDecimalValor?: number;
    casaDecimalQtde?: number;
    tipoEmissaoFiscal?: number;
    nFCeSerie?: number;
    nFCeEnviarContigencia?: boolean;
    nFCeIsHomologacao?: boolean;
    nFCeIdToken?: string;
    nFCeToken?: string;
    dispositivoIpTef?: string;
    dispositivoEmpresaTef?: string;
    dispositivoTerminalTef?: string;
    dispositivoAdicionaisTef?: string;
    isPdvComanda?: boolean;
    readonly isHabilitado?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
