/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SismouraWebViewPetMouraAplicativoModelPagamentoAPPCartaoAPI { 
    codigoAtendimento?: number;
    numeroCartao?: string;
    mes?: number;
    ano?: number;
    codigoSeguranca?: string;
    nomeCliente?: string;
    CPF?: string;
    salvarCartao?: boolean;
    cartaoID?: string;
    cartaoToken?: string;
}
