/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreCommonFiltroProcura { 
    valor?: any;
    tipoLike?: SiSMouraCoreCommonFiltroProcura.TipoLikeEnum;
    campo?: string;
}
export namespace SiSMouraCoreCommonFiltroProcura {
    export type TipoLikeEnum = 0 | 1 | 2 | 3;
    export const TipoLikeEnum = {
        NUMBER_0: 0 as TipoLikeEnum,
        NUMBER_1: 1 as TipoLikeEnum,
        NUMBER_2: 2 as TipoLikeEnum,
        NUMBER_3: 3 as TipoLikeEnum
    };
}
