/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SismouraWebViewModelsPedidosListaPreco } from './sismouraWebViewModelsPedidosListaPreco';
import { SismouraWebViewModelsPedidosProduto } from './sismouraWebViewModelsPedidosProduto';


export interface SismouraWebViewModelsPedidosOrcamentoItemPedido { 
    item?: number;
    descontoAbsoluto?: number;
    descontoRelativo?: number;
    preco?: number;
    produto?: SismouraWebViewModelsPedidosProduto;
    quantidade?: number;
    subtotal?: number;
    total?: number;
    listaPreco?: SismouraWebViewModelsPedidosListaPreco;
    produtoPreco?: number;
    estoqueAtual?: number;
}
