/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SismouraWebViewModelsPedidosRotaVendaCliente } from './sismouraWebViewModelsPedidosRotaVendaCliente';


export interface SismouraWebViewModelsPedidosRotaVenda { 
    codigo?: number;
    vendedor?: number;
    data?: Date;
    diaSemana?: number;
    clientes?: Array<SismouraWebViewModelsPedidosRotaVendaCliente>;
}
