/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityFiscalNFServicoRetorno { 
    id?: string;
    item?: number;
    codigoProduto?: number;
    descricaoProduto?: string;
    quantidade?: number;
    valorUnitario?: number;
    valorDesconto?: number;
    valorDescontoPorcentagem?: number;
    valorSubTotal?: number;
    valorOutros?: number;
    valorTotal?: number;
    cfop?: string;
    stPis?: string;
    aliquotaPis?: number;
    basePis?: number;
    valorPis?: number;
    stCofins?: string;
    aliquotaCofins?: number;
    baseCofins?: number;
    valorCofins?: number;
    listaServico?: string;
    aliquotaISSQN?: number;
    baseISSQN?: number;
    valorISSQN?: number;
    exigibilidadeISS?: number;
    incentivoFiscal?: number;
}
