/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SismouraWebViewVendaCartaoMobile { 
    codigoCartao?: number;
    isTef?: boolean;
    nsuHost?: string;
    nsuSitef?: string;
    modalidadePagamento?: string;
    codModalidadePagamento?: string;
    valorAprovado?: number;
    viaCliente?: string;
    viaEstabelecimento?: string;
    data?: string;
    operadora?: string;
    bandeira?: string;
    codAutorizacao?: string;
    parcelas?: string;
}
