/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityConsoleContatoParceiroRetorno { 
    nomeCompleto?: string;
    cargo?: string;
    telefone?: string;
    celular?: string;
    email?: string;
    skype?: string;
    cep?: string;
    endereco?: string;
    numero?: string;
    estado?: string;
    complemento?: string;
    cidade?: string;
    razaoSocial?: string;
    nomeFantasia?: string;
    website?: string;
    tipoParceria?: string;
    comoSoubeParceria?: string;
}
