/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityCidade { 
    codigo?: number;
    cidade?: string;
    estado?: string;
    _DDD?: string;
    codigoCidadeIBGE?: number;
    codigoUFIBGE?: number;
    codigoPais?: number;
    nomePais?: string;
    regiao?: number;
    codigoSIAFI?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
