/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SismouraWebViewModelsPedidosPessoaPedido { 
    codigo?: number;
    codigoTemporarioLocal?: number;
    bairro?: string;
    cep?: string;
    cidade?: number;
    complemento?: string;
    endereco?: string;
    nome?: string;
    nomeFantasia?: string;
    listaPadrao?: number;
    bloquearVendaOrcamento?: boolean;
    contato?: string;
    obs?: string;
    email?: string;
    transmitido?: string;
    dDD1?: string;
    dDD2?: string;
    foneNumero?: string;
    fone2Numero?: string;
    numero?: string;
    enderecoNome?: string;
    CPFCNPJ?: string;
    tipo?: string;
    RG?: string;
    vendedor?: number;
    apelido?: string;
    cidadeNome?: string;
}
