/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityConsoleForcaVendaCampo { 
    codigo?: number;
    codigoForcaVenda?: number;
    campo?: string;
    codigoTela?: SiSMouraCoreEntityConsoleForcaVendaCampo.CodigoTelaEnum;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
export namespace SiSMouraCoreEntityConsoleForcaVendaCampo {
    export type CodigoTelaEnum = 1 | 2;
    export const CodigoTelaEnum = {
        NUMBER_1: 1 as CodigoTelaEnum,
        NUMBER_2: 2 as CodigoTelaEnum
    };
}
