/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityPetAppAnimalRetorno { 
    codigo?: number;
    nome?: string;
    codigoEspecie?: number;
    codigoRaca?: number;
    sexo?: string;
    dataNascimento?: Date;
    microchip?: string;
    castrado?: boolean;
    inativo?: boolean;
    observacao?: string;
}
