/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityPetAppUsuarioRetorno { 
    codigo?: number;
    nome?: string;
    bearerLogin?: string;
    codigoCidade?: number;
    enderecoFormatado?: string;
    endereco?: string;
    numeroEndereco?: string;
    cidadeNome?: string;
    cidadeEstado?: string;
    senha?: string;
    bairro?: string;
    celular?: string;
    cep?: string;
    complementoEndereco?: string;
    cpf?: string;
    dataNascimento?: Date;
    email?: string;
    telefone?: string;
}
