/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SismouraWebViewModelsPedidosRotaVendaCliente { 
    rota?: number;
    cliente?: number;
    ordem?: number;
    observacao?: string;
    distancia?: string;
    visitado?: boolean;
    dataHora?: Date;
    observacaoVisita?: string;
    latitudeVisita?: number;
    longitudeVisita?: number;
    latitudeDestino?: number;
    longitudeDestino?: number;
}
