/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityChequeSituacao } from './siSMouraCoreEntityChequeSituacao';


export interface SiSMouraCoreEntityCheques { 
    codigo?: number;
    cliente?: number;
    nomeCliente?: string;
    enderecoCliente?: string;
    foneCliente?: string;
    dataCadastro?: Date;
    venda?: number;
    banco?: number;
    cheque?: number;
    vencimento?: Date;
    valorCheque?: number;
    observacao?: string;
    dias?: number;
    cpf?: string;
    pessoa?: string;
    situacaoAtual?: number;
    dataSituacaoAtual?: Date;
    baixaData?: Date;
    situacaoCc?: string;
    contasPagar?: number;
    codigoTroca?: number;
    codEnviado?: number;
    enviado?: string;
    tipoCheque?: string;
    origem?: string;
    codigoRecebimento?: number;
    vendedor?: number;
    agencia?: string;
    conta?: string;
    codEmpresa?: number;
    dataPagamentoComissao?: Date;
    naoGerarLancamento?: boolean;
    configuracaoLancamento?: number;
    chequeSituacoes?: Array<SiSMouraCoreEntityChequeSituacao>;
    contaContabilLancamento?: number;
    dataDeposito?: Date;
    dataLancamento?: Date;
    contaCorrenteDeposito?: string;
    situacaoAnterior?: number;
    tipoLancamentoBaixaCheque?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
