/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityCidade } from './siSMouraCoreEntityCidade';
import { SiSMouraCoreEntityEmpresaIeOutrosEstados } from './siSMouraCoreEntityEmpresaIeOutrosEstados';


export interface SiSMouraCoreEntityEmpresa { 
    codigo?: number;
    razaoSocial?: string;
    fantasia?: string;
    inativo?: boolean;
    cnpj?: string;
    ie?: string;
    endereco?: string;
    bairro?: string;
    cidade?: number;
    cidadeEntity?: SiSMouraCoreEntityCidade;
    cep?: string;
    fone?: string;
    fax?: string;
    logotipo?: string;
    iss?: number;
    pis?: number;
    cofins?: number;
    ir?: number;
    csl?: number;
    simples?: number;
    diaIss?: number;
    diaPis?: number;
    diaCofins?: number;
    diaIr?: number;
    diaCsl?: number;
    diaSimples?: number;
    regTrib?: number;
    funruralAliquota?: number;
    funruralMensagem?: string;
    readonly regTribIMendes?: number;
    codAtividade?: number;
    jucesp?: number;
    dataJucesp?: Date;
    licencas?: number;
    dataVenda?: Date;
    contrato?: string;
    emailFiscal?: string;
    dataCadastroEcf?: Date;
    croCadastroEcf?: number;
    numero?: number;
    contato?: string;
    inscricaoCadastroContribuinte?: string;
    inscricaoMunicipal?: string;
    padrao?: boolean;
    icmsNf?: boolean;
    multilojaIp?: string;
    multilojaBanco?: string;
    multilojaSenha?: string;
    nomeContabilista?: string;
    cpfContabilista?: string;
    crcContabilista?: string;
    cnpjEscritorioContabilista?: string;
    cepContabilista?: string;
    enderecoContabilista?: string;
    numeroEnderecoContabilista?: string;
    complementoEnderecoContabilista?: string;
    bairroContabilista?: string;
    foneContabilista?: string;
    faxContabilista?: string;
    emailContabilista?: string;
    cidadeContabilista?: number;
    numeroSuframa?: string;
    tipoAtividade?: number;
    fkEmpresaFiscalSerieNf?: number;
    tipoEmpresa?: number;
    codigoFolhamatic?: string;
    codigoCliente?: number;
    slogan?: string;
    decretoPadrao?: number;
    caminhoMultilojaXml?: string;
    nOrdem?: number;
    dataJunta?: Date;
    empresaContador?: string;
    registroJunta?: string;
    ramoAtividade?: string;
    descontoIssqn?: number;
    regimeIncidencia?: number;
    retencaoIss?: boolean;
    issMaiorQue?: number;
    nfeMsgLogotipo?: string;
    apuracaoPisCofins?: number;
    spedPisCofinsUtilizar?: boolean;
    timeoutConexao?: number;
    loginNfp?: string;
    senhaNfp?: string;
    tipoNfp?: number;
    licencaSanitaria?: string;
    complemento?: string;
    covisaConferidoEstoque?: boolean;
    tipo?: string;
    qtdeMaquinas?: string;
    codigoFornecedor?: number;
    siteEmpresa?: string;
    codigointernoedi?: string;
    dataFechamentoAtual?: Date;
    cpfTransmissorSngpc?: string;
    dataCarga?: Date;
    franquiaPerfilCadastro?: number;
    criterioApuracaoPisCofins?: number;
    exibirCockPit?: boolean;
    empresaMatriz?: number;
    usuarioAT?: string;
    senhaAt?: string;
    capitalSocial?: number;
    pais?: number;
    dadosProcon?: string;
    urlFoto?: string;
    iEOutrosEstados?: Array<SiSMouraCoreEntityEmpresaIeOutrosEstados>;
    integracaoSuperOn?: boolean;
    listaPrecoAPP?: number;
    petzSigla?: string;
    emailContato?: string;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
