/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityFiscalRegraImposto { 
    codigo?: number;
    contador?: number;
    tipoRegraImposto?: number;
    iva?: number;
    precoMedioAntigo?: number;
    qtdeEmbalagem?: number;
    ufOrigem?: string;
    ufDestino?: string;
    baseIcms?: number;
    aliquotaInternaICMS?: number;
    aliquotaFCP?: number;
    aliquotaIcms?: number;
    baseIcmsSt?: number;
    aliquotaIcmsSt?: number;
    calcularStIva?: boolean;
    cst?: string;
    csosn?: string;
    taxaTributaria?: number;
    decreto?: number;
    modalidadeSt?: number;
    cfop?: string;
    classeIpi?: string;
    codigoEnquadramentoIpi?: string;
    codigoSeloControle?: string;
    qtdeSeloControle?: string;
    tipoCalculoIpi?: string;
    aliquotaIpi?: number;
    valorUnidadeIpi?: number;
    stPis?: number;
    tipoCalculoPis?: string;
    aliquotaPisP?: number;
    aliquotaPisR?: number;
    stCofins?: number;
    tipoCalculoCofins?: string;
    aliquotaCofinsP?: number;
    aliquotaCofinsR?: number;
    tributacaoIssqn?: string;
    ipiZerado?: boolean;
    stPisEntrada?: number;
    stCofinsEntrada?: number;
    darSt?: number;
    basePis?: number;
    baseCofins?: number;
    grupoFiscalCliente?: number;
    basePisEntrada?: number;
    baseCofinsEntrada?: number;
    aliquotaPisEntrada?: number;
    aliquotaCofinsEntrada?: number;
    cstEntrada?: string;
    cfopEntrada?: string;
    cFOPEntradaDevolucao?: string;
    csosnEntrada?: string;
    codSuframa?: string;
    stIpi?: string;
    sempreCalcularIpi?: string;
    tipoCalculoIpiSaida?: string;
    aliquotaIpiSaida?: number;
    valorUnidadeIpiSaida?: number;
    stIpiSaida?: string;
    aliquotaIssqn?: number;
    exigibilidadeIss?: number;
    codServicoIss?: string;
    incentivoFiscalIss?: number;
    cfopServico?: string;
    codigoEnquadramentoIpiLegal?: string;
    dataCarga?: Date;
    aliquotaFCPST?: number;
    iSSRetido?: boolean;
    iPIDevolvidoBaseICMS?: boolean;
    naturezaReceitaIsentaPISCOFINS?: number;
    isIMendes?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
