/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SismouraWebViewGerarNFRequisicaoItens } from './sismouraWebViewGerarNFRequisicaoItens';


export interface SismouraWebViewGerarNFRequisicao { 
    tipo?: SismouraWebViewGerarNFRequisicao.TipoEnum;
    codPdv?: number;
    serie?: number;
    data?: Date;
    deposito?: number;
    codCliente?: number;
    cpfCliente?: string;
    valorProdutos?: number;
    valorDesconto?: number;
    valorAcrescimo?: number;
    valorTotal?: number;
    itens?: Array<SismouraWebViewGerarNFRequisicaoItens>;
    isContigencia?: boolean;
    ambienteEnvio?: SismouraWebViewGerarNFRequisicao.AmbienteEnvioEnum;
    modalidadeFrete?: SismouraWebViewGerarNFRequisicao.ModalidadeFreteEnum;
    idToken?: string;
    token?: string;
}
export namespace SismouraWebViewGerarNFRequisicao {
    export type TipoEnum = 1 | 2;
    export const TipoEnum = {
        NUMBER_1: 1 as TipoEnum,
        NUMBER_2: 2 as TipoEnum
    };
    export type AmbienteEnvioEnum = 1 | 2;
    export const AmbienteEnvioEnum = {
        NUMBER_1: 1 as AmbienteEnvioEnum,
        NUMBER_2: 2 as AmbienteEnvioEnum
    };
    export type ModalidadeFreteEnum = 0 | 1 | 2 | 9;
    export const ModalidadeFreteEnum = {
        NUMBER_0: 0 as ModalidadeFreteEnum,
        NUMBER_1: 1 as ModalidadeFreteEnum,
        NUMBER_2: 2 as ModalidadeFreteEnum,
        NUMBER_9: 9 as ModalidadeFreteEnum
    };
}
