/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityFiscalNfProdutoDiAdicao } from './siSMouraCoreEntityFiscalNfProdutoDiAdicao';


export interface SiSMouraCoreEntityFiscalNfProdutoDi { 
    codigo?: number;
    produto?: number;
    numeroDi?: string;
    dataRegistro?: Date;
    codigoExportador?: string;
    uf?: string;
    local?: string;
    dataAduaneiro?: Date;
    codigoNf?: number;
    fiscalNFProdutoDIAdicao?: Array<SiSMouraCoreEntityFiscalNfProdutoDiAdicao>;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
