/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SismouraWebViewModelsPedidosProdutoPreco } from './sismouraWebViewModelsPedidosProdutoPreco';


export interface SismouraWebViewModelsPedidosProduto { 
    codigo?: number;
    codigoBarra?: string;
    grupo?: number;
    nome?: string;
    estoque?: number;
    quantidadeEmbalagem?: number;
    referencia?: string;
    precoProduto?: number;
    descontoMaximo?: number;
    estoqueAtual?: number;
    unidade?: string;
    caminhoFoto?: string;
    dataUltimaCompra?: Date;
    quantidadeUltimaCompra?: number;
    fornecedores?: string;
    novo?: boolean;
    precos?: Array<SismouraWebViewModelsPedidosProdutoPreco>;
}
