/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityPostoBombaAbastecimento { 
    codigo?: number;
    bomba?: number;
    combustivel?: number;
    data?: Date;
    litros?: number;
    valor?: number;
    venda?: boolean;
    valorUnitario?: number;
    erro?: boolean;
    programar?: string;
    vender?: string;
    encerranteqtde?: number;
    encerrantevalor?: number;
    bico?: number;
    bombalogica?: number;
    usado?: boolean;
    erroAutomacao?: boolean;
    codigoVenda?: number;
    vendedor?: number;
    assinaturaDigitalRegistro?: string;
    tanque?: number;
    numeroSerieEcf?: string;
    coo?: number;
    notaFiscal?: number;
    impresso?: string;
    encerranteqtdeinicial?: number;
    microAbertura?: string;
    dataAbertura?: string;
    usuarioAbertura?: number;
    empresa?: number;
    codigoabastecimentomemoria?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
