/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityFiscalNfPagamento { 
    nf?: number;
    linha?: number;
    parcela?: string;
    vencimento?: Date;
    documento?: string;
    valor?: number;
    id?: number;
    origem?: string;
    documentoMercantil?: number;
    contaContabil?: number;
    contaCorrente?: string;
    codFormaPagamentoXML?: number;
    codIndPagamentoXML?: number;
    docBancario?: number;
    cpf?: string;
    banco?: number;
    agencia?: number;
    cheque?: number;
    cliente?: number;
    nomeTitular?: string;
    dDDTitular?: string;
    foneTitular?: string;
    enderecoTitular?: string;
    formaPagamento?: number;
    troco?: number;
    tipo?: string;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
