/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityVendaTefDiscado { 
    venda?: number;
    empresa?: number;
    coo?: string;
    autorizacao?: string;
    nsu?: string;
    dataTransacao?: Date;
    operadora?: string;
    bandeira?: string;
    valorTransacao?: number;
    qtdeParcelas?: number;
    id?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
