/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SismouraWebViewMaiControllerSqlParametro { 
    nome?: string;
    valor?: any;
    tipo?: SismouraWebViewMaiControllerSqlParametro.TipoEnum;
}
export namespace SismouraWebViewMaiControllerSqlParametro {
    export type TipoEnum = 0 | 1 | 2 | 3 | 4 | 5 | 6 | 7 | 8 | 9 | 10 | 11 | 12 | 13 | 14 | 15 | 16 | 17 | 18 | 19 | 20 | 21 | 22 | 23 | 25 | 29 | 30 | 31 | 32 | 33 | 34;
    export const TipoEnum = {
        NUMBER_0: 0 as TipoEnum,
        NUMBER_1: 1 as TipoEnum,
        NUMBER_2: 2 as TipoEnum,
        NUMBER_3: 3 as TipoEnum,
        NUMBER_4: 4 as TipoEnum,
        NUMBER_5: 5 as TipoEnum,
        NUMBER_6: 6 as TipoEnum,
        NUMBER_7: 7 as TipoEnum,
        NUMBER_8: 8 as TipoEnum,
        NUMBER_9: 9 as TipoEnum,
        NUMBER_10: 10 as TipoEnum,
        NUMBER_11: 11 as TipoEnum,
        NUMBER_12: 12 as TipoEnum,
        NUMBER_13: 13 as TipoEnum,
        NUMBER_14: 14 as TipoEnum,
        NUMBER_15: 15 as TipoEnum,
        NUMBER_16: 16 as TipoEnum,
        NUMBER_17: 17 as TipoEnum,
        NUMBER_18: 18 as TipoEnum,
        NUMBER_19: 19 as TipoEnum,
        NUMBER_20: 20 as TipoEnum,
        NUMBER_21: 21 as TipoEnum,
        NUMBER_22: 22 as TipoEnum,
        NUMBER_23: 23 as TipoEnum,
        NUMBER_25: 25 as TipoEnum,
        NUMBER_29: 29 as TipoEnum,
        NUMBER_30: 30 as TipoEnum,
        NUMBER_31: 31 as TipoEnum,
        NUMBER_32: 32 as TipoEnum,
        NUMBER_33: 33 as TipoEnum,
        NUMBER_34: 34 as TipoEnum
    };
}
