/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityServicoPetListaPrecosApiRetorno } from './siSMouraCoreEntityServicoPetListaPrecosApiRetorno';


export interface SiSMouraCoreEntityServicoPetApiRetorno { 
    codigo?: number;
    nome?: string;
    valor?: number;
    fixo?: boolean;
    duracao?: string;
    informacoes?: string;
    subgrupoCodigo?: number;
    subgrupoNome?: string;
    precos?: Array<SiSMouraCoreEntityServicoPetListaPrecosApiRetorno>;
}
