/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityConsoleForcaVendaDispositivo { 
    codigo?: number;
    dataInclusao?: Date;
    cliente?: number;
    descricao?: string;
    iDDispositivo?: string;
    dispositivo?: string;
    tipo?: number;
    status?: number;
    empresaDispositivo?: number;
    deposito?: number;
    casasDecimaisValor?: number;
    casasDecimaisQtde?: number;
    descontoUtilizado?: number;
    venderSemEstoque?: boolean;
    venderClientesDevedores?: boolean;
    excederDesconto?: boolean;
    gravarSemForma?: boolean;
    isHomologacao?: boolean;
    readonly isHabilitado?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
