/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreCommonProcuraCampo } from './siSMouraCoreCommonProcuraCampo';
import { SiSMouraWebControlsProcuraPaiDadosColuna } from './siSMouraWebControlsProcuraPaiDadosColuna';


export interface SiSMouraWebControlsProcuraPai { 
    mensagemNaoEncontrou?: string;
    readonly campoID?: string;
    readonly campoDescricao?: string;
    readonly urlCadastro?: string;
    readonly exibirInformacoesAdicionais?: boolean;
    readonly usarComboEmpresa?: boolean;
    readonly exibirCheckBoxInativo?: boolean;
    readonly camposProcura?: Array<SiSMouraCoreCommonProcuraCampo>;
    colunasProcura?: Array<SiSMouraWebControlsProcuraPaiDadosColuna>;
    nome?: string;
}
