/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityAnimaisCadastroApiRetorno } from './siSMouraCoreEntityAnimaisCadastroApiRetorno';
import { SiSMouraCoreEntityAnimaisVeterinarioApiRetorno } from './siSMouraCoreEntityAnimaisVeterinarioApiRetorno';
import { SiSMouraCoreEntityEmpresasApiRetorno } from './siSMouraCoreEntityEmpresasApiRetorno';
import { SismouraWebViewPetMouraAplicativoModelRetornoServico } from './sismouraWebViewPetMouraAplicativoModelRetornoServico';


export interface SismouraWebViewPetMouraAplicativoModelRetornoAtendimento { 
    codigo?: number;
    animal?: SiSMouraCoreEntityAnimaisCadastroApiRetorno;
    data?: Date;
    hora?: Date;
    empresa?: SiSMouraCoreEntityEmpresasApiRetorno;
    profissional?: SiSMouraCoreEntityAnimaisVeterinarioApiRetorno;
    cuidados?: string;
    servicos?: Array<SismouraWebViewPetMouraAplicativoModelRetornoServico>;
    quantidadeReagendamentos?: number;
    readonly duracaoTotalAtendimento?: string;
}
