/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityExactSalesCamposPersonalizadoExact } from './siSMouraCoreEntityExactSalesCamposPersonalizadoExact';
import { SiSMouraCoreEntityExactSalesContatoExact } from './siSMouraCoreEntityExactSalesContatoExact';
import { SiSMouraCoreEntityExactSalesDoreExact } from './siSMouraCoreEntityExactSalesDoreExact';
import { SiSMouraCoreEntityExactSalesEnderecoExact } from './siSMouraCoreEntityExactSalesEnderecoExact';
import { SiSMouraCoreEntityExactSalesEtapaExact } from './siSMouraCoreEntityExactSalesEtapaExact';
import { SiSMouraCoreEntityExactSalesMercadoExact } from './siSMouraCoreEntityExactSalesMercadoExact';
import { SiSMouraCoreEntityExactSalesOrigemExact } from './siSMouraCoreEntityExactSalesOrigemExact';
import { SiSMouraCoreEntityExactSalesPreVendedorExact } from './siSMouraCoreEntityExactSalesPreVendedorExact';
import { SiSMouraCoreEntityExactSalesProdutoExact } from './siSMouraCoreEntityExactSalesProdutoExact';
import { SiSMouraCoreEntityExactSalesSubOrigemExact } from './siSMouraCoreEntityExactSalesSubOrigemExact';
import { SiSMouraCoreEntityExactSalesVendedorExact } from './siSMouraCoreEntityExactSalesVendedorExact';


export interface SiSMouraCoreEntityExactSalesLeadExact { 
    id?: number;
    empresa?: string;
    dtCadastro?: Date;
    dtAtualizacao?: Date;
    contatos?: Array<SiSMouraCoreEntityExactSalesContatoExact>;
    mercado?: SiSMouraCoreEntityExactSalesMercadoExact;
    origem?: SiSMouraCoreEntityExactSalesOrigemExact;
    subOrigem?: SiSMouraCoreEntityExactSalesSubOrigemExact;
    preVendedor?: SiSMouraCoreEntityExactSalesPreVendedorExact;
    vendedor?: SiSMouraCoreEntityExactSalesVendedorExact;
    linkMkt?: string;
    telEmpresa?: string;
    site?: string;
    produtoLead?: string;
    endereco?: SiSMouraCoreEntityExactSalesEnderecoExact;
    obs?: string;
    etapa?: string;
    dores?: Array<SiSMouraCoreEntityExactSalesDoreExact>;
    produtos?: Array<SiSMouraCoreEntityExactSalesProdutoExact>;
    camposPersonalizados?: Array<SiSMouraCoreEntityExactSalesCamposPersonalizadoExact>;
    motivoDescarte?: string;
    etapas?: Array<SiSMouraCoreEntityExactSalesEtapaExact>;
}
