/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SismouraWebViewModelsPedidosOrcamentoChequesPedido { 
    codigo?: number;
    orcamento?: number;
    dataCadastro?: Date;
    valor?: number;
    vencimento?: Date;
    CPF?: string;
    tipoPessoa?: string;
    banco?: string;
    agencia?: string;
    conta?: string;
    cheque?: string;
    cliente?: number;
    clienteNome?: string;
    clienteFone?: string;
    clienteEndereco?: string;
}
