/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityProdutoMobileRetorno { 
    codigo?: number;
    codigoBarra?: string;
    nome?: string;
    precoCusto?: number;
    precoProduto?: number;
    unidade?: string;
    taxaTributaria?: number;
    cfop?: string;
    ncm?: string;
    codigoANP?: string;
    codigoCEST?: string;
    combustivel?: boolean;
    inativo?: boolean;
    grupoCodigo?: number;
    grupoDescricao?: string;
    subGrupoCodigo?: number;
    subGrupoDescricao?: string;
}
