/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityExactSalesVendedorExact } from './siSMouraCoreEntityExactSalesVendedorExact';


export interface SiSMouraCoreEntityExactSalesAgendamentoExact { 
    boxId?: number;
    boxIdAnterior?: number;
    dtInicio?: Date;
    dtFim?: Date;
    vendedor?: SiSMouraCoreEntityExactSalesVendedorExact;
    tipoReuniao?: string;
    referencia?: string;
    linkFeedback?: string;
}
