/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityCursoUsuario } from './siSMouraCoreEntityCursoUsuario';
import { SiSMouraCoreEntityRhFuncionarioHorario } from './siSMouraCoreEntityRhFuncionarioHorario';
import { SiSMouraCoreEntityUsuarioEmpresa } from './siSMouraCoreEntityUsuarioEmpresa';
import { SiSMouraCoreEntityUsuarioGrupo } from './siSMouraCoreEntityUsuarioGrupo';
import { SiSMouraCoreEntityUsuarioZonavenda } from './siSMouraCoreEntityUsuarioZonavenda';


export interface SiSMouraCoreEntityUsuario { 
    codigo?: number;
    nome?: string;
    abreviacao?: string;
    senha?: string;
    endereco?: string;
    cidade?: number;
    cep?: string;
    fone?: string;
    nivel?: string;
    dtNasc?: Date;
    dtAdmissao?: Date;
    comissaoVenda?: number;
    demitido?: boolean;
    horaEntrada1?: string;
    horaSaida1?: string;
    horaEntrada2?: string;
    horaSaida2?: string;
    celular?: string;
    estadoCivil?: string;
    cpf?: string;
    rg?: string;
    dataEmissao?: Date;
    orgaoExp?: string;
    carteiraHabilitacao?: string;
    qtdePasseDia?: number;
    horasTrabalhar?: string;
    bairro?: string;
    codigoBarra?: string;
    salarioEncript?: string;
    observacao?: string;
    vendedor?: boolean;
    bloquearFinalizarVenda?: boolean;
    dataCadastro?: Date;
    situacao?: string;
    numeroResidencia?: string;
    dataNascimento?: Date;
    naturalidade?: number;
    ctps?: string;
    serieCtps?: string;
    emissaoCtps?: Date;
    pis?: string;
    emissaoPis?: Date;
    tituloEleitor?: string;
    zona?: string;
    secao?: string;
    reservista?: string;
    dataAdmissao?: Date;
    funcao?: number;
    contratoExperienciaDe?: Date;
    contratoExperienciaAte?: Date;
    nomeMae?: string;
    dataNascMae?: Date;
    contaCorrente?: string;
    agencia?: string;
    banco?: string;
    nomeBanco?: string;
    email?: string;
    empresa?: number;
    nomeConjugue?: string;
    filho?: boolean;
    roteadorPuxou?: boolean;
    dataDemissao?: Date;
    valorPasse?: number;
    sexo?: number;
    farmaceutico?: boolean;
    socio?: boolean;
    autonomo?: boolean;
    perfilAdministrativo?: boolean;
    complemento?: string;
    depositoPadrao?: number;
    _UF_CTPS?: string;
    cNHCategoria?: string;
    cNHOrgao?: number;
    cNHValidade?: Date;
    deficiencia?: number;
    racaCor?: number;
    folhaFicha?: string;
    departamento?: number;
    setor?: number;
    usuarioSecao?: number;
    empresasUsuario?: Array<SiSMouraCoreEntityUsuarioEmpresa>;
    gruposUsuario?: Array<SiSMouraCoreEntityUsuarioGrupo>;
    zonasVenda?: Array<SiSMouraCoreEntityUsuarioZonavenda>;
    cursos?: Array<SiSMouraCoreEntityCursoUsuario>;
    exMedico?: Date;
    diasProrrogacao?: number;
    terminoContribuicaoProrrogacao?: Date;
    tipoTributacaoSindical?: number;
    sindicato?: number;
    codigoAdmissao?: number;
    formacaoAcademica?: string;
    grauInstrucao?: number;
    vinculoEmpregatico?: number;
    tipoContaBancaria?: number;
    hrsSemanais?: string;
    hrsMensais?: string;
    tipoContrato?: number;
    formaPagamento?: number;
    trabalhadorCategoria?: string;
    grauRisco?: number;
    dataSenha?: Date;
    dataCarga?: Date;
    empresaContratual?: number;
    usuarioTodasEmpresas?: boolean;
    usuarioWindows?: string;
    contador?: boolean;
    entregador?: boolean;
    rhFuncionarioHorario?: Array<SiSMouraCoreEntityRhFuncionarioHorario>;
    franqueador?: boolean;
    franqueado?: boolean;
    freelancer?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
