/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityEmpresaMobileRetorno { 
    codigo?: number;
    razaoSocial?: string;
    fantasia?: string;
    cnpj?: string;
    ie?: string;
    endereco?: string;
    bairro?: string;
    cidade?: string;
    telefone?: string;
    numero?: string;
}
