/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityFiscalNFChaveReferenciaRetorno } from './siSMouraCoreEntityFiscalNFChaveReferenciaRetorno';
import { SiSMouraCoreEntityFiscalNFPagamentoRetorno } from './siSMouraCoreEntityFiscalNFPagamentoRetorno';
import { SiSMouraCoreEntityFiscalNFProdutoRetorno } from './siSMouraCoreEntityFiscalNFProdutoRetorno';
import { SiSMouraCoreEntityFiscalNFServicoRetorno } from './siSMouraCoreEntityFiscalNFServicoRetorno';
import { SiSMouraCoreEntityFiscalNfChaveReferencia } from './siSMouraCoreEntityFiscalNfChaveReferencia';
import { SiSMouraCoreEntityFiscalNfPagamento } from './siSMouraCoreEntityFiscalNfPagamento';
import { SiSMouraCoreEntityFiscalNfProduto } from './siSMouraCoreEntityFiscalNfProduto';
import { SiSMouraCoreEntityFiscalNfProdutoDi } from './siSMouraCoreEntityFiscalNfProdutoDi';
import { SiSMouraCoreEntityFiscalNfProdutoIi } from './siSMouraCoreEntityFiscalNfProdutoIi';
import { SiSMouraCoreEntityFiscalNfServico } from './siSMouraCoreEntityFiscalNfServico';
import { SiSMouraCoreEntityFiscalNfVenda } from './siSMouraCoreEntityFiscalNfVenda';
import { SiSMouraCoreEntityFiscalNfce } from './siSMouraCoreEntityFiscalNfce';
import { SiSMouraCoreEntityFiscalNfe } from './siSMouraCoreEntityFiscalNfe';


export interface SiSMouraCoreEntityFiscalNf { 
    codigo?: number;
    formulario?: number;
    empresa?: number;
    _E_S?: string;
    natureza?: number;
    substTribut?: string;
    nome?: string;
    cpfCgc?: string;
    endereco?: string;
    bairro?: string;
    cep?: string;
    municipio?: string;
    uf?: string;
    ie?: string;
    dataEmissao?: Date;
    hora?: Date;
    dataEs?: Date;
    horaSaida?: Date;
    baseIcms?: number;
    valorIcms?: number;
    frete?: number;
    seguro?: number;
    totalNf?: number;
    codigoTransportadora?: number;
    transportadora?: string;
    conta?: number;
    placa?: string;
    ufPlaca?: string;
    cpfCgcTransp?: string;
    enderecoTransp?: string;
    municipioTransp?: string;
    ufTransp?: string;
    ieTransp?: string;
    qtdeTransp?: number;
    especie?: string;
    marca?: string;
    numero?: string;
    pesoBruto?: number;
    pesoLiquido?: number;
    dadosAdicionais?: string;
    dataRecebimento?: Date;
    cancelada?: boolean;
    codigoCliente?: number;
    venda?: number;
    valorF1?: number;
    vencimentoF1?: Date;
    valorF2?: number;
    vencimentoF2?: Date;
    valorF3?: number;
    vencimentoF3?: Date;
    dataCancelado?: Date;
    valorF4?: number;
    vencimentoF4?: Date;
    cfop?: string;
    mensagem?: string;
    cfop2?: string;
    totalServicos?: number;
    totalIss?: number;
    creditoIcms?: boolean;
    vendedor?: number;
    pedidoCliente?: string;
    comprador?: string;
    enderecoEntrega?: string;
    enderecoCobranca?: string;
    redespacho?: string;
    receber?: string;
    estoque?: number;
    desconto?: number;
    valorDesconto?: number;
    devolvida?: string;
    tipo?: string;
    tiponf?: string;
    qtde?: number;
    tipoNf?: number;
    impressao?: string;
    valorIss?: number;
    valorTotalServicos?: number;
    cupomFiscal?: string;
    modeloNf?: number;
    tipoNota?: string;
    codigoFornecedor?: number;
    serie?: number;
    centroCusto?: number;
    artigoSimples?: string;
    descricaoCf?: string;
    tara?: number;
    dadosAdicionaisNfe?: string;
    dadosAdicionaisFiscoNfe?: string;
    naturezaOperacaoNfe?: string;
    codigoSaida?: number;
    deposito?: number;
    rntc?: string;
    nfReferenciada?: number;
    darSt?: number;
    modelo?: number;
    xmlNfe?: string;
    enderecoNumero?: string;
    enderecoComplemento?: string;
    ufEmbarque?: string;
    localEmbarque?: string;
    foneNumero?: string;
    foneDdd?: string;
    fone?: string;
    faturaNFe?: string;
    dadosAdicionaisManuais?: string;
    mensagemIbpt?: string;
    chaveNfReferenciada?: string;
    consumidorFinal?: string;
    tipoOperacao?: number;
    fiscalNFProdutos?: Array<SiSMouraCoreEntityFiscalNfProduto>;
    fiscalNFServicos?: Array<SiSMouraCoreEntityFiscalNfServico>;
    fiscalNFPagamentos?: Array<SiSMouraCoreEntityFiscalNfPagamento>;
    nFe?: Array<SiSMouraCoreEntityFiscalNfe>;
    nFCe?: SiSMouraCoreEntityFiscalNfce;
    fiscalNFVendas?: Array<SiSMouraCoreEntityFiscalNfVenda>;
    ficalNFChavesImportadas?: Array<SiSMouraCoreEntityFiscalNfChaveReferencia>;
    fiscalNFProdutoDI?: Array<SiSMouraCoreEntityFiscalNfProdutoDi>;
    fiscalNFProdutoII?: Array<SiSMouraCoreEntityFiscalNfProdutoIi>;
    produtosRetorno?: Array<SiSMouraCoreEntityFiscalNFProdutoRetorno>;
    faturaRetorno?: Array<SiSMouraCoreEntityFiscalNFPagamentoRetorno>;
    servicosRetorno?: Array<SiSMouraCoreEntityFiscalNFServicoRetorno>;
    chavesReferenciadas?: Array<SiSMouraCoreEntityFiscalNFChaveReferenciaRetorno>;
    vendasImportadas?: string;
    configuracaoLancamento?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
