/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityUsuarioLoginRetorno { 
    codigo?: number;
    nome?: string;
    abreviacao?: string;
    usuarioWindows?: string;
    demitido?: boolean;
    contador?: boolean;
    franqueador?: boolean;
    franqueado?: boolean;
    freelancer?: boolean;
    readonly isMoura?: boolean;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
