/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraWebControlsProcuraPaiDadosColuna { 
    dataField?: string;
    captionColuna?: string;
    tamanhoColuna?: number;
    tipoColuna?: SiSMouraWebControlsProcuraPaiDadosColuna.TipoColunaEnum;
    casasDecimais?: number;
}
export namespace SiSMouraWebControlsProcuraPaiDadosColuna {
    export type TipoColunaEnum = 0 | 1 | 2 | 3 | 4;
    export const TipoColunaEnum = {
        NUMBER_0: 0 as TipoColunaEnum,
        NUMBER_1: 1 as TipoColunaEnum,
        NUMBER_2: 2 as TipoColunaEnum,
        NUMBER_3: 3 as TipoColunaEnum,
        NUMBER_4: 4 as TipoColunaEnum
    };
}
