/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SiSMouraCoreEntityFiscalNfProdutoAnilha } from './siSMouraCoreEntityFiscalNfProdutoAnilha';


export interface SiSMouraCoreEntityFiscalNfProduto { 
    nf?: number;
    produto?: number;
    embalagem?: number;
    quantidade?: number;
    unitario?: number;
    total?: number;
    descricao?: string;
    icms?: number;
    unidade?: string;
    situacaoTributaria?: string;
    classificacaoFiscal?: string;
    ipi?: number;
    valorIpi?: number;
    observacao?: string;
    qtdeAnt?: number;
    valorAnt?: number;
    valorIcms?: number;
    codif?: string;
    cfop?: string;
    inseridoManualmente?: boolean;
    desconto?: number;
    lote?: string;
    fabricacao?: Date;
    validade?: Date;
    precoMaximo?: number;
    baseIcmsSt?: number;
    valorIcmsSt?: number;
    iva?: number;
    icmsSt?: number;
    baseIcms?: number;
    porcBaseIcms?: number;
    codigoBarra?: string;
    aliquotaPis?: number;
    valorPis?: number;
    aliquotaCofins?: number;
    valorCofins?: number;
    baseSt060?: number;
    icmsSt060?: number;
    item?: number;
    stPis?: number;
    stCofins?: number;
    darSt?: number;
    darStValor?: number;
    valorOutros?: number;
    basePis?: number;
    baseCofins?: number;
    pedidoCompraNumero?: string;
    pedidoCompraItem?: number;
    codigo?: number;
    stIpi?: string;
    valorFrete?: number;
    porcentagemCreditoSn?: number;
    valorCreditoSn?: number;
    ncm?: string;
    valorTotalTributado?: number;
    aliquotaFCP?: number;
    valorFCP?: number;
    aliquotaFCPST?: number;
    valorFCPST?: number;
    percentualIPIDevolvido?: number;
    valorIPIDevolvido?: number;
    produtoAnilhas?: Array<SiSMouraCoreEntityFiscalNfProdutoAnilha>;
    cest?: string;
    motivoDesoneracaoICMS?: number;
    vlrICMSDesonerado?: number;
    codigoBeneficioFiscal?: string;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
