/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityConsoleClienteSiteRetorno { 
    nome?: string;
    descritivo?: string;
    urlLogo?: string;
    urlSite?: string;
    urlFacebook?: string;
    urlTwitter?: string;
    urlInstagram?: string;
    destaqueInicial?: boolean;
    prioridade?: number;
    segmento?: string;
    segmentoInt?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
