/**
 * Sismoura.Web.View
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


export interface SiSMouraCoreEntityVendaItem { 
    id?: number;
    venda?: number;
    item?: number;
    produto?: number;
    quantidade?: number;
    valorUnitario?: number;
    valorTotal?: number;
    valorCusto?: number;
    comissao?: number;
    cancelado?: boolean;
    desconto?: number;
    bomba?: number;
    atendimento?: number;
    vendedor?: number;
    observacao?: string;
    bico?: number;
    listaPreco?: number;
    valorVenda?: number;
    fator?: number;
    precoDesconto?: number;
    encerranteqtde?: number;
    encerrantevalor?: number;
    finalizarAtendimento?: boolean;
    taxaTributaria?: number;
    fator2?: number;
    fator3?: number;
    deposito?: number;
    comanda?: string;
    lote?: string;
    pagoComissao?: boolean;
    dataComissaoPaga?: Date;
    pontosProduto?: number;
    qtdePrescrita?: number;
    qtdeSolicitada?: number;
    codigoFornecedor?: number;
    codigoAbastecimento?: number;
    acrescimo?: number;
    precoProdutoNormal?: number;
    promocao?: boolean;
    farmaciaReceita?: number;
    truncarTotal?: number;
    tipoComissao?: string;
    comissaoValor?: number;
    numeroCartaoPresente?: number;
    clienteCartaoPresente?: number;
    observacaoCartaoPresente?: string;
    kit?: boolean;
    brinde?: boolean;
    iVAPorcentagem?: number;
    iVAValor?: number;
    volume?: number;
    undConversaoValor?: number;
    undConversaoQtde?: number;
    undConversaoUnidade?: string;
    indicacaoOrigemIndicado?: number;
    quantidadeEntregue?: number;
    preencheuClasse?: boolean;
    isInativo?: boolean;
    ignorarDuplicidade?: boolean;
}
