declare class C_OrcAte extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Orcamento_Atendimento> {
    readonly grdServicos: MouraGridViewJSEditavel;
    Servico: any;
    Servicos: any[];
    Produto: any;
    Produtos: any[];
    readonly txtServico: MouraTextBoxProcura;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtQuantidade: MouraTextBox;
    readonly txtValorUnitario: MouraTextBox;
    readonly txtDesconto: MouraTextBox;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtProprietarioNome: MouraTextBox;
    readonly txtAnimalNome: MouraTextBox;
    readonly lblValorTotal: MouraLabel;
    readonly grdProdutos: MouraGridViewJSEditavel;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtQuantidadeProduto: MouraTextBox;
    readonly txtValorUnitarioProduto: MouraTextBox;
    readonly txtDescontoProduto: MouraTextBox;
    readonly lblTotalProduto: MouraLabel;
    readonly txtData: MouraTextBoxData;
    readonly lblCadastrado: MouraLabel;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboModelo: MouraComboBox;
    readonly btnImprimir: MouraButton;
    readonly chkCobrado: MouraCheckBox;
    readonly cboListaPreco: MouraComboBox;
    readonly txtCPF: MouraTextBoxCPF;
    readonly txtE_Mail: MouraTextBox;
    readonly txtFone_DDD1: MouraTextBoxTelefone;
    readonly lstTipo: MouraRadioButtonList;
    readonly lblValorTotalOrcamento: MouraLabel;
    protected Init(): void;
    protected OnComboBoxEmpresaChange(): void;
    protected PreencherGridDocumentos(empresa: string): void;
    protected OnCboListaPrecoGotFocus(s: any, e: any): void;
    protected MudouTipo(newValue: any, oldValue: any): void;
    OnPageLoad(): void;
    protected OnValidandoItemServico(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnValidandoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnCodigoProcurou(): void;
    calcularTotalServico(): void;
    calcularTotalProduto(): void;
    protected OnCboListaPreco_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    private listaPrecos;
    protected OnTxtServicoProcurou(s: MouraControl, e: MouraEventArgs): void;
    protected OnTxtProdutoProcurou(s: MouraControl, e: MouraEventArgs): void;
    protected OnTxtPetProcurouProrprietario(s: MouraControl, e: MouraEventArgs): void;
    protected OnTxtPetProcurouAnimal(s: MouraControl, e: MouraEventArgs): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Orcamento_Atendimento): void;
    protected LimparServico(): void;
    protected LimparProduto(): void;
    protected OnAntesGravar(): boolean;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Animais_Orcamento_Atendimento): void;
    private PreencherGrades;
    private OnAdicionouDoOrcamento;
    protected OnAlterarOrcamento(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected AtualizaLabelOrcamento(): void;
    private OnExcluiuDoOrcamento;
    private AtualizandoLabelOrcamento;
}
declare var c_OrcAte: C_OrcAte;
//# sourceMappingURL=C_OrcAte.d.ts.map