declare class C_ConParam extends MouraPage {
    readonly txtConta_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDestinoZeramento_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDebIRPJ_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaCredIRPJ_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDebCSLL_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaCredCSLL_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaLucro_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaPrejuizo_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaSintetica_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaGrupo_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaOrigem_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDestino_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDestinoZeramento: MouraTextBoxProcuraContabil;
    readonly cboEmpresa: MouraComboBox;
    readonly txtContaSintetica: MouraTextBoxProcuraContabil;
    readonly txtContaDebIRPJ: MouraTextBoxProcuraContabil;
    readonly txtContaCredIRPJ: MouraTextBoxProcuraContabil;
    readonly txtContaDebCSLL: MouraTextBoxProcuraContabil;
    readonly txtContaCredCSLL: MouraTextBoxProcuraContabil;
    readonly txtContaLucro: MouraTextBoxProcuraContabil;
    readonly txtContaPrejuizo: MouraTextBoxProcuraContabil;
    readonly txtContaGrupo: MouraTextBoxProcuraContabil;
    readonly txtConta: MouraTextBoxProcuraContabil;
    readonly txtContaOrigem: MouraTextBoxProcuraContabil;
    readonly txtContaDestino: MouraTextBoxProcuraContabil;
    protected Init(): void;
    protected OnContaAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaSinteticaAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaSinteticaPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): boolean;
    protected OnContaGrupoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaPrejuizoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaLucroAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaCredCSLLAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebCSLLAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaCredIRPJAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebIRPJAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDestinoZeramentoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilOrigemAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilDestinoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    PreencherEmpresaContabil(): void;
    protected OnContaDebIRPJPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaCredIRPJPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaDebCSLLPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaLucroPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaPrejuizoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaGrupoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaCredCSLLPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaDestinoZeramentoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaContabilOrigemPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaContabilDestinoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
}
declare var c_ConParam: C_ConParam;
//# sourceMappingURL=C_ConParam.d.ts.map