declare class C_ConLan extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Contabil_Configuracao_Lancamento> {
    readonly txtContaDebito_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaCredito_hdnEmpresaContabil: HTMLInputElement;
    readonly cboEmpresa: MouraComboBox;
    readonly txtTipoLancamento: MouraTextBoxProcura;
    readonly txtContaCredito: MouraTextBoxProcuraContabil;
    readonly txtContaDebito: MouraTextBoxProcuraContabil;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtDescricao: MouraTextBox;
    readonly cboTipo: MouraComboBox;
    readonly chkDesconsiderarLancamento: MouraCheckBox;
    readonly lblMsgLanc: MouraLabel;
    readonly btnTipos: MouraButton;
    readonly cboGrupo: MouraComboBox;
    readonly cnkLancamentoMultiplo: MouraCheckBox;
    readonly hdnItem: HTMLInputElement;
    readonly lblCredito: MouraLabel;
    readonly lblDebito: MouraLabel;
    readonly grdTiposCadastrados: MouraGridViewJS;
    readonly grdItem: MouraGridViewJSEditavel;
    readonly txtHistoricoPadrao: MouraTextBoxProcura;
    readonly mdConfiguracoes: MouraModal;
    Parametros: SiSMoura.Core.Entity.ContabilConfiguracaoLancamentoParametroRetorno[];
    protected Init(): void;
    OnPageLoad(): void;
    protected OnClickExcluirCampos(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickBotaoLinhaItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoLimpar(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnClickBotaoGravar(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): boolean;
    protected OnAntesGravar(): boolean;
    PreencherEmpresaContabil(): void;
    protected OnClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickTipos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnGrupoChanged(): void;
    protected PreencherItemPorGrupo(): void;
    protected PreencherConfiguracoesCadastradas(): void;
    protected OnTipoChanged(): void;
    protected validarTipo(): void;
    protected PreencherComboGrupo(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Contabil_Configuracao_Lancamento): boolean;
    protected LimparCampoItens(): void;
    protected PreencherGradeItens(): void;
    protected LabelMensagemLancamentos(): void;
    protected VerificarCamposNota(): void;
    protected OnProcurouContaContabilCredito(): void;
    protected OnAbriuProcuraContaContabilCredito(): void;
    protected OnContaContabilCreditoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilCreditoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnTipoLancamentoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnTipoLancamentoPesquisando(): void;
    protected OnProcurouTipoLancamento(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraKeyPressEventArgs): void;
    protected OnProcurouContaContabilDebito(): void;
    protected OnAbriuProcuraContaContabilDebito(): void;
    protected OnContaContabilDebitoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilDebitoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
}
declare var c_ConLan: C_ConLan;
//# sourceMappingURL=C_ConLan.d.ts.map