declare class C_ParamCon extends MouraPageAngular {
    readonly txtConta_hdnEmpresaContabil: HTMLInputElement;
    readonly txtConsolidacaoContaContabil_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDestinoZeramento_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDebIRPJ_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaCredIRPJ_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDebCSLL_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaCredCSLL_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaLucro_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaPrejuizo_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaSintetica_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaGrupo_hdnEmpresaContabil: HTMLInputElement;
    readonly hdnContaSintetica: HTMLInputElement;
    readonly txtContaOrigem_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDestino_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaHistorico_hdnEmpresaContabil: HTMLInputElement;
    readonly AbaEcf: MouraTabPage;
    readonly AbaApuracao: MouraTabPage;
    readonly txtContaDestinoZeramento: MouraTextBoxProcuraContabil;
    readonly txtHistoricoZeramento: MouraTextBoxProcura;
    readonly accGrupo: MouraAccordion;
    readonly cboEmpresa: MouraComboBox;
    readonly cboEmpresaOrigem: MouraComboBox;
    readonly lstEmpresaDestino: MouraListBoxEmpresa;
    readonly txtContaSintetica: MouraTextBoxProcuraContabil;
    readonly chkAtivarModulo: MouraCheckBox;
    readonly txtContaDebIRPJ: MouraTextBoxProcuraContabil;
    readonly txtContaCredIRPJ: MouraTextBoxProcuraContabil;
    readonly txtContaDebCSLL: MouraTextBoxProcuraContabil;
    readonly txtContaCredCSLL: MouraTextBoxProcuraContabil;
    readonly txtContaLucro: MouraTextBoxProcuraContabil;
    readonly txtContaPrejuizo: MouraTextBoxProcuraContabil;
    readonly txtHistoricoTransferencia: MouraTextBoxProcura;
    readonly txtHistoricoIRPJ: MouraTextBoxProcura;
    readonly txtHistoricoCSLL: MouraTextBoxProcura;
    readonly txtDiarioLivro: MouraTextBox;
    readonly txtDiarioPagina: MouraTextBox;
    readonly txtDiarioQtdePaginas: MouraTextBox;
    readonly txtContaGrupo: MouraTextBoxProcuraContabil;
    readonly txtConta: MouraTextBoxProcuraContabil;
    readonly btnGerar: MouraButton;
    readonly btnExcluir: MouraButton;
    readonly btnAdicionar: MouraButton;
    readonly btnGravar: MouraButton;
    readonly btnLimpar: MouraButton;
    readonly btnMarcarReplica: MouraButton;
    readonly btnDesmarcarReplica: MouraButton;
    readonly btnAdicionarGrupo: MouraButton;
    readonly chkPlanoReferencialSped: MouraCheckBox;
    readonly chkFechamentoCaixa: MouraCheckBox;
    readonly chkTransfere: MouraCheckBox;
    readonly chkLivroCaixa: MouraCheckBox;
    readonly chkGrupo: MouraCheckBox;
    readonly chkPlanoConta: MouraCheckBox;
    readonly chkLancamentoContabil: MouraCheckBox;
    readonly chkCartao: MouraCheckBox;
    readonly chkContaCorrente: MouraCheckBox;
    readonly chkConfiguracaoContabil: MouraCheckBox;
    readonly chkParametros: MouraCheckBox;
    readonly chkImpostoVenda: MouraCheckBox;
    readonly chkTransferencia: MouraCheckBox;
    readonly GridContas: MouraGridViewJS;
    readonly cboIntegracaoCartao: MouraComboBox;
    readonly cboIntegracaoNotaEntrada: MouraComboBox;
    readonly txtGrupo: MouraTextBox;
    readonly txtDescricao: MouraTextBox;
    readonly GridGrupo: MouraGridViewJS;
    readonly cboOperacao: MouraComboBox;
    readonly txtContaOrigem: MouraTextBoxProcuraContabil;
    readonly txtContaDestino: MouraTextBoxProcuraContabil;
    readonly GridTransferencia: MouraGridViewJS;
    readonly txtHistorico: MouraTextBoxProcura;
    readonly cboParametro: MouraComboBox;
    readonly btnAdicionarTransferencia: MouraButton;
    readonly lblExecoes: MouraLabel;
    readonly txtConsolidacaoContaContabil: MouraTextBoxProcuraContabil;
    readonly GridConsolidacao: MouraGridViewJSEditavel;
    Consolidacoes: SiSMoura.Core.Entity.Contabil_Consolidacao_ExcecaoRetorno[];
    ContasLivroCaixa: SiSMoura.Core.Entity.Contabil_Parametros_Ecf_ContasRetorno[];
    LivroCaixa: SiSMoura.Core.Entity.Contabil_Parametros_Ecf_ContasRetorno;
    readonly txtContaLivroCaixa: MouraTextBoxProcuraContabil;
    readonly cboSituacaoEspecial: MouraComboBox;
    readonly txtDataSitEsp: MouraTextBoxData;
    readonly txtCnpjScp: MouraTextBoxCPF;
    readonly cboTipoEcf: MouraComboBox;
    readonly cboFormaTributacao: MouraComboBox;
    readonly cboEscrituracao: MouraComboBox;
    readonly cboTipoPessoaImune: MouraComboBox;
    readonly cboApuracaoIrpjImune: MouraComboBox;
    readonly cboApuracaoCSllImune: MouraComboBox;
    readonly cboCriterioReconhecimento: MouraComboBox;
    readonly cboApuIrpjCsll: MouraComboBox;
    readonly txtApuracaoEstimativa: MouraTextBox;
    readonly btnAdicionarLivroCx: MouraButton;
    readonly grdContasEcf: MouraGridViewJS;
    readonly cboInicioPeriodo: MouraComboBox;
    readonly cboTipoEscri: MouraComboBox;
    readonly txtNumeroRecibo: MouraTextBox;
    readonly cboOptanteRefis: MouraComboBox;
    readonly cboOptantePaes: MouraComboBox;
    readonly cboPessoaJuridica: MouraComboBox;
    readonly txtCodNaturezaJuridica: MouraTextBox;
    readonly cboAliquota: MouraComboBox;
    readonly txtQuantidadeCsp: MouraTextBox;
    readonly cboAdministradora: MouraComboBox;
    readonly cboParticipacoes: MouraComboBox;
    readonly cboOperacoesExterior: MouraComboBox;
    readonly cboOperacoesPessoa: MouraComboBox;
    readonly cboEnquadrada: MouraComboBox;
    readonly cboAtvRural: MouraComboBox;
    readonly cboLucroExplora: MouraComboBox;
    readonly cboIsencaoResumido: MouraComboBox;
    readonly cboIndicativoFinor: MouraComboBox;
    readonly cboDoacoes: MouraComboBox;
    readonly cboEquivalencia: MouraComboBox;
    readonly cboExportadora: MouraComboBox;
    readonly cboRecebimentoExt: MouraComboBox;
    readonly cboAtivoExterior: MouraComboBox;
    readonly cboComercialExpor: MouraComboBox;
    readonly cboPagExt: MouraComboBox;
    readonly cboComerEletro: MouraComboBox;
    readonly cboRoyalties: MouraComboBox;
    readonly cboRoyaltiesBenef: MouraComboBox;
    readonly cboRendimentosRelativos: MouraComboBox;
    readonly cboPagRemessa: MouraComboBox;
    readonly cboInovacao: MouraComboBox;
    readonly cboCapacitacao: MouraComboBox;
    readonly cboPjHabilitada: MouraComboBox;
    readonly cboPoloIndus: MouraComboBox;
    readonly cboZonaProcess: MouraComboBox;
    readonly cboLivreComercio: MouraComboBox;
    readonly cboIntegrante: MouraComboBox;
    readonly cboDeclaracao: MouraComboBox;
    readonly cboParticipacoesExt: MouraComboBox;
    readonly txtFormaTributacao1: MouraTextBox;
    readonly txtFormaTributacao2: MouraTextBox;
    readonly txtFormaTributacao3: MouraTextBox;
    readonly txtFormaTributacao4: MouraTextBox;
    readonly txtJan: MouraTextBox;
    readonly txtFev: MouraTextBox;
    readonly txtMar: MouraTextBox;
    readonly txtAbr: MouraTextBox;
    readonly txtMai: MouraTextBox;
    readonly txtJun: MouraTextBox;
    readonly txtJul: MouraTextBox;
    readonly txtAgo: MouraTextBox;
    readonly txtSet: MouraTextBox;
    readonly txtOut: MouraTextBox;
    readonly txtNov: MouraTextBox;
    readonly txtDez: MouraTextBox;
    readonly txtHistoricoApu: MouraTextBoxProcura;
    protected Init(): void;
    protected DigitouDestinoLancamento(): void;
    protected OnExcluirItemGrade(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    OnCboEmpresaOrigemChange(): void;
    protected OnClicouBotaoLinhaConta(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClicouBotaoContaCaixa(s: any, e: MouraGridViewJSItemEventArgs): void;
    protected OnClicouBotaoLinhaGrupo(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClicouBotaoLinhaTransferencia(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAtivarCheckChanged(): void;
    protected OnIntegracaoChanged(): void;
    protected OnFormaTributacaoChanged(): void;
    protected OnSituacaoEspecialChanged(): void;
    protected OnTipoEcfChaneged(): void;
    protected OnApuracaoIrplCsllChanged(): void;
    protected OnTransfereCheckChanged(): void;
    VerificaCheckTransfere(): void;
    protected PreencherTela(empresa: number): void;
    protected OnAbriuProcuraContabilConsolidacao(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnPesquisandoContabil(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnProcurouContaContabilConsolidacao(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnValidandoItemConsolidacao(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected PreencherAbaEcf(empresa: number): void;
    protected PreencherAbaApuracao(empresa: number): void;
    protected PreencherCamposEcf(ecf: string): void;
    protected PreencherAbaTransferencia(empresa: number): void;
    protected PreencherIntegracaoNotaEntrada(): void;
    protected OnClickLimparCampos(): void;
    protected LimparCampos(): void;
    protected LimparCamposTransferencia(): void;
    OnPageLoad(): void;
    protected OnClickMarcar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickDesmarcar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected MarcarDesmarcar(checked: boolean): void;
    protected PreencherGradeContas(): void;
    protected PreencherGradeGrupos(): void;
    protected PreencherGradeTransferencia(): void;
    protected PreencherGradeLivroCaixa(): void;
    protected PreencherGradeConsolidacao(): void;
    protected OnClickGravar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickExcluir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAdicionar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAdicionarGrupo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAdicionarTransferencia(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnAdicionarLivroCx(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickGerar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnContaAntesAbrirProcuraLivroCaixa(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaPesquisandoLivroCaixa(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaAntesAbrirProcura(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnProcurouContaLivroCaixa(s: MouraTextBoxProcuraContabil, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaSinteticaAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaSinteticaPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): boolean;
    protected OnContaGrupoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaOrigemAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDestinoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaPrejuizoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaLucroAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaCredCSLLAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebCSLLAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaCredIRPJAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDebIRPJAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaDestinoZeramentoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    OnCboEmpresaChange(): void;
    PreencherEmpresaContabil(): void;
    protected ValidaAbaEcf(): void;
    protected OnContaDebIRPJPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaCredIRPJPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaDebCSLLPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaLucroPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaPrejuizoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaGrupoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaOrigemPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaDestinoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnDigitouTributacaoPeriodo(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraPesquisandoEventArgs): void;
    protected OnDigitouTributacaoMensal(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraPesquisandoEventArgs): void;
    protected OnContaCredCSLLPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaDestinoZeramentoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
}
declare var c_ParamCon: C_ParamCon;
//# sourceMappingURL=C_ParamCon.d.ts.map