declare class C_PlCoPa extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Contabil_Configuracao_Pagamento> {
    readonly txtContaContabil_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaDebitoCartao_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaContabilSobra_hdnEmpresaContabil: HTMLInputElement;
    readonly txtContaContabilQuebra_hdnEmpresaContabil: HTMLInputElement;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboFormaPagamento: MouraComboBox;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtCartao: MouraTextBoxProcura;
    readonly txtHistorico: MouraTextBoxProcura;
    readonly txtContaContabil: MouraTextBoxProcuraContabil;
    readonly txtContaContabilSobra: MouraTextBoxProcuraContabil;
    readonly txtContaContabilQuebra: MouraTextBoxProcuraContabil;
    readonly txtContaDebito: MouraTextBoxProcuraContabil;
    readonly txtContaDebitoCartao: MouraTextBoxProcuraContabil;
    readonly chkLanMultiplo: MouraCheckBox;
    readonly txtHistorico_: MouraTextBoxProcuraContabil;
    readonly txtHistoricoSobra: MouraTextBoxProcuraContabil;
    readonly txtHistoricoQuebra: MouraTextBoxProcuraContabil;
    readonly Tab: MouraTabPanel;
    readonly lblCartoes: MouraLabel;
    readonly Grid: MouraGridViewJS;
    readonly GridVenda: MouraGridViewJSEditavel;
    Cartoes: SiSMoura.Core.Entity.ContabilFechamentoCaixaCartao[];
    Cartao: SiSMoura.Core.Entity.ContabilFechamentoCaixaCartao;
    protected Init(): void;
    protected OnClickBotaoLinhaCartao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Contabil_Configuracao_Pagamento): void;
    protected OnDepoisPesquisar(s: any, e: MouraDepoisPesquisarEventArgs): void;
    PreencherGradeVenda(): void;
    protected PreencherDiferencaCaixa(): void;
    protected OnDepoisClickNovo(): boolean;
    protected LimparCampos(): void;
    protected LimparCamposEmpresa(): void;
    protected cboEmpresaSelectedItemChanged(): void;
    OnPageLoad(): void;
    protected HabilitarCampos(flag: boolean): void;
    protected PreencherFormaPagamento(): void;
    protected GetCadastrados(empresa: any): void;
    protected OnDepoisGravar(): boolean;
    protected OnAntesGravar(): boolean;
    protected OnClickBotaoLimpar(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnClickBotaoGravar(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected VerificarCadastro(): void;
    protected MostrarGrupoTaxaOperadora(flag: boolean): void;
    protected OnContaContabilDebitoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaContabilDebitoCartaoPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    PreencherEmpresaContabil(): void;
    protected OnContaDebitoCartaoAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaContabilSobraAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilQuebraAntesAbrirProcura(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnContaContabilQuebraPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
    protected OnContaContabilSobraPesquisando(s: MouraTextBoxProcura, ev: MouraTextBoxProcuraContabilPesquisandoEventArgs): void;
}
declare var c_PlCoPa: C_PlCoPa;
//# sourceMappingURL=C_PlCoPa.d.ts.map