declare class C_CupDesc extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Food_Cupom_Desconto> {
    readonly grdProduto: MouraGridViewJSEditavel;
    Produto: any;
    Produtos: any[];
    Combo: any;
    Combos: any[];
    Lanche: any;
    Lanches: any[];
    readonly grdProdutoValorDiferenciado: MouraGridViewJSEditavel;
    ProdutoValorDiferenciado: any;
    ProdutosValorDiferenciado: any[];
    readonly grdCupom: MouraGridViewJSEditavel;
    Cupom: any;
    Cupons: any[];
    readonly cboTipo: MouraComboBox;
    readonly cboTipoIngredienteDobro: MouraComboBox;
    readonly txtPrecoValorDiferenciado: MouraTextBox;
    readonly txtPrecoLanche: MouraTextBox;
    readonly txtPrecoCombo: MouraTextBox;
    readonly txtPorcentagem: MouraTextBox;
    readonly txtProdutoValorDiferenciado: MouraTextBoxProcura;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtLanche: MouraTextBoxProcura;
    readonly txtCombo: MouraTextBoxProcura;
    readonly btnCarregarQR: MouraButton;
    readonly QR: MouraQRCode;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly DivGanhaLanche: HTMLDivElement;
    readonly DivGanhaCombo: HTMLDivElement;
    readonly DivIngredienteDobro: HTMLDivElement;
    readonly DivDescontoFinal: HTMLDivElement;
    readonly DivGanhaIngrediente: HTMLDivElement;
    readonly DivQRCode: HTMLDivElement;
    readonly DivIngredienteValorDiferenciado: HTMLDivElement;
    readonly tab: MouraTabPanel;
    readonly lblPrecoCombo: MouraLabel;
    readonly lblPrecoLanche: MouraLabel;
    readonly lblPrecoProduto: MouraLabel;
    readonly lblPrecoProdutoValorDiferenciado: MouraLabel;
    readonly grdLanche: MouraGridViewJSEditavel;
    readonly grdCombo: MouraGridViewJSEditavel;
    readonly fotoFundoCupomDesconto: MouraImgUploadJs;
    readonly grdTipo: MouraGridViewJSEditavel;
    IngredienteDobro: any;
    IngredientesDobro: any[];
    private codigos;
    protected Init(): void;
    protected OnPrecoLanche(): void;
    protected OnPrecoProdutoProdutoValorDiferenciado(): void;
    protected OnPrecoCombo(): void;
    protected OnPrecoProduto(): void;
    OnPageLoad(): void;
    protected CamposInvisiveis(): void;
    protected OnAntesGravar(): boolean;
    protected MudouTipo(newValue: any, oldValue: any): void;
    protected OnDepoisGravar(): boolean;
    protected PreencherGrade(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Food_Cupom_Desconto): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Food_Cupom_Desconto): void;
    protected OnGrdSelecionouCupom(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickIncluirIngredienteDobro(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirProduto(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirLanche(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirCombo(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirProdutoValorDiferenciado(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected LimparCampos(): void;
    protected PreencherEmpresas(empresas: SiSMoura.Core.Entity.Food_Cupom_Desconto_Empresa[]): void;
    protected OnClickCarregarQR(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected ValidarCampos(): boolean;
}
declare var c_CupDesc: C_CupDesc;
//# sourceMappingURL=C_CupDesc.d.ts.map