declare class C_FoodPromo extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Food_Promocao> {
    readonly grdProduto: MouraGridViewJSEditavel;
    Produto: any;
    Produtos: any[];
    readonly grdTipo: MouraGridViewJSEditavel;
    Tipo: any;
    Tipos: any[];
    readonly grdProdutoRetorno: MouraGridViewJSEditavel;
    ProdutoRetorno: any;
    ProdutosRetorno: any[];
    readonly grdProdutoPrecoDiferenciado: MouraGridViewJSEditavel;
    ProdutoPrecoDiferenciado: any;
    ProdutosPrecoDiferenciado: any[];
    readonly grdTipoRetorno: MouraGridViewJSEditavel;
    TipoRetorno: any;
    TiposRetorno: any[];
    readonly grdPromocao: MouraGridViewJSEditavel;
    Promocao: any;
    Promocoes: any[];
    readonly ImgUploadInformativo: MouraImgUploadJs;
    readonly ImgUploadRetorno: MouraImgUploadJs;
    readonly cboRequisito: MouraComboBox;
    readonly cboRetorno: MouraComboBox;
    readonly txtQuantidade: MouraTextBox;
    readonly txtPreco: MouraTextBox;
    readonly txtPorcentagem: MouraTextBox;
    readonly txtProdutoRetorno: MouraTextBoxProcura;
    readonly txtAlturaBotaoRetornoPromocao: MouraTextBox;
    readonly txtLarguraBotaoRetornoPromocao: MouraTextBox;
    readonly txtProdutoPrecoDiferenciado: MouraTextBoxProcura;
    readonly txtProdutoSelecionouItem: MouraTextBoxProcura;
    readonly cboTipo: MouraComboBox;
    readonly cboTipoRetorno: MouraComboBox;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly lstDiaSemana: MouraListBoxEmpresa;
    readonly cboTipoEscolha: MouraComboBox;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtValorMinimoPedido: MouraTextBox;
    readonly txtValorMinimoItem: MouraTextBox;
    readonly txtValorMinimoPedidoTipo: MouraTextBox;
    readonly DivAtingirValor: HTMLDivElement;
    readonly DivSelecionouItem: HTMLDivElement;
    readonly DivSelecionouTipo: HTMLDivElement;
    readonly DivGanhaItem: HTMLDivElement;
    readonly DivDescontoPedido: HTMLDivElement;
    readonly DivPrecoDiferenciado: HTMLDivElement;
    readonly DivSelecionouTipoRetorno: HTMLDivElement;
    private codigos;
    private codigosDiaSemana;
    protected Init(): void;
    OnPageLoad(): void;
    protected CamposInvisiveis(): void;
    protected OnAntesGravar(): boolean;
    protected MudouRequisito(newValue: any, oldValue: any): void;
    protected MudouRetorno(newValue: any, oldValue: any): void;
    protected OnDepoisGravar(): boolean;
    protected PreencherGrade(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Food_Promocao): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Food_Promocao): void;
    protected OnGrdSelecionouPromocao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected ValidarCampos(): boolean;
    protected OnClickIncluirProdutoRequisito(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirProdutoRetorno(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirProdutoPrecoDiferenciado(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirTipoRequisito(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirTipoRetorno(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected LimparCamposRequisito(): void;
    protected LimparCamposRetorno(): void;
    protected PreencherEmpresas(empresas: SiSMoura.Core.Entity.Food_Promocao_Empresa[]): void;
    protected PreencherDiasSemna(diasSemana: SiSMoura.Core.Entity.Food_Promocao_Dia_Semana[]): void;
}
declare var c_FoodPromo: C_FoodPromo;
//# sourceMappingURL=C_FoodPromo.d.ts.map