declare class C_Tela extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Food_Tela> {
    readonly grdTela: MouraGridViewJSEditavel;
    readonly grdIngredientes: MouraGridViewJSEditavel;
    readonly grdCombo: MouraGridViewJSEditavel;
    readonly grdAcompanhamentos: MouraGridViewJSEditavel;
    readonly txtMinima: MouraTextBox;
    readonly txtMaxima: MouraTextBox;
    readonly txtLinhas: MouraTextBox;
    readonly txtColunas: MouraTextBox;
    readonly txtMargemTopoMenu: MouraTextBox;
    readonly txtZoomTeclado: MouraTextBox;
    readonly txtProdutoIngrediente: MouraTextBoxProcura;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtLinhaIngrediente: MouraTextBox;
    readonly txtColunaIngrediente: MouraTextBox;
    readonly txtProdutoAcompanhamento: MouraTextBoxProcura;
    readonly txtLarguraBotaoRodape: MouraTextBoxProcura;
    readonly txtLinhaAcompanhamento: MouraTextBox;
    readonly txtColunaAcompanhamento: MouraTextBox;
    Telas: any[];
    readonly lblFoto: MouraLabel;
    readonly cboTipo: MouraComboBox;
    readonly cboTipoInformativo: MouraComboBox;
    readonly tab: MouraTabPanel;
    Ingrediente: any;
    Ingredientes: any[];
    Combo: any;
    Combos: any[];
    Acompanhamento: any;
    Acompanhamentos: any[];
    readonly fotoTela: MouraImgUploadJs;
    readonly CorFundo: MouraColorEdit;
    readonly CorTextoSenha: MouraColorEdit;
    readonly CorTitulo: MouraColorEdit;
    readonly CorProdutoModalAdicionais: MouraColorEdit;
    readonly CorTituloModalAdicionais: MouraColorEdit;
    readonly CorTotal: MouraColorEdit;
    readonly CorSubtitulo1ModalAdicionais: MouraColorEdit;
    readonly CorSubtitulo2ModalAdicionais: MouraColorEdit;
    readonly CorPrecoModalAdicionais: MouraColorEdit;
    readonly CorDescricaoRodape: MouraColorEdit;
    readonly CorBordaBotaoRodape: MouraColorEdit;
    readonly txtTamanhoFonteRodape: MouraTextBox;
    readonly CorSelecaoRodape: MouraColorEdit;
    readonly CorFundoBotaoRodape: MouraColorEdit;
    readonly CorBordaCampo: MouraColorEdit;
    readonly CorLinhaImpar: MouraColorEdit;
    readonly CorLinhaPar: MouraColorEdit;
    readonly CorNomeProduto: MouraColorEdit;
    readonly CorPrecoProduto: MouraColorEdit;
    readonly chkExibirBotao: MouraCheckBox;
    readonly chkProximaTela: MouraCheckBox;
    readonly chkExibirBotaoAgora: MouraCheckBox;
    readonly chkExibirBotaoViagem: MouraCheckBox;
    readonly chkExibirBotaoOk: MouraCheckBox;
    readonly chkExibirCadastrarPedido: MouraCheckBox;
    readonly txtAlturaImgBotao: MouraTextBox;
    readonly txtLarguraImgBotao: MouraTextBox;
    readonly txtAlturaBotaoModal: MouraTextBox;
    readonly txtLarguraBotaoModal: MouraTextBox;
    readonly txtAlturaTitulo: MouraTextBox;
    readonly txtAlturaBotaoPagamento: MouraTextBox;
    readonly txtLarguraBotaoPagamento: MouraTextBox;
    readonly txtAlturaBotaoMenu: MouraTextBox;
    readonly txtAlturaBotaoMenuLateral: MouraTextBox;
    readonly txtLarguraBotaoMenuLateral: MouraTextBox;
    readonly txtAlturaBotaoModalAdicionais: MouraTextBox;
    readonly txtLarguraBotaoModalAdicionais: MouraTextBox;
    readonly txtAlturaBotaoRodape: MouraTextBox;
    readonly txtLarguraPedido: MouraTextBox;
    readonly txtLarguraImgPedido: MouraTextBox;
    readonly txtAlturaBotaoSenha: MouraTextBox;
    readonly txtLarguraBotaoSenha: MouraTextBox;
    readonly txtFonteNomeProduto: MouraTextBox;
    readonly txtTamFonteSenha: MouraTextBox;
    readonly txtTamanhoFonteTotal: MouraTextBox;
    readonly txtFontePrecoProduto: MouraTextBox;
    readonly txtFonteProdutoModalAdicionais: MouraTextBox;
    readonly txtFonteTituloModalAdicionais: MouraTextBox;
    readonly txtFonteSubtitulo1ModalAdicionais: MouraTextBox;
    readonly txtFonteSubtitulo2ModalAdicionais: MouraTextBox;
    readonly txtFontePrecoModalAdicionais: MouraTextBox;
    readonly txtTextoRodape: MouraTextBox;
    readonly fotoRodape: MouraImgUploadJs;
    readonly fotoBotaoAvancar: MouraImgUploadJs;
    readonly fotoBotaoVoltar: MouraImgUploadJs;
    readonly fotoBotaoEditarPedido: MouraImgUploadJs;
    readonly fotoBotaoAgora: MouraImgUploadJs;
    readonly fotoBotaoViagem: MouraImgUploadJs;
    readonly fotoBotaoOk: MouraImgUploadJs;
    readonly fotoBotaoCadastrarPedido: MouraImgUploadJs;
    readonly fotoBotaoDinheiro: MouraImgUploadJs;
    readonly fotoBotaoCredito: MouraImgUploadJs;
    readonly fotoPedidoEfetuado: MouraImgUploadJs;
    readonly fotoBotaoDebito: MouraImgUploadJs;
    readonly fotoBotaoVale: MouraImgUploadJs;
    readonly fotoBotaoCaixa: MouraImgUploadJs;
    readonly fotoBotaoCupomNumerico: MouraImgUploadJs;
    readonly txtCombo: MouraTextBoxProcura;
    readonly txtLinhaCombo: MouraTextBox;
    readonly txtColunaCombo: MouraTextBox;
    readonly fotoFundoModal: MouraImgUploadJs;
    readonly fotoFundoModalConfirmacao: MouraImgUploadJs;
    readonly fotoFundoModalAdicionais: MouraImgUploadJs;
    readonly imgIngrediente: MouraImgUploadJs;
    readonly imgCombo: MouraImgUploadJs;
    readonly imgAcompanhamento: MouraImgUploadJs;
    readonly imgBuscar: MouraImgUploadJs;
    readonly imgQrCode: MouraImgUploadJs;
    readonly txtTamanhoFonteTitulo: MouraTextBox;
    readonly txtAlturaBotaoVoltar: MouraTextBox;
    readonly txtLarguraBotaoVoltar: MouraTextBox;
    readonly txtAlturaBotaoAvancar: MouraTextBox;
    readonly txtLarguraBotaoAvancar: MouraTextBox;
    protected Init(): void;
    protected OnGrdSelecionouTela(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected ValidarCampos(): boolean;
    protected OnAntesGravar(): boolean;
    protected OnGrdSelecionouTelaIngrediente(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdSelecionouTelaAcompanhamento(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdSelecionouTelaCombo(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    OnPageLoad(): void;
    protected CamposNaoVisiveis(tipo: any): void;
    protected MudouTipo(newValue: any, oldValue: any): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Food_Tela): void;
    protected OnDepoisGravar(): boolean;
    protected PreencherGrade(): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Food_Tela): void;
    protected OnClickIncluirIngrediente(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirAcompanhamento(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnClickIncluirCombo(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected LimparCamposTipo(tipo: any): void;
}
declare var c_Tela: C_Tela;
//# sourceMappingURL=C_Tela.d.ts.map