declare class C_ProdMan extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Produto> {
    private PATH_DOCUMENTOS;
    private STAGE;
    private LAYER;
    Similares: SiSMoura.Core.Entity.ProdutoSimilarRetorno[];
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtPrecoCusto: MouraTextBox;
    readonly lblDataCadastro: MouraLabel;
    readonly lblDataAlteracao: MouraLabel;
    readonly txtMarkup_P: MouraTextBox;
    readonly txtPrecoVenda: MouraTextBox;
    readonly txtPrecoPorcentagem: MouraTextBox;
    readonly hdnCampoAtualizar: HTMLInputElement;
    readonly hdnCalcularMargem: HTMLInputElement;
    readonly mdConfigManequim: MouraModal;
    readonly mdImportarDados: MouraModal;
    readonly txtProdutoImportar: MouraTextBoxProcura;
    readonly txtProdutoSimilar: MouraTextBoxProcura;
    readonly hdnURLConsulta: HTMLInputElement;
    readonly btnHistoricoPreco: MouraButton;
    readonly btnGerarHistoricoPreco: MouraButton;
    readonly cboHistoricoTipo: MouraComboBox;
    readonly cboHistoricoCampoAlterado: MouraComboBox;
    readonly mdHistoricoPreco: MouraModal;
    readonly txtPeriodoHistoricoPreco: MouraTextBoxPeriodo;
    readonly grdHistoricoPreco: MouraGridViewJS;
    readonly btnInativos: MouraButton;
    readonly mdInativosEmpresa: MouraModal;
    readonly txtDescricao: MouraTextBox;
    readonly grdInativosporEmpresas: MouraGridViewJS;
    readonly lblProduto: MouraLabel;
    readonly btnOKInativo: MouraButton;
    readonly GridProdutosSimilares: MouraGridViewJS;
    readonly btnProdutosSimilares: MouraButton;
    readonly mdSimilares: MouraModal;
    readonly btnOkSimilares: MouraButton;
    readonly btnAdicionarSimilar: MouraButton;
    readonly btnConfigManequim: MouraButton;
    readonly btnImportarDados: MouraButton;
    readonly btnImportarProduto: MouraButton;
    readonly btnCancelarImportar: MouraButton;
    readonly txtMarca: MouraTextBoxProcura;
    readonly lblInfFoto: MouraLabel;
    readonly Tab: MouraTabPanel;
    readonly cboPrioridade: MouraComboBox;
    Manequim: any;
    Manequins: any[];
    readonly grdFotos: MouraGridViewJSEditavel;
    readonly btnFotos: MouraButton;
    readonly imgProduto: MouraImgUploadJs;
    readonly cboManequim: MouraComboBox;
    readonly btnAddManequim: MouraButton;
    readonly btnRemoverRoupa: MouraButton;
    readonly txtProvadorCodEcommerce: MouraTextBox;
    readonly btnFecharMdFotos: MouraButton;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnGlobalEndCallback(): void;
    OnSelecionouEmpresa(): void;
    OnSelecionouManequim(): void;
    OnCarregouImagemRoupa(): void;
    DrawRoupa(imgProduto: any, width: number, height: number, rotation: number, left: number, top: number, upload: boolean): void;
    LimparCanvasRoupa(): void;
    protected LimparCanvasManequim(): void;
    OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Produto): void;
    ValidaEmpresaUnico(): boolean;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Produto): void;
    protected LimparManequim(): void;
    protected OnAntesGravar(): boolean;
    protected ValidarAntesGravar(produto: SiSMoura.Core.Entity.Produto): boolean;
    protected ExecutarGravar(): void;
    protected OnDepoisGravar(): boolean;
    protected PreencherFornecedoresEntity(Entity: SiSMoura.Core.Entity.Produto): void;
    protected OnClickHistoricoPreco(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickGerarHistorico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnConfigManequim(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickInativosPorEmpresa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected selecionarCheck(atributoAngular: string, valor: boolean): void;
    protected OnEndCallBackModalImportarDados(): void;
    protected OnTextBoxMarkupChange(): void;
    protected OnTextBoxPrecoCustoChange(): void;
    protected OnTextBoxPrecoVendaChange(): void;
    private AtualizarValoresProduto;
    private AtualizarValorVenda;
    private AtualizarMarkup;
    private AtualizarMargem;
    protected PreencherListaInativos(entity: SiSMoura.Core.Entity.Produto): void;
    protected ProcuraEmpresa(codEmpresa: number, lista: SiSMoura.Core.Entity.Provador_Produto_Empresa[]): SiSMoura.Core.Entity.Provador_Produto_Empresa;
    OnClickBtnAddManequim(): void;
    protected PreencherListaManequins(entity: SiSMoura.Core.Entity.Produto): void;
    protected PreencherGradeManequins(entity: SiSMoura.Core.Entity.Produto): void;
    protected OnGridFotosSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGridFotosExcluiuItem(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnClickBotaoOKInativo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoSimilares(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOKSimilares(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAdicionarSimilar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected PreencherListaSimilares(entity: SiSMoura.Core.Entity.Produto): void;
    protected OnClickBotaoImportarDados(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoCancelarImportarDados(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoImportarProduto(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected OnClickFecharModalFotos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnAlterouProdutoPreco(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected criarEntidadePersonalizados(Entidade: SiSMoura.Core.Entity.Produto): void;
    protected FormatImg(img: any): any;
}
declare var c_ProdMan: C_ProdMan;
declare var Konva: any;
//# sourceMappingURL=C_ProdMan.d.ts.map