declare class C_Animal_Old extends MouraPageCadastro<SiSMoura.Core.Entity.Animais_Atendimento> {
    private listaPrecos;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtServico: MouraTextBoxProcura;
    readonly txtValorUnitario: MouraTextBoxProcura;
    readonly txtQuantidade: MouraTextBox;
    readonly txtDesconto: MouraTextBox;
    readonly txtDescontoPorcent: MouraTextBox;
    readonly txtObservacao: MouraTextBoxProcura;
    readonly lblTotal: MouraTextBox;
    readonly cboListaPreco_comboBox: DevExpress.Web.Scripts.ASPxClientComboBox;
    readonly dlgVacinasAgendadas: MouraModal;
    readonly txtProfissionalAgendamento: MouraTextBoxProcura;
    readonly grdAgendamentos: MouraGridViewJS;
    readonly btnVoltarAgendamento: MouraButton;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly btnPendentes: HTMLSpanElement;
    readonly hdnAgendamentoSelecionado: HTMLInputElement;
    readonly hdnPendentesVisible: HTMLInputElement;
    readonly hdnDoc: HTMLInputElement;
    readonly hdnDocSelecionado: HTMLInputElement;
    readonly btnVacinasSpan: HTMLSpanElement;
    readonly btnVacinas: MouraButton;
    readonly hdnAgendamentoVisible: HTMLInputElement;
    readonly btnDiagnostico: HTMLSpanElement;
    readonly hdnDiagnosticoVisible: HTMLInputElement;
    readonly lblEndereco_TextBox: HTMLInputElement;
    readonly lblComplemento_TextBox: HTMLInputElement;
    readonly lblCidade_TextBox: HTMLInputElement;
    readonly lblFone_TextBox: HTMLInputElement;
    readonly lblSaldoDevedor_TextBox: HTMLInputElement;
    readonly lblCredito_TextBox: HTMLInputElement;
    readonly lblEspecie_TextBox: HTMLInputElement;
    readonly lblRaca_TextBox: HTMLInputElement;
    readonly lblTemperamento_TextBox: HTMLInputElement;
    readonly lblPeso_TextBox: HTMLInputElement;
    readonly lblDataNascimento_TextBox: HTMLInputElement;
    readonly lblIdadeSexo_TextBox: HTMLInputElement;
    readonly lblPelagem_TextBox: HTMLInputElement;
    readonly lblCHIP_TextBox: HTMLInputElement;
    readonly lblRGA_TextBox: HTMLInputElement;
    readonly lblObsServico_TextBox: HTMLInputElement;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly callBackServico: MouraCallBackPanel;
    readonly grdDoc: MouraGridViewJS;
    readonly btnImpDoc: MouraButton;
    readonly btnZanthus: MouraButton;
    readonly lblZanthus: MouraLabel;
    readonly hdnMsgAdicionar: HTMLInputElement;
    readonly hdnServicoPacote: HTMLInputElement;
    AgendamentoSelecionado: SiSMoura.Core.Entity.Animais_Marketing_Servicos;
    protected Init(): void;
    protected OnTxtPetProcurouAnimal(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnSelecionouMSGBoxAgendamento(e: MsgBoxResultEventArgs): void;
    protected OnTxtPetProcurouProprietario(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnCboListaPreco_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnTxtServicoProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnTxtValoresChange(): void;
    protected OnTxtDescontoPorcentChange(): void;
    protected PreencherGridDocumentos(): void;
    protected OnClickImprimirDoc(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoZanthus(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecinouOpcaoZanthus(e: MsgBoxResultEventArgs): void;
    protected VerificaEnabledCampos(): void;
    protected OnAntesAbrirProcura(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnAntesAbrirProcuraProfissionalAgendamento(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnCboListaPrecoGotFocus(s: any, e: any): void;
    protected OnClickBtnVacina(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickbtnVoltarAgendamento(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecionouLinhaAgendamento(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
}
declare var c_Animal_Old: C_Animal_Old;
//# sourceMappingURL=C_Animal_Old.d.ts.map