declare module SiSMoura.Core.Entity {
    interface Animais_Atendimento extends SiSMoura.Core.Common.Entity {
        RetornarOperadorData: () => string;
    }
}
interface ServicoContinuo {
    Codigo: number;
    Atendimento: number;
    Servico: string;
    Data: Date;
}
interface ProdutoContinuo {
    Codigo: number;
    Atendimento: number;
    Produto: string;
    Data: Date;
}
interface ServicoAgenda {
    Codigo: number;
    Hora: string;
}
declare class C_Animal extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Atendimento> {
    private listaPrecos;
    private listaPrecosProduto;
    private horarioAtendimento;
    private dataAtendimento;
    private codigoProfissional;
    private verificouDesconto;
    private selecionouAgendamento;
    private servicosAgenda;
    private codigoEspera;
    private isTelaAgendaConsolidada;
    private lancamentosPrestador;
    private faltaServicoAtendimento;
    private atendimentosContinuos;
    private servicosContinuos;
    private produtosContinuos;
    private mudouDeProfissionalGenerico;
    private mudouProfissionalAposConcluidoPago;
    private mudouDataAposConcluidoPago;
    private mudouConcluidoAposPagoeConcluido;
    private verificadoMudouCampoCritico;
    private nomeCampoAlterado;
    private usuarioAutorizou;
    private valorAnterior;
    private valorNovo;
    private valorProfissional;
    private validarProfissional;
    private PATH_FOTOS;
    readonly PathFoto: string;
    VendaAtendimento: string;
    Servicos: SiSMoura.Core.Entity.ServicosAtendimento[];
    Servico: SiSMoura.Core.Entity.ServicosAtendimento;
    Encaminhamento: SiSMoura.Core.Entity.Animais_Atendimento_Encaminhamento;
    AlteracaoesCamposChave: SiSMoura.Core.Entity.Animais_Alteracoes_Camposchave[];
    AlteracaoCamposChave: SiSMoura.Core.Entity.Animais_Alteracoes_Camposchave;
    Produtos: SiSMoura.Core.Entity.ProdutosAtendimento[];
    Produto: SiSMoura.Core.Entity.ProdutosAtendimento;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtServico: MouraTextBoxProcura;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtValorUnitario: MouraTextBox;
    readonly cboOrigemAcidente: MouraComboBox;
    readonly txtIncidencia: MouraTextBox;
    readonly txtTipoAcidente: MouraTextBoxProcura;
    readonly cboGravidadeAcidente: MouraComboBox;
    readonly txtValorUnitarioProduto: MouraTextBox;
    readonly txtMotivoDesconto: MouraTextBox;
    readonly txtQuantidade: MouraTextBox;
    readonly txtQuantidadeProduto: MouraTextBox;
    readonly txtDesconto: MouraTextBox;
    readonly txtDescontoProduto: MouraTextBox;
    readonly txtDescontoPorcent: MouraTextBox;
    readonly txtMotivoTroca: MouraTextBox;
    readonly txtDescontoPorcentProduto: MouraTextBox;
    readonly lblTotal: MouraLabel;
    readonly lblTotalProduto: MouraLabel;
    readonly cboListaPreco: MouraComboBox;
    readonly cboListaPrecoProduto: MouraComboBox;
    readonly cboModelo: MouraComboBox;
    readonly txtDataProduto: MouraTextBoxData;
    readonly txtDataServico: MouraTextBoxData;
    readonly txtHoraServico: MouraTextBoxHora;
    readonly txtHoraProduto: MouraTextBoxHora;
    readonly txtProfissionalProduto: MouraTextBoxProcura;
    readonly txtObservacaoProduto: MouraTextBox;
    readonly txtObservacao: MouraTextBox;
    readonly chkCobrado: MouraCheckBox;
    readonly cboEmpresa_List: HTMLSelectElement;
    readonly hdnDoc: HTMLInputElement;
    readonly hdnConfigPET: HTMLInputElement;
    readonly hdnPathFotoAnimal: HTMLInputElement;
    readonly btnVacinas: MouraButton;
    readonly btnDiagnostico: MouraButton;
    readonly lblEndereco_TextBox: HTMLInputElement;
    readonly lblComplemento_TextBox: HTMLInputElement;
    readonly lblCidade_TextBox: HTMLInputElement;
    readonly lblFone_TextBox: HTMLInputElement;
    readonly lblSaldoDevedor_TextBox: HTMLInputElement;
    readonly lblCredito_TextBox: HTMLInputElement;
    readonly lblEspecie_TextBox: HTMLInputElement;
    readonly lblRaca_TextBox: HTMLInputElement;
    readonly lblCarteirinha_TextBox: HTMLInputElement;
    readonly lblTemperamento_TextBox: HTMLInputElement;
    readonly lblPeso_TextBox: HTMLInputElement;
    readonly lblDataNascimento_TextBox: HTMLInputElement;
    readonly lblIdadeSexo_TextBox: HTMLInputElement;
    readonly lblPelagem_TextBox: HTMLInputElement;
    readonly lblTempoDuracao: MouraLabel;
    readonly lblCHIP_TextBox: HTMLInputElement;
    readonly lblRGA_TextBox: HTMLInputElement;
    readonly lblObsServico_TextBox: HTMLInputElement;
    readonly callBackServico: MouraCallBackPanel;
    readonly callBackProduto: MouraCallBackPanel;
    readonly grdAgPendente: MouraGridViewJS;
    readonly grdDoc: MouraGridViewJS;
    readonly grdServicos: MouraGridViewJSEditavel;
    readonly grdProdutos: MouraGridViewJSEditavel;
    readonly grdParticipantes: MouraGridViewJSEditavel;
    readonly grdConsultas: MouraGridViewJS;
    readonly grdCheckListItens: MouraGridViewJS;
    readonly btnImpDoc: MouraButton;
    readonly btnFecharAgPendente: MouraButton;
    readonly hdnMsgAdicionar: HTMLInputElement;
    readonly hdnMsgAdicionarProduto: HTMLInputElement;
    readonly hdnUltimoProprietario: HTMLInputElement;
    readonly dlgParticipante: MouraModal;
    readonly dlgAgPendente: MouraModal;
    readonly dlgAtendimentoContinuo: MouraModal;
    readonly cboEncaminhamento: MouraComboBox;
    readonly dlgConsultas: MouraModal;
    readonly txtParticipante: MouraTextBoxProcura;
    readonly txtComissaoReais: MouraTextBox;
    readonly txtCheckListProcura: MouraTextBoxProcura;
    readonly txtCheckList: MouraTextBox;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly txtProfissionalResponsavel: MouraTextBoxProcura;
    readonly btnContinuo: MouraButton;
    readonly btnOK: MouraButton;
    readonly btnVoltar: MouraButton;
    readonly btnCancelarConsulta: MouraButton;
    readonly btnCalcularContinuos: MouraButton;
    readonly btnOKContinuo: MouraButton;
    readonly btnCancelarContinuo: MouraButton;
    readonly txtQuantidadeDias: MouraTextBox;
    readonly txtQuantidadeContinuos: MouraTextBox;
    readonly txtConvenio: MouraTextBoxProcura;
    readonly txtAutorizacaoConvenio: MouraTextBox;
    readonly chkGerarSemData: MouraCheckBox;
    readonly grdAtendimentosContinuos: MouraGridViewJS;
    readonly sgnCheckList: MouraSignaturePad;
    readonly btnAssinatura: MouraButton;
    readonly btnAdicionar: MouraButton;
    readonly tab: MouraTabPanel;
    readonly EnvioSms: MouraSMS;
    readonly dlgVacinasPendentes: MouraModal;
    readonly btnOkPendentes: MouraButton;
    readonly btrCancelarPendentes: MouraButton;
    readonly grdPendentes: MouraGridViewJSEditavel;
    readonly txtServicoPendente: MouraTextBoxProcura;
    readonly dlgVacinasAgendadas: MouraModal;
    readonly grdAgendamentos: MouraGridViewJS;
    readonly grdIncidencia: MouraGridViewJSEditavel;
    readonly btnVoltarAgendamento: MouraButton;
    readonly dlgDiagnostico: MouraModal;
    readonly txtDiagnostico: MouraTextBox;
    readonly btnVoltarDiagnostico: MouraButton;
    readonly dlgMotivoExclusao: MouraModal;
    readonly dlgMotivoTroca: MouraModal;
    readonly txtMotivoExclusao: MouraTextBox;
    readonly btnConfirmarExclusao: MouraButton;
    readonly btnCancelarExclusao: MouraButton;
    readonly btnConfirmarTroca: MouraButton;
    readonly btnCancelarTroca: MouraButton;
    readonly dlgPendentes: MouraModal;
    readonly grdAtendimentosPendentes: MouraGridViewJS;
    readonly btnVoltarPendentes: MouraButton;
    readonly btnPendentes: MouraButton;
    readonly btnHisProdutos: MouraButton;
    readonly btnHisPacotes: MouraButton;
    readonly btnHistoricoServico: MouraButton;
    readonly btnImprimir: MouraButton;
    readonly btnImprimirTicket: MouraButton;
    readonly btnImprimirCheckList: MouraButton;
    readonly fotosAnimal: MouraFotosPasta;
    readonly btnCarregarFotos: MouraButton;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly btnZanthus: MouraButton;
    readonly btnSolicitarAprovacao: MouraButton;
    readonly btnCortesia: MouraButton;
    readonly btnEstornarConvenio: MouraButton;
    readonly lblZanthus: MouraLabel;
    readonly lblCortesia: MouraLabel;
    readonly lblStatusPagamentoAPP: MouraLabel;
    readonly hdnServicoPacote: HTMLInputElement;
    readonly btnFecharHistorico: MouraButton;
    readonly grdHistorico: MouraGridViewJS;
    readonly dlgHistorico: MouraModal;
    readonly btnHistoricoAtendimentos: MouraButton;
    readonly lblHistProprietario: MouraLabel;
    readonly lblHistAnimal: MouraLabel;
    readonly lblHistTotal: MouraLabel;
    readonly btnConsulta: MouraButton;
    readonly btnPeso: MouraButton;
    readonly cboTipoEncaminhamento: MouraComboBox;
    readonly cboEmpresaEncaminhamento: MouraComboBoxEmpresa;
    readonly txtProfissionalEncaminhou: MouraTextBoxProcura;
    readonly txtClinicaEncaminhou: MouraTextBox;
    readonly txtVeterinarioExternoEncaminhou: MouraTextBox;
    readonly txtCRMVVeterinario: MouraTextBox;
    readonly txtTelefoneContatoEncaminhou: MouraTextBox;
    readonly txtEmailEncaminhou: MouraTextBox;
    readonly ConfiguracoesPET: any;
    readonly IsIntegracaoZanthus: boolean;
    readonly Atendimento_Bloquear_Editar_ValorServico: boolean;
    Incidencias: SiSMoura.Core.Entity.Animais_Incidencia[];
    PendentesAnimal: any[];
    readonly dlgInfoProprietario: MouraModal;
    readonly btnDlgInfoProprietarioOK: MouraButton;
    readonly btnDlgInfoProprietarioCadastro: MouraButton;
    readonly DlgInfoProprietarioInfo: HTMLElement;
    readonly DivEncaminhamento: HTMLElement;
    readonly dvLegendaPlano: HTMLDivElement;
    Participante: any;
    readonly mdAutorizacoes: MouraModal;
    readonly lblAutorizacoes: HTMLElement;
    readonly btnFecharAutorizacao: MouraButton;
    protected OnTxtPetLimpouAnimal(): void;
    protected Init(): void;
    protected OnClickFecharAgendamento(s: MouraButton, e: MouraClickEventArgs): void;
    private inserirItem;
    protected OnAdicionandoItemServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    OnPageLoad(): void;
    protected OnComboBoxEmpresaChange(): void;
    protected VerificarAutorizacaoIncidencia(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected AlterarCamposAtendimentoPago(isAtendimentopago: boolean): void;
    protected AlterarColunasEditaveisVenda(editavel: boolean): void;
    protected OnGrdAgPendentesClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdAgendamentosClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnEnvioSmsEnviandoMensagem(s: any, e: EnviandoMensagemEventArgs): void;
    protected OnEnvioSmsFechou(s: any, e: MouraEventArgs): void;
    private respondeuMotivoExclusao;
    protected OnAntesDeletar(): boolean;
    protected OnClickCancelarExclusao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarTroca(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickConfirmarTroca(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickConfirmarExclusao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Atendimento): void;
    protected HabilitarAbaEncaminhamento(flag: boolean): void;
    private verificadoAutorizacaoDescontoAtendimento;
    private verificouAlertaIncidencia;
    private verificouCortesia;
    private verificouFilhote;
    protected OnAntesGravar(): boolean;
    protected VerificarAutorizacaoDescontoAtendimento(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnDepoisGravar(): boolean;
    protected OnRepostaImprimirTodosDocumentos(result: MsgBoxResultEventArgs): void;
    protected OnRespostaCienteIncidencia(result: MsgBoxResultEventArgs): void;
    protected VerificarEnviarSMSDepoisGravar(): void;
    protected VerificarVacinasPendentes(): void;
    protected OnBtnCancelarConsultaClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnGrdConsultasClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdServicosClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdProdutosClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    AbrirModalParticipantes(servicoParticipante: SiSMoura.Core.Entity.ServicosAtendimento): void;
    protected OnBtnOkClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnVoltarClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnTxtProfissionalEncaminhouProcurou(s: MouraTextBoxProcuraRetornoProcura, e: MouraEventArgs): void;
    private profissionalPrestador;
    protected OnTxtProfissionalProcurou(s: MouraTextBoxProcuraRetornoProcura, e: MouraEventArgs): void;
    protected OnTxtCheckListProcuraProcurou(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected AlteraVisibleProfissionalResponsavel(flag: boolean): void;
    protected OnTxtParticipanteProcurou(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnBtnCalcularContinuosClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnbtnFecharAutorizacaoClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnOkContinuosClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private verificouFeriados;
    protected GravarContinuos(): void;
    protected RetornoFeriadosContinuo(result: MsgBoxResultEventArgs): void;
    protected OnClickAtendimentoContinuo(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnBtnCancelarContinuosClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private PreencherServicos;
    private PreencherProdutos;
    private adicionarCamposComputadosAtendimento;
    private GetTotalServicos;
    private GetTotalProdutos;
    protected OnValidandoItemPendente(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnValidandoItemParticipante(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnExcluindoItemParticipante(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnExcluindoIncidencia(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAdicionouParticipante(s: any, e: any): void;
    protected OnLimpouParticipante(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAdicionouItemPendente(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAdicionandoGridIncidencia(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnLimpouItemPendente(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnLimpouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnLimpouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAlterandoItem(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnGerouCelulaGradeServicos(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnExcluindoItemServico(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnExcluindoItemProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    private retornoComplementosItemServico;
    private getRetornoComplementoItemServico;
    private perguntouAdicionarServicoDuplicado;
    private perguntouAdicionarProdutoDuplicado;
    private mostrouParticipantes;
    private mostrouConsulta;
    private mostrouFuncao;
    protected OnValidandoItemServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected VerificarAutorizacaoTroca(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnSelecionouOpcaoInserirServico(e: MsgBoxResultEventArgs): void;
    protected ServicoZerado(servico: number): boolean;
    protected OnValidandoItemProduto(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnSelecionouOpcaoInserirProduto(e: MsgBoxResultEventArgs): void;
    protected VerificarFuncaoAdmBloquearRetorno(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnSetouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnSetouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private IniciarValoresAutomaticosServico;
    private IniciarValoresAutomaticosProduto;
    protected OnAdiciouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected VerificaAutorizacaoPlano(item: SiSMoura.Core.Entity.ServicosAtendimento): void;
    protected VerificarElegibilidadePlano(codAnimal: number): void;
    protected OnAdiciouItemProduto(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAntesBuscarExistente(): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Animais_Atendimento): void;
    protected PodeAlterarServicoPago(): boolean;
    protected OnAntesSetEntidade(eventArg: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Animais_Atendimento>): void;
    private _mostrarMensagem;
    protected OnTxtPetProcurouAnimal(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected preencherAgendamentos(codigoAnimal: number, codEmpresa: number, codigoAtendimento: number): void;
    protected OnSelecionouMSGBoxAgendamentoPendente(e: MsgBoxResultEventArgs): void;
    protected OnSelecionouMSGBoxAgendamento(e: MsgBoxResultEventArgs): void;
    private mostrarAgendamentoVacina;
    protected verificarAgPendente(): boolean;
    private alterarVisibleBotaoPendente;
    private alterarVisibleBotaoDiagnostico;
    private alterarVisibleBotaoAgendamentosPendentes;
    protected OnTxtPetProcurouProprietario(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    private OnMsgBoxCadastroProprietario;
    protected OnCboListaPreco_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboTipoEncaminhamentoComboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected HabilitarTipoEncaminhamento(tipo: string): void;
    protected OnCboListaPrecoProduto_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnTxtServicoProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnTxtProdutoProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnClickAssinatura(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickVacinas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickVoltarAgendamento(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickDiagnostico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickVoltarDiagnostico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOkPendente(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarPendente(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickPendentes(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickVoltarPendentes(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickHisProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickHisPacote(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickHistoricoServico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirTicket(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCarregarFotos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirChecklist(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnGrdAtendimentosPendentesSelecionouLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnSalvouAssinatura(s: any, e: any): void;
    protected PreencherGridDocumentos(): void;
    protected OnClickImprimirDoc(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickImprimirDocAcidente(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnCboListaPrecoGotFocus(s: any, e: any): void;
    protected OnCboListaPrecoProdutoGotFocus(s: any, e: any): void;
    protected OnAntesAbrirProcuraProfissional(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnAntesAbrirProcuraProfissionalResponsavel(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnTxtProfissionalResponsavelProcurou(s: MouraTextBoxProcuraRetornoProcura, e: MouraEventArgs): void;
    protected OnClickBotaoZanthus(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecinouOpcaoZanthus(e: MsgBoxResultEventArgs): void;
    protected OnClickBotaoCortesia(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecinouOpcaoCortesia(e: MsgBoxResultEventArgs): void;
    protected OnClickBotaoEstornar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecinouOpcaoEstornar(e: MsgBoxResultEventArgs): void;
    protected IsAtendimentoConvenio(): boolean;
    protected CorrigirTextoBotaoZanthus(): void;
    protected OntxtConvenioLostFocus(): void;
    protected OnProcurouConvenio(s: any, e: any): void;
    protected OnAntesAbrirProcuraConvenio(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OntxtAutorizacaoConvenioLostFocus(): void;
    protected OnClickBotaoFecharHistorico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoHistoricoAtendimentos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnSelecionouLinhaHistorico(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnFechouModalHistorico(s: any, e: any): void;
    protected OnClickBotaoConsulta(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected VerificarStatusPagamentoAPP(entity: SiSMoura.Core.Entity.Animais_Atendimento): void;
    protected OnCboEncaminhamento(s: MouraComboBox, e: MouraEventArgs): void;
    protected AlterarVisibleEncaminhamento(value: boolean): void;
    protected OnClickPesos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected IsConvenioProprio(codConvenio: number): boolean;
    protected OnClickSolicitarConvenio(): void;
    protected IsAtendimentoPago(codAtendimento: number): boolean;
    protected OnBtnDlgInfoProprietarioOKClick(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnBtnDlgInfoProprietarioCadastroClick(s: MouraButton, e: MouraClickEventArgs): void;
    private AbrirModalAtualizarInfoProprietario;
    protected MudouComissaoReal(newValue: any, oldValue: any): void;
    private flag;
    protected MudouComissaoPorcentagem(newValue: any, oldValue: any): void;
    private _codSala;
    protected verificarServicoCategoriaSala(codEmpresa: number, codProfissional: number, data: Date, codServico: number): string;
    protected OntxtDataServicoChanged(): void;
    protected OntxtHoraServicoChanged(): void;
    protected AtualizarListaPrecoServico(): void;
}
declare var c_Animal: C_Animal;
//# sourceMappingURL=C_Animal.d.ts.map