declare class C_AtenAni extends MouraPageAngular {
    private listaPrecos;
    private listaPrecosProduto;
    private horarioAtendimento;
    private UltimoRegistro;
    Atendimento: SiSMoura.Core.Entity.Animais_Atendimento;
    Servicos: SiSMoura.Core.Entity.ServicosAtendimento[];
    Servico: SiSMoura.Core.Entity.ServicosAtendimento;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly lblEspecie: MouraLabel;
    readonly lblRaca: MouraLabel;
    readonly lblIdade: MouraLabel;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly chkJuntarServicos: MouraCheckBox;
    readonly lblUltimo: MouraLabel;
    readonly txtServico: MouraTextBoxProcura;
    readonly cboListaPreco: MouraComboBox;
    readonly txtValorUnitario: MouraTextBox;
    readonly txtQuantidade: MouraTextBox;
    readonly txtDesconto: MouraTextBox;
    readonly btnImprimir: MouraButton;
    readonly txtDescontoPorcent: MouraTextBox;
    readonly lblTotal: MouraLabel;
    readonly cboModelo: MouraComboBox;
    readonly txtDataServico: MouraTextBoxData;
    readonly txtHoraServico: MouraTextBoxHora;
    readonly txtHoraPegar: MouraTextBoxHora;
    readonly txtHoraEntrega: MouraTextBoxHora;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly txtObservacao: MouraTextBox;
    readonly grdServicos: MouraGridViewJSEditavel;
    readonly txtDias: MouraTextBox;
    readonly txtQuantidaDeDias: MouraTextBox;
    readonly btnGravar: MouraButton;
    readonly btnNovo: MouraButton;
    readonly chkData: MouraCheckBox;
    protected Init(): void;
    OnPageLoad(): void;
    protected LimparAtendimento(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Atendimento): void;
    protected VerificarAutorizacaoDescontoAtendimento(retorno: MouraFuncoesAdministrativasRetorno): void;
    private PreencherServicos;
    private adicionarCamposComputadosAtendimento;
    private GetTotalServicos;
    protected OnLimpouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnExcluindoItemServico(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    private retornoComplementosItemServico;
    private getRetornoComplementoItemServico;
    private mostrouFuncao;
    protected OnValidandoItemServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnSelecionouOpcaoInserirServico(e: MsgBoxResultEventArgs): void;
    protected OnSetouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private IniciarValoresAutomaticosServico;
    protected OnAdicionandoItemServico(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAdiciouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAntesSetEntidade(eventArg: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Animais_Atendimento>): void;
    protected OnTxtPetProcurouAnimal(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnCboListaPreco_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnNovoClick(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnGravarClick(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnTxtServicoProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnClickImprimir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnCheckData(): void;
    protected OnCboListaPrecoGotFocus(s: any, e: any): void;
    protected OnAntesAbrirProcura(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected GravarContinuos(): void;
    protected AtualizarUltimoAtendimento(): void;
}
declare var c_AtenAni: C_AtenAni;
//# sourceMappingURL=C_AtenAni.d.ts.map