declare class R_AgProfi extends MouraPageRelacaoAngular {
    readonly AccordionFiltros: MouraAccordion;
    readonly Grid: MouraGridViewJS;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly dlgMotivoExclusao: MouraModal;
    readonly txtMotivoExclusao: MouraTextBox;
    readonly btnConfirmarExclusao: MouraButton;
    readonly btnCancelarExclusao: MouraButton;
    readonly dlgMotivoCancelamento: MouraModal;
    readonly txtMotivoCancelamento: MouraTextBox;
    readonly btnConfirmarCancelamento: MouraButton;
    readonly btnCancelarCancelamento: MouraButton;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboTipoProfissional: MouraComboBox;
    readonly accFiltro: MouraAccordion;
    readonly btnExcluir: MouraButton;
    readonly btnCancelamento: MouraButton;
    readonly btnEncaixe: MouraButton;
    readonly btnFecharHistorico: MouraButton;
    readonly grdHistorico: MouraGridViewJS;
    readonly lstHistAtendimentos: MouraRadioButtonList;
    readonly lblHistAtendimento: MouraLabel;
    readonly lblHistProprietario: MouraLabel;
    readonly lblHistAnimal: MouraLabel;
    readonly lblHistTotal: MouraLabel;
    readonly lblHistVenda: MouraLabel;
    readonly lblHistCadastrado: MouraLabel;
    readonly dlgHistorico: MouraModal;
    readonly btnCadastroAtividade: MouraButton;
    protected LimparCampos(): void;
    protected ConfigurarGrade(): void;
    protected FuncaoSort(data: any): any;
    protected FuncaoCustomText(data: any): string;
    OnPageLoad(): void;
    protected Init(): void;
    PreencherGrade(): void;
    GerarGrade(): void;
    protected ValidarCampos(): boolean;
    protected OnGridCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    private codProfissional;
    private codEmpresa;
    private dataAtendimento;
    protected OnGridClicouBotao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected AbrirNovoAtendimento(dataAtendimento: string, horaAtendimento: string, codProfissional: number, codEmpresa: number, isEncaixe: boolean): void;
    protected AbrirAtendimento(codAtendimento: number): void;
    protected OnPesquisouCliente(s: any, e: any): void;
    private NOVO_ATENDIMENTO;
    protected OnRetornouModalAtendimento(s: any, e: MouraTelaModalRetornouEventArgs): void;
    protected CarregarHistoricoAtendimento(codAtendimento: number, isProximoAtendimento: boolean): void;
    protected OnClickBtnEncaixe(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnFechouHistorico(s: any, e: MouraEventHandler): void;
    protected OnLstHistAtendimentoChange(): void;
    protected OnClickBotaoFecharHistorico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoCadastroAtividade(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarExclusao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarCancelamento(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickConfirmarExclusao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickConfirmarCancelamento(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnDepoisExcluir(result: MsgBoxResultEventArgs): void;
    protected OnRespostaCancelarAtendimento(result: MsgBoxResultEventArgs): void;
    private respondeuMotivoExclusao;
    protected OnClickBotaoExcluir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    private respondeuMotivoCancelamento;
    protected OnClickBotaoCancelamento(s: MouraButton, e: MouraClickEventArgs): boolean;
}
declare var r_AgProfi: R_AgProfi;
//# sourceMappingURL=R_AgProfi.d.ts.map