declare class R_AgPetC extends MouraPageRelacaoAngular {
    readonly AccordionFiltros: MouraAccordion;
    readonly Grid: MouraGridViewJS;
    readonly txtData: MouraTextBoxData;
    readonly dlgMotivoExclusao: MouraModal;
    readonly chkProfPreferencial: MouraCheckBox;
    readonly txtMotivoExclusao: MouraTextBox;
    readonly txtServico: MouraTextBoxProcura;
    readonly btnConfirmarExclusao: MouraButton;
    readonly btnCancelarExclusao: MouraButton;
    readonly dlgMotivoCancelamento: MouraModal;
    readonly dlgMotivoReagendamento: MouraModal;
    readonly txtMotivoCancelamento: MouraTextBox;
    readonly btnConfirmarCancelamento: MouraButton;
    readonly btnCancelarCancelamento: MouraButton;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly cboTipoProfissional: MouraComboBox;
    readonly cboMotivoCancelamento: MouraComboBox;
    readonly cboMotivoReagendamento: MouraComboBox;
    readonly accFiltro: MouraAccordion;
    readonly btnRecolher: MouraButton;
    readonly btnExpandir: MouraButton;
    readonly btnExcluir: MouraButton;
    readonly btnCancelamento: MouraButton;
    readonly btnEncaixe: MouraButton;
    readonly btnCheckin: MouraButton;
    readonly btnReagendar: MouraButton;
    readonly btnConfirmarReagendamento: MouraButton;
    readonly btnCancelarReagendamento: MouraButton;
    readonly btnFecharHistorico: MouraButton;
    readonly grdHistorico: MouraGridViewJS;
    readonly lstHistAtendimentos: MouraRadioButtonList;
    readonly lblHistAtendimento: MouraLabel;
    readonly lblHistProprietario: MouraLabel;
    readonly lblHistTotal: MouraLabel;
    readonly lblPreferencial: HTMLInputElement;
    readonly lblPreferencialCor: HTMLInputElement;
    readonly lblClienteFaltou: HTMLInputElement;
    readonly lblClienteFaltouCor: HTMLInputElement;
    readonly lblHistCadastrado: MouraLabel;
    readonly dlgHistorico: MouraModal;
    readonly btnCadastroAtividade: MouraButton;
    readonly btnAvaliacao: MouraButton;
    readonly btnListaEspera: MouraButton;
    readonly dlgListaEspera: MouraModal;
    readonly grdServicosEspera: MouraGridViewJSEditavel;
    Servicos: SiSMoura.Core.Entity.Animais_Lista_Espera_ServicoRetorno[];
    readonly txtPetEspera: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtServicoEspera: MouraTextBoxProcura;
    readonly cboEmpresaEspera: MouraComboBoxEmpresa;
    readonly txtProfissionalEspera: MouraTextBoxProcura;
    readonly txtPeriodoEspera: MouraTextBoxPeriodo;
    readonly chkHorarioEspera: MouraCheckBox;
    readonly txtHoraInicioEspera: MouraTextBoxHora;
    readonly txtHoraFimEspera: MouraTextBoxHora;
    readonly btnConfirmarEspera: MouraButton;
    readonly btnCancelarEspera: MouraButton;
    readonly dlgVerificarClienteListaEspera: MouraModal;
    readonly lblTotalListaEsperaResultado: MouraLabel;
    readonly lblCodProprietarioLista: MouraLabel;
    readonly lblProprietarioLista: MouraLabel;
    readonly lblTelefoneLista: MouraLabel;
    readonly lblCodAnimalLista: MouraLabel;
    readonly lblAnimalLista: MouraLabel;
    readonly lblData: MouraLabel;
    readonly btnFinalizarAtendimentoLista: MouraButton;
    readonly btnProximoLista: MouraButton;
    readonly btnMenos: MouraButton;
    readonly btnMais: MouraButton;
    readonly agpData: MouraAgrupamento;
    readonly accFiltros: MouraAccordion;
    protected OnClickBtnMenos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnMais(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected LimparCampos(): void;
    protected LimparCamposEspera(): void;
    protected ConfigurarGrade(): void;
    protected FuncaoSort(data: any): any;
    protected FuncaoCustomText(data: any): string;
    OnPageLoad(): void;
    protected OnMotivoSelectedItemChanged(): void;
    protected OnchkProfPreferencialCheckChanged(): void;
    protected OnSelectedItemChanged(): void;
    protected Init(): void;
    protected verificarAgendamento(tipo: number): void;
    protected cboTipoProfissionalSelectedItemChanged(): void;
    PreencherGrade(): void;
    protected retornarDiaSemana(dia: number): string;
    GerarGrade(): void;
    protected ValidarCampos(): boolean;
    protected OnGridCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    private codProfissional;
    private codEmpresa;
    protected OnGridClicouBotao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBtnExpandir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnRecolher(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickbtnCancelarReagendamento(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickBtnReagendar(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickbtnConfirmarReagendamento(s: MouraButton, e: MouraClickEventArgs): void;
    protected reagendamento(motivo: number): void;
    protected AbrirNovoAtendimento(dataAtendimento: string, horaAtendimento: string, codProfissional: number, codEmpresa: number, isEncaixe: boolean, isAgendamentoPreferencial: boolean, Codigo_Sala: number, Sala_Descricao: string, codAnimal?: number, motivoReagendamento?: number, atendimentoReagendamento?: number): void;
    protected AbrirAtendimento(codAtendimento: number): void;
    protected OnPesquisouCliente(s: any, e: any): void;
    protected OnAntesAbrirPesquisaEmpresa(s: any, e: MouraListBoxEmpresaAbriuProcuraEventArgs): void;
    private NOVO_ATENDIMENTO;
    protected OnRetornouModalAtendimento(s: any, e: MouraTelaModalRetornouEventArgs): void;
    protected CarregarHistoricoAtendimento(codAtendimento: number, isProximoAtendimento: boolean): void;
    protected OnClickBtnEncaixe(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickbtnAvaliacao(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickbtnCheckin(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnGridHistoricoClicouBotao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected ConcluirServico(codServico: number): void;
    protected OnSelecionouOpcaoConcluir(e: MsgBoxResultEventArgs): void;
    protected OnFechouHistorico(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnLstHistAtendimentoChange(): void;
    protected OnClickBotaoFecharHistorico(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickBotaoCadastroAtividade(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickIncluirServicoEspera(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickCancelarExclusao(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickCancelarCancelamento(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickListaEspera(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnAntesAbrirProcuraProfissionalEspera(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnTxtProfissionalEsperaProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnCheckHorarioEspera(s: MouraCheckBox, e: MouraEventArgs): void;
    protected OnClickConfirmarEspera(s: MouraButton, e: MouraClickEventArgs): void;
    protected ValidarCamposEspera(): string;
    protected OnClickCancelarEspera(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickConfirmarExclusao(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickConfirmarCancelamento(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnDepoisExcluir(result: MsgBoxResultEventArgs): void;
    private listaEspera;
    protected OnDepoisCancelamento(result: MsgBoxResultEventArgs): void;
    protected OnRespostaCancelarAtendimento(result: MsgBoxResultEventArgs): void;
    protected OnRespostaVisualizarLista(result: MsgBoxResultEventArgs): void;
    protected VerificarClientesListaEspera(): void;
    protected OnClickProximoLista(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnClickFinalizarAtendimentoLista(s: MouraButton, e: MouraClickEventArgs): void;
    private respondeuMotivoExclusao;
    protected OnClickBotaoExcluir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    private respondeuMotivoCancelamento;
    protected OnClickBotaoCancelamento(s: MouraButton, e: MouraClickEventArgs): boolean;
}
declare var r_AgPetC: R_AgPetC;
//# sourceMappingURL=R_AgPetC.d.ts.map