declare class C_Pro_Re extends MouraPageAngular {
    readonly txtCodReferencia: MouraTextBoxProcura;
    readonly AgpRef: MouraAgrupamento;
    readonly txtReferencia: MouraTextBox;
    readonly txtProcuraReferencia: MouraTextBoxProcura;
    readonly txtProcuraImportacao: MouraTextBoxProcura;
    readonly txtDescricao: MouraTextBox;
    readonly txtModelo: MouraTextBoxProcura;
    readonly txtPrecoCusto: MouraTextBox;
    readonly Tab: MouraTabPanel;
    readonly txtMargem: MouraTextBox;
    readonly txtPrecoVenda: MouraTextBox;
    readonly txtLinha: MouraTextBoxProcura;
    readonly txtMarca: MouraTextBoxProcura;
    readonly txtEstoque: MouraTextBox;
    readonly txtDecreto: MouraTextBoxProcura;
    readonly cboConvUndNf: MouraComboBox;
    readonly txtPeso: MouraTextBox;
    readonly txtDataVigencia: MouraTextBoxData;
    readonly cboIAT: MouraComboBox;
    readonly cboUnidade: MouraComboBox;
    readonly cboTaxaTributaria: MouraComboBox;
    readonly lblCadastrado: MouraLabel;
    readonly hdnRespostaDataVigencia: HTMLInputElement;
    readonly hdnRespostaCodBarra: HTMLInputElement;
    readonly hdnRespostaCodBarraLista: HTMLInputElement;
    readonly grdImpostos: MouraGridViewJS;
    Impostos: SiSMoura.Core.Entity.ProdutoRegraImpostoRetorno[];
    readonly txtDescricaoCusto: MouraTextBox;
    readonly cboOperacaoCusto: MouraComboBox;
    readonly optTipoCalculo: MouraRadioButtonList;
    readonly txtValorCusto: MouraTextBox;
    readonly grdCustos: MouraGridViewJSEditavel;
    Custos: SiSMoura.Core.Entity.Produto_Custo[];
    Custo: SiSMoura.Core.Entity.Produto_Custo;
    readonly grdPrecos: MouraGridViewJS;
    Precos: SiSMoura.Core.Entity.ProdutoPrecoRetorno[];
    readonly grdPersonalizados: MouraGridViewJS;
    Personalizados: SiSMoura.Core.Entity.ProdutoCamposPersonalizadosRetorno[];
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly grdFornecedores: MouraGridViewJSEditavel;
    Fornecedores: SiSMoura.Core.Entity.FornecedorProdutoRetorno[];
    readonly cboEmpresaCfop: MouraComboBoxEmpresa;
    readonly cboCfop: MouraComboBox;
    readonly cboRegraCfop: MouraComboBox;
    readonly grdRegraCfop: MouraGridViewJSEditavel;
    Cfops: SiSMoura.Core.Entity.ProdutoRegraImpostoCFOP[];
    readonly cboEmpresaIva: MouraComboBoxEmpresa;
    readonly cboEstadoIva: MouraComboBox;
    readonly txtIvaPauta: MouraTextBox;
    readonly txtPautaValor: MouraTextBox;
    readonly grdIva: MouraGridViewJSEditavel;
    Ivas: SiSMoura.Core.Entity.ProdutoIvaPautaRetorno[];
    readonly btnGravar: MouraButton;
    readonly btnExcluir: MouraButton;
    readonly btnNovo: MouraButton;
    readonly cboUnidadeConversao: MouraComboBox;
    readonly cboCalculo: MouraComboBox;
    readonly txtFatorConversao: MouraTextBox;
    readonly txtCustoConversao: MouraTextBox;
    readonly txtVendaConversao: MouraTextBox;
    readonly grdConversao: MouraGridViewJSEditavel;
    Conversoes: SiSMoura.Core.Entity.Produto_Unidade_Conversao[];
    readonly txtCodigoProduto: MouraTextBoxProcura;
    readonly txtCodigoBarras: MouraTextBoxProcura;
    readonly txtCor: MouraTextBoxProcura;
    readonly txtTamanho: MouraTextBox;
    readonly txtEstoqueMinimo: MouraTextBoxProcura;
    readonly txtObservacao: MouraTextBox;
    readonly grdProdutos: MouraGridViewJSEditavel;
    Produtos: SiSMoura.Core.Entity.ProdutoDadosRetorno[];
    Produto: SiSMoura.Core.Entity.ProdutoDadosRetorno;
    readonly mdProcura: ModalProcura;
    readonly dvPrincipal: HTMLDivElement;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnPesquisouCodReferencia(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnGerouCelulaGradeProduto(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnTxtReferenciaChange(): void;
    protected OnTxtUsarReferenciaKeyDown(e: any): void;
    protected OnTxtReferenciaKeyDown(e: any): void;
    protected OnProcurouImportacao(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnProcurouReferencia(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnTxtMargemChange(): void;
    protected OnTxtPrecoVendaChange(): void;
    private CalculaPrecoVendaProduto;
    private OnDepoisBuscarExistente;
    protected criarEntidadePersonalizados(Entidade: SiSMoura.Core.Entity.Produto): void;
    private configuracoesCamposIniciais;
    private configuracoesGridsIniciais;
    private preencherListaPreco;
    private preencherGridImpostos;
    private preencherGridCustos;
    protected OnClickIncluirFornecedor(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickIncluirCustos(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickIncluirRegraCfop(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickIncluirIvaPauta(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickIncluirConversao(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickIncluirProduto(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnGrdProdutosCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected OnClickBtnNovo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private LimparCampos;
    private LimparCamposGrid;
    protected OnPesquisouCodigoProduto(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnClickBtnGravar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private Gravar;
    private OnAntesGravar;
    protected OnRespostaDataVigencia(result: MsgBoxResultEventArgs): void;
    protected OnRespostaCodigoBarraProduto(result: MsgBoxResultEventArgs): void;
    protected OnRespostaCodigoBarraListaProduto(result: MsgBoxResultEventArgs): void;
    private preencherProdutoPreco;
    private preencherFornecedor;
    private preencherCustos;
    private preencherImposto;
    private preencherRegraCfop;
    private preencherProdutoUnidadeConversao;
    protected OnClickBtnExcluir(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnRespostaExcluirRegistro(result: MsgBoxResultEventArgs): void;
    private Excluir;
    protected OnClicouCellGrdImpostos(s: any, e: MouraGridViewJSItemEventArgs): void;
    protected OnAlterandoItemProduto(s: any, e: MouraGridViewJSItemEventArgs): void;
}
declare const c_Pro_Re: C_Pro_Re;
//# sourceMappingURL=C_Pro_Re.d.ts.map