declare class C_NFSe extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Fiscal_Nfse> {
    readonly cboEmpresa: MouraComboBox;
    readonly cboLocalOperacao: MouraComboBox;
    readonly lblForaMun: MouraLabel;
    readonly txtCodigoCliente: MouraTextBoxProcura;
    readonly chkISSRetido: MouraCheckBox;
    readonly txtCidadeOperacao: MouraTextBoxProcura;
    readonly txtCodServico: MouraTextBoxProcura;
    readonly txtNomeCliente: MouraTextBox;
    readonly txtRg: MouraTextBox;
    readonly txtCpf: MouraTextBoxCPF;
    readonly txtCidade: MouraTextBoxProcura;
    readonly txtTelefone: MouraTextBoxTelefone;
    readonly txtEndereco: MouraTextBox;
    readonly txtNumero: MouraTextBox;
    readonly txtComplemento: MouraTextBox;
    readonly txtBairro: MouraTextBox;
    readonly txtCep: MouraTextBox;
    readonly txtValAproxTrib: MouraTextBox;
    readonly txtValor: MouraTextBox;
    readonly cboTipoTomador: MouraComboBox;
    readonly cboServico: MouraComboBox;
    readonly txtNumeronfse: MouraTextBoxProcura;
    readonly hdnCodigo: HTMLInputElement;
    readonly hdnSeriePadrao: HTMLInputElement;
    readonly hdnCaminhoXML: HTMLInputElement;
    readonly hdnEmpresa: HTMLInputElement;
    readonly btnMais: MouraButton;
    readonly btnMenos: MouraButton;
    readonly btnTransmitir: MouraButton;
    readonly btnGerarXml: MouraButton;
    readonly btnAssinar: MouraButton;
    readonly btnConsultarNfse: MouraButton;
    RetNFSe: SiSMoura.Core.Entity.FiscalNFeEnvioRetorno;
    protected Init(): void;
    protected OnClickBotaoGerenciarNFSe(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected OnConsultar(): void;
    protected OnClickBotaoConsultar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected OnClickBotaoGerarXML(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected OnClickBotaoAssinarXML(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    OnPageLoad(): void;
    protected OnPesquisarDescricaoCodServico(): void;
    protected chkISSRetidoCheckChanged(): void;
    protected CalcularBase(): void;
    protected CalcularPis(s: SiSMoura.Core.Entity.Servicoempresa): void;
    protected CalcularCofins(s: SiSMoura.Core.Entity.Servicoempresa): void;
    protected CalcularIr(s: SiSMoura.Core.Entity.Servicoempresa): void;
    protected CalcularInss(s: SiSMoura.Core.Entity.Servicoempresa): void;
    protected CalcularCsll(s: SiSMoura.Core.Entity.Servicoempresa): void;
    protected CalcularIssPagar(s: SiSMoura.Core.Entity.Servicoempresa): void;
    protected CalcularValorLiquido(): void;
    protected OnValorValidar(): void;
    protected OnValorDeducaoValidar(): void;
    protected OnDescIncondicionado(): void;
    protected OnDescCondicionado(): void;
    protected OnOutrasRetencoes(): void;
    protected OnValorISSRetido(): void;
    protected OnPis(): void;
    protected OnCofins(): void;
    protected OnIR(): void;
    protected OnINSS(): void;
    protected OnCSLL(): void;
    protected OnPesquisouCodigoServico(): void;
    protected OnMudouComboEmpresa(): void;
    protected PreencherComboServico(): void;
    protected PreencherCamposProcuraServico(): void;
    protected OnPesquisouDados(s: any, e: any): boolean;
    protected OncboLocalOperacaoIndexChanged(): void;
    protected MudouTipo(tipo: String): void;
    protected OnDigitouNumerorps(): boolean;
    protected OnMudouIdentificacao(): void;
    protected retornaNumeracao(): void;
    protected RespostaSequencia(result: MsgBoxResultEventArgs): void;
    protected OnMudouComboSerie(s: any, e: any): void;
    protected OnClickBotaoMais(): void;
    protected OnClickBotaoMenos(): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Fiscal_Nfse): void;
    protected LimparCamposClientes(entidade: SiSMoura.Core.Entity.Fiscal_Nfse): void;
    protected LimparCamposServico(entidade: SiSMoura.Core.Entity.Fiscal_Nfse): void;
}
declare var c_NFSe: C_NFSe;
//# sourceMappingURL=C_NFSe.d.ts.map