declare class C_Agenda extends MouraPageAngular {
    readonly grid: MouraGridViewJS;
    readonly gridTelFone: MouraGridViewJS;
    readonly txtData: MouraTextBoxData;
    readonly cboTipoAgenda: MouraComboBox;
    readonly lstUsuario: MouraCheckBoxList;
    readonly txtCompromisso: MouraTextBox;
    readonly txtHora: MouraTextBox;
    readonly txtUsuarioAgTel: MouraTextBoxProcura;
    readonly txtNome: MouraTextBox;
    readonly txtTelefone: MouraTextBox;
    readonly btnAdicionar: MouraButton;
    Agendas: SiSMoura.Core.Entity.AgendaRetorno[];
    Agenda: SiSMoura.Core.Entity.AgendaRetorno;
    AgendaTelefones: SiSMoura.Core.Entity.Agenda_Telefone[];
    AgendaTelefone: SiSMoura.Core.Entity.Agenda_Telefone;
    AgendasUsuario: SiSMoura.Core.Entity.Agenda_Usuario[];
    AgendaUsuario: SiSMoura.Core.Entity.Agenda_Usuario;
    AgendaCompromissos: SiSMoura.Core.Entity.Agenda[];
    AgendaCompromisso: SiSMoura.Core.Entity.Agenda;
    readonly btnGravar: MouraButton;
    readonly btnLimpar: MouraButton;
    readonly btnNovo: MouraButton;
    readonly mdCompromisso: MouraModal;
    private nomeExistente;
    OnPageLoad(): void;
    protected OnGrdExcluiuLinha(s: any, e: MouraGridViewJSEditavelItemEventArgs): boolean;
    protected OnGrdConsultasClickBotaoLinha(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnClickBotaoFecharPagamento(): void;
    protected OnGrdConsultasClickBotaoLinhaTelefone(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected MudouData(): void;
    protected OnClickIncluirAgenda(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): boolean;
    protected OnNomeExistente(result: MsgBoxResultEventArgs): boolean;
    protected OnGridSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): boolean;
    protected AbrirModalInf(codigoAgendaTelefone: number, rowKey: number): boolean;
    protected OnAlterarCompromisso(result: MsgBoxResultEventArgs): void;
    protected OcultarCampos(): void;
    protected VisibilidadeCampos(): void;
    protected OcultarVisibilidadeTelefone(): void;
    protected MudouTipoAgenda(): void;
    protected LimparCampos(): void;
    GerarGrade(): boolean;
    protected OnGerougrade(d: any): void;
    protected OnErrorGerarGrade(erro: JQueryXHR): void;
    protected OnClickBtnLimpar(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickBtnNovo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBtnGravar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ConverterAgendaTelefone(): void;
    protected ConverterAgenda(): void;
    private Gravar;
    private Deletar;
    protected ValidarCampos(): boolean;
    private codigosUsuario;
    protected PreencherUsuarios(usuarios: SiSMoura.Core.Entity.Usuario[]): void;
    protected OnClickBotaoFechar(): void;
}
declare var c_Agenda: C_Agenda;
//# sourceMappingURL=C_Agenda.d.ts.map