declare class PrioAtiv extends MouraPage {
    readonly cboPeriodo: MouraComboBox;
    readonly DockPendentes: DevExpress.Web.Scripts.ASPxClientDockZone;
    readonly DockPriorizadas: DevExpress.Web.Scripts.ASPxClientDockZone;
    readonly btnOkRecusa: MouraButton;
    readonly btnCancelRecusa: MouraButton;
    readonly mdRecusa: MouraModal;
    readonly txtMotivoRecusa: MouraTextBox;
    readonly hdnAtividadeRecusa: HTMLInputElement;
    readonly hdnPainelRecusa: HTMLInputElement;
    readonly hdnPriorizacaoAtiva: HTMLInputElement;
    readonly lblAtividadeRecusa: MouraLabel;
    readonly mdInf: MouraModal;
    readonly hdnAtividadeInf: HTMLInputElement;
    readonly lblAtividadeInf: MouraLabel;
    readonly txtHistoricoAtividade: MouraTextBox;
    readonly btnFecharInf: MouraButton;
    readonly lblModuloInf: MouraLabel;
    readonly lblDataCadInf: MouraLabel;
    readonly lblClienteInf: MouraLabel;
    readonly lblUsuarioCadastroInf: MouraLabel;
    readonly mdPriorizarProgramacao: MouraModal;
    readonly btnFecharProg: MouraButton;
    readonly cboEquipe: MouraComboBox;
    readonly txtObservacaoProg: MouraTextBox;
    readonly txtDataProg: MouraTextBoxData;
    readonly btnSalvarProg: MouraButton;
    readonly lblModuloProg: MouraLabel;
    readonly lblClienteProg: MouraLabel;
    readonly lblAtividadeProg: MouraLabel;
    readonly grdAtProg: MouraGridViewJS;
    readonly btnInfProg: MouraButton;
    readonly mdAtv: MouraModal;
    readonly btnProcurar: MouraButton;
    readonly btnGerarAtv: MouraButton;
    readonly grdAtv: MouraGridViewJS;
    protected Init(): void;
    protected OnDockPanelPriorizadas(s: any, e: any): void;
    protected OnDockPanelPendentes(s: any, e: any): void;
    protected GravarPriorizacao(codAtividade: number): boolean;
    protected OnClickBotaoPriorizar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs, codAtividade: number, idPanel: string): void;
    protected OncboEquipeSelectedIndexChanged(s: any, e: any): void;
    protected FiltrarGradeEquipe(): void;
    protected AbrirModalPriorizarProgramacao(codAtividade: number): void;
    protected OnClickSalvarPriorizacaoProg(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnCloseModalProgramacao(s: any, e: any): void;
    protected GetAtividadePainel(nomePainel: string): number;
    protected OnCliCkReprovarAtividade(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs, codAtividade: number, idPainel: string): void;
    protected OnClickOKRecusa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelRecusa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ReprovarAtividade(): boolean;
    MaisInformacoesAtividade(codAtividade: number): void;
    protected OnClickFecharInf(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnDockClosing(s: any, e: any, codAtividade: number): void;
    protected IsAtividadePriorizada(codAtividade: number): boolean;
    protected OnClickFecharProg(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected MinimizarDocks(): void;
    protected SetAllowDragging(dockZone: DevExpress.Web.Scripts.ASPxClientDockZone, value: boolean): void;
    protected OnClickMaisInformacoesProgramacao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoGrade(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoProcurar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoGerarProcura(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoGradeProcurar(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected PriorizarAtividade(codAtividade: number): boolean;
}
declare var prioAtiv: PrioAtiv;
//# sourceMappingURL=PrioAtiv.d.ts.map