declare class C_ForPag extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Forma_Pagamento> {
    readonly cboTipoVencimento: MouraComboBox;
    readonly cboTipo: MouraComboBox;
    readonly cboCategoria: MouraComboBox;
    readonly txtDescricao: MouraTextBox;
    readonly txtValor: MouraTextBox;
    readonly tab: MouraTabPanel;
    readonly txtTodosDias: MouraTextBox;
    readonly txtTodosDiasPorc: MouraTextBox;
    readonly cboTodoDia: MouraComboBox;
    readonly txtDias: MouraTextBox;
    readonly txtPorc: MouraTextBox;
    readonly cboDia: MouraComboBox;
    readonly txtDiaDe: MouraTextBox;
    readonly txtDiaAte: MouraTextBox;
    readonly txtDiaFixo: MouraTextBox;
    readonly txtCoeficiente: MouraTextBox;
    readonly chkImprimir: MouraCheckBox;
    readonly chkCentavos: MouraCheckBox;
    readonly chkUltimo_Dia: MouraCheckBox;
    readonly chkProximoMes: MouraCheckBox;
    readonly lstDiaSemana: MouraCheckBoxList;
    readonly cboDiaSemana: MouraComboBox;
    readonly txtCodigo: MouraTextBox;
    readonly grdDias: MouraGridViewJSEditavel;
    readonly grdTodosDias: MouraGridViewJSEditavel;
    readonly grdPeriodos: MouraGridViewJSEditavel;
    readonly grdDiaSemanas: MouraGridViewJSEditavel;
    FormaPagamentoDias: SiSMoura.Core.Entity.Forma_Pagamento_Dias[];
    FormaPagamentoTodosDias: SiSMoura.Core.Entity.Forma_Pagamento_Dias[];
    FormaPagamentoPeriodos: SiSMoura.Core.Entity.Forma_Pagamento_Dias[];
    FormaPagamentoDiaSemanas: SiSMoura.Core.Entity.Forma_Pagamento_Dias[];
    protected Init(): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected OnSelecionouTipoVencimento(): void;
    protected OnSelecionouTipo(): void;
    protected selecionarCheck(chk: MouraCheckBox, valor: boolean): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Forma_Pagamento): void;
    protected OnDepoisGravar(): boolean;
    protected OnAntesGravar(): boolean;
    protected OnDepoisLimpar(): boolean;
    protected BuscarGridDias(): void;
    protected BuscarGridTodosDias(): void;
    protected BuscarGridPeriodos(): void;
    protected BuscarGridDiaSemanas(): void;
    protected OnClickIncluirFormaPagamentoDia(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): boolean;
    protected OnClickIncluirFormaPagamentoTodoDia(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): boolean;
    protected OnClickIncluirFormaPagamentoPeriodo(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): boolean;
    protected OnClickIncluirFormaPagamentoDiaSemana(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): boolean;
    protected OnClickExcluirFormaPagamentoDia(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickExcluirFormaPagamentoPeriodo(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickExcluirFormaPagamentoTodoDia(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnClickExcluirFormaPagamentoDiaSemana(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    OnPageLoad(): void;
    protected LimparCampos(): void;
    protected LimparEntidade(): void;
}
declare var c_ForPag: C_ForPag;
//# sourceMappingURL=C_ForPag.d.ts.map