declare class RetornoValidacaoAtendimento {
    retorno: boolean;
    mensagem: string;
    status: SiSMoura.Core.Entity.Animais_Atendimento.StatusEnvioZanthus;
}
declare class C_HosRes_Angular extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Hospedagem_Reserva> {
    private FLAG_GRID_BAIAS_ONALTEROU;
    private PATH_DOCUMENTOS_RESERVA;
    private isCadastroNovo;
    private validouInformacoesReserva;
    private verificadoAutorizacaoDescontoHospedagem;
    private enviarEmailPagamentoDepoisGravar;
    readonly hdnConfigPET: HTMLInputElement;
    readonly ConfiguracoesPET: any;
    readonly IsIntegracaoZanthus: boolean;
    readonly GetHorarioCheckin: string;
    readonly GetHorarioCheckout: string;
    readonly GetProfissionalDiaria: SiSMoura.Core.Entity.Animais_Veterinario;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly hdnEsperaReserva: HTMLInputElement;
    readonly hdnServicosHospedagem: HTMLInputElement;
    readonly lblSituacaoHospedagem: MouraLabel;
    readonly lblSituacaoPagamento: MouraLabel;
    readonly lblModalEsperaInformacoes: MouraLabel;
    readonly btnHospedagem: MouraButton;
    readonly btnEmail: MouraButton;
    readonly btnEnviarEmailPagamento: MouraButton;
    readonly btnEsperaReserva: MouraButton;
    readonly btnCancelarReserva: MouraButton;
    readonly cboBaia: MouraComboBox;
    readonly cboTamanhoBaia: MouraComboBox;
    readonly btnModalEsperaConfirmar: MouraButton;
    readonly btnModalEsperaCancelar: MouraButton;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly txtLocalHospedagem: MouraTextBoxProcura;
    Baias: SiSMoura.Core.Entity.Animais_Hospedagem_Baia[];
    readonly optTipoHospedagem: MouraRadioButtonList;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly txtFuncionario: MouraTextBoxProcura;
    readonly dlgAdicionarEspera: MouraModal;
    readonly dlgMotivoCancelamento: MouraModal;
    readonly txtMdlMotivoCanc: MouraTextBox;
    readonly btnMldMotivoCancConfirmar: MouraButton;
    readonly btnMldMotivoCancCancelar: MouraButton;
    readonly lstSemana: MouraCheckBoxList;
    readonly grdCheckListItens: MouraGridViewJS;
    readonly txtCheckListProcura: MouraTextBoxProcura;
    readonly txtProfissionalCheckList: MouraTextBoxProcura;
    readonly txtCheckList: MouraTextBox;
    readonly btnImprimirCheckList: MouraButton;
    readonly sgnCheckList: MouraSignaturePad;
    readonly btnAssinatura: MouraButton;
    readonly tab: MouraTabPanel;
    readonly dlgIndicarParceiro: MouraModal;
    readonly gridIndicacao: MouraGridViewJS;
    readonly btnDlgIndicacaoConfirmar: MouraButton;
    readonly btnDlgIndicacaoCancelar: MouraButton;
    readonly lblModalIndicacaoInformacoes: MouraLabel;
    readonly btnIndicarParceiro: MouraButton;
    readonly lblQtdeDias: MouraLabel;
    readonly lblDias2: MouraLabel;
    readonly cboServicoDiaria: MouraComboBox;
    readonly btnRecalcularDiarias: MouraButton;
    readonly grdDiarias: MouraGridViewJSEditavel;
    readonly grdAtendimentos: MouraGridViewJS;
    Atendimentos: any[];
    ServicosDiarias: SiSMoura.Core.Entity.Servico[];
    Diarias: SiSMoura.Core.Entity.Animais_Hospedagem_Servico[];
    Diaria: SiSMoura.Core.Entity.Animais_Hospedagem_Servico;
    DiasSemana: string[];
    readonly cboMeioPagamento: MouraComboBox;
    AtendimentoExcluido: any[];
    DiariasExcluidas: SiSMoura.Core.Entity.Animais_Hospedagem_Servico[];
    DiariaCalculada: SiSMoura.Core.Entity.Animais_Hospedagem_Servico;
    readonly txtDescontoDiaria: MouraTextBox;
    readonly txtDescontoPorcentDiaria: MouraTextBox;
    protected Init(): void;
    protected OnSelecionouAtendimentoGrid(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnPesquisandoProprietario(s: any, e: MouraTextBoxProcuraPesquisandoEventArgs): void;
    protected OnLstSemanaItemChanged(s: any, e: any): void;
    private OnMsgBoxAlterandoDiasSemana;
    private LimparDiarias;
    protected OnTxtDataEntradaLostFocus(): void;
    protected OnTxtDataSaidaLostFocus(): void;
    protected VerificarDatas(isDataInicial: boolean): boolean;
    protected OnCboBaiaGotFocus(s: any, e: any): void;
    protected OnCboMeioPagamento_ValueChange(s: any, e: any): void;
    protected OnCboServicoDiaria_SelectedIndexChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboBaia_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected PreencherBaias(codLocal: number): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Animais_Hospedagem_Reserva): void;
    protected PreencherInformacoesTela(entidade: SiSMoura.Core.Entity.Animais_Hospedagem_Reserva): void;
    private AtualizarLabelSituacao;
    private AtualizarLabelSituacaoPagamento;
    protected OnDepoisGravar(): boolean;
    protected OnMsgBoxEnviarEmailReserva(resultado: MsgBoxResultEventArgs): void;
    OnPageLoad(): void;
    private PreencherReserva;
    protected OnPesquisandoAnimal(s: any, e: MouraTextBoxProcuraPesquisandoEventArgs): void;
    protected OnMudouOptTipoHospedagem(s: any, e: MouraEventArgs): void;
    private IniciarDataTipoHospedagem;
    protected OnDepoisProcuraLocal(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    private OnbtnCancelarReserva;
    protected OnMsgBoxCancelarReserva(resultado: MsgBoxResultEventArgs): void;
    private OnbtnEmail;
    private OnbtnEnviarEmailPagamento;
    private OnBtnHospedagemClick;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Hospedagem_Reserva): void;
    protected onMudouEmpresa(s: any, e: any): void;
    private VerificarVisibilidadeAbas;
    protected OnAntesDeletar(): boolean;
    protected OnAntesGravar(): boolean;
    private EnviarEmailHospedagem;
    private EnviarEmailPagamento;
    private OnBtnEsperaReservaClick;
    private OnConfirmarEsperaReserva;
    private OnCancelarCriarEsperaReserva;
    protected OnMsBoxVisualizarEspera(resultado: MsgBoxResultEventArgs): void;
    private onBtnMdlMotivoCancConfirmar;
    private onBtnMdlMotivoCancCancelar;
    protected OnTxtCheckListProcuraProcurou(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnSalvouAssinatura(s: any, e: any): void;
    protected OnClickAssinatura(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirChecklist(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private ExibirHoteisParceiros;
    private onBtnDlgIndicacaoConfirmar;
    private onBtnDlgIndicacaoCancelar;
    private onBtnIndicarParceiro;
    private EnviarEmailIndicacaoParceiro;
    private GetDataHoraEntrada;
    private GetDataHoraSaida;
    protected CarregarServicosVinculadosBaias(): void;
    private PreencherServicosHospedagem;
    protected onRecalcularDias(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private isReservaFinalizada;
    private RecalcularDiariasHotel;
    private RecalcularDiariasDayCare;
    private GetNumeroDiariasGerar;
    protected validarCalculoDias(): boolean;
    private podeAdicionarDiaria;
    protected OnValidandoAlteracaoDiaria(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    private IniciarValoresAutomaticosDiaria;
    protected OnSetouItemDiaria(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAlterandoDiaria(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    private retornoComplementosItemServico;
    private getRetornoComplementoItemServico;
    private SetHoraData;
    private AtualizarLabelQtdeDias;
    private GetNumeroDiariasGerarDaycare;
    private TratarEntidadeAntesGravar;
    protected PreencherItens(entidade: SiSMoura.Core.Entity.Animais_Hospedagem_Reserva): boolean;
    private RetornarDiasSemana;
    private HabilitarDesabilitarControles;
    private HabilitarDesabilitarCamposAvaliacaoFisica;
    private validarInformacoesAntesGravar;
    private OnValidandoInformacoesReserva;
    private getQuantidadeDias;
    protected OnRespostaAvaliacaoComportamental(resultado: MsgBoxResultEventArgs): void;
    private calcularUltimoDiaMensalidadeDaycare;
    private calcularDescontoPDiaria;
    private calcularDescontoDiaria;
    private onTxtDescontoDiariaLostFocus;
    private onTxtDescontoPorcentDiaria;
    private verificarDescontoMaxPermitido;
    private LimparCamposDesconto;
    private alterarModoPagamento;
    private verificarStatusAtendimento;
    private podeAlterarMeioPagamento;
}
declare var c_HosRes_Angular: C_HosRes_Angular;
//# sourceMappingURL=C_HosRes_Angular.d.ts.map