interface DadosAdicionaisPET {
    vetResponsavel: string;
    dddFoneVetResponsavel: string;
    foneVetResponsavel: string;
    carteiraVacinacao: string;
    restricaoAlimentar: string;
    restricaoAlimentarTexto: string;
    racaoPET: string;
    quantidadeRacao: string;
    atestado: string;
    castrado: string;
}
declare class C_HosCad_Angular extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Hospedagem> {
    private PATH_DOCUMENTOS_HOSPEDAGEM;
    private DataRealizandoCheckout;
    private ExecutarCheckoutDepoisGravar;
    private validouInformacoesHospedagem;
    private enviarEmailCheckout;
    private verificadoAutorizacaoDescontoHospedagem;
    readonly ConfiguracoesPET: any;
    readonly GetHorarioCheckout: string;
    readonly GetProfissionalDiaria: SiSMoura.Core.Entity.Animais_Veterinario;
    readonly Atendimento_Bloquear_Editar_ValorServico: boolean;
    readonly tab: MouraTabPanel;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly hdnConfigPET: HTMLInputElement;
    readonly hdnReserva: HTMLInputElement;
    readonly hdnServicosHospedagem: HTMLInputElement;
    readonly lblDataCadastro: MouraLabel;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly lblStatus: MouraLabel;
    readonly lblQtdeDias: MouraLabel;
    readonly lblDias2: MouraLabel;
    readonly btnVacinas: MouraButton;
    readonly hdnAgendamentoVisible: HTMLInputElement;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly txtDataEntrada: MouraTextBoxData;
    readonly txtHoraEntrada: MouraTextBoxHora;
    readonly txtUsuarioEntrada: MouraTextBoxProcura;
    readonly txtLocalHospedagem: MouraTextBoxProcura;
    readonly cboBaia: MouraComboBox;
    Baias: SiSMoura.Core.Entity.Animais_Hospedagem_Baia[];
    readonly txtObservacao: MouraTextBox;
    readonly txtDataSaida: MouraTextBoxData;
    readonly cboServicoDiaria: MouraComboBox;
    readonly btnRecalcularDiarias: MouraButton;
    readonly btnAdicionarDiaria: MouraButton;
    readonly grdDiarias: MouraGridViewJSEditavel;
    readonly txtServico: MouraTextBoxProcura;
    readonly btnAnexo: MouraButton;
    readonly btnEmail: MouraButton;
    readonly dlgAnexo: MouraModalAnexo;
    readonly dlgMotivoCortesia: MouraModal;
    readonly EnviarEmail: MouraEmail;
    readonly cboListaPreco: MouraComboBox;
    readonly txtValorUnitario: MouraTextBox;
    readonly txtQuantidadeServico: MouraTextBox;
    readonly txtDesconto: MouraTextBox;
    readonly txtDescontoPorcent: MouraTextBox;
    readonly lblTotal: MouraTextBox;
    readonly txtObservacaoServico: MouraTextBox;
    readonly chkConcluido: MouraCheckBox;
    readonly txtProfissional: MouraTextBoxProcura;
    readonly btnAdicionar: MouraButton;
    readonly btnNovoServico: MouraButton;
    readonly btnReplicar: MouraButton;
    readonly grdReplicarServicos: MouraGridViewJS;
    readonly dlgReplicar: MouraModal;
    readonly dlgMotivoCancelamento: MouraModal;
    readonly txtMdlMotivoCanc: MouraTextBox;
    readonly txtMotivoCortesia: MouraTextBox;
    readonly chkCortesia: MouraCheckBox;
    readonly btnOKCortesia: MouraButton;
    readonly btnCancelarCortesia: MouraButton;
    readonly btnMldMotivoCancConfirmar: MouraButton;
    readonly btnMldMotivoCancCancelar: MouraButton;
    readonly rblTipoIntervalo: MouraRadioButtonList;
    readonly optTipoHospedagem: MouraRadioButtonList;
    readonly txtIntervaloReplicacoes: MouraTextBox;
    readonly txtQtdeReplicacoes: MouraTextBox;
    readonly btnReplicarServicos: MouraButton;
    readonly btnCancelarReplicar: MouraButton;
    readonly grdServicos: MouraGridViewJSEditavel;
    readonly grdProdutosConsumidos: MouraGridViewJSEditavel;
    readonly txtDataCheckout: MouraTextBoxData;
    readonly txtHoraCheckout: MouraTextBoxHora;
    readonly cboServicoCheckout: MouraComboBox;
    readonly lblInfoExcedido: MouraLabel;
    readonly txtFuncionarioCheckout: MouraTextBox;
    readonly txtProduto: MouraTextBoxProcura;
    readonly cboListaPrecoProduto: MouraComboBox;
    readonly txtValorUnitarioProduto: MouraTextBox;
    readonly txtQuantidadeProduto: MouraTextBox;
    readonly txtDescontoProduto: MouraTextBox;
    readonly txtDescontoPorcentProduto: MouraTextBox;
    readonly lblTotalProduto: MouraTextBox;
    readonly txtDataProduto: MouraTextBoxData;
    readonly txtHoraProduto: MouraTextBoxHora;
    readonly txtProfissionalProduto: MouraTextBoxProcura;
    readonly txtObservacaoProduto: MouraTextBox;
    readonly chkCobrado: MouraCheckBox;
    readonly btnAdicionarProduto: MouraButton;
    readonly btnReplicarProduto: MouraButton;
    readonly btnNovoProduto: MouraButton;
    readonly grdProdutos: MouraGridViewJSEditavel;
    readonly dlgReplicarProduto: MouraModal;
    readonly optTipoIntervaloProduto: MouraRadioButtonList;
    readonly txtIntervaloReplicacoesProduto: MouraTextBox;
    readonly txtQtdeReplicacoesProduto: MouraTextBox;
    readonly grdReplicarProdutos: MouraGridViewJS;
    readonly btnModalReplicarProdutos: MouraButton;
    readonly btnModalCancelarReplicarProdutos: MouraButton;
    readonly grdAgendamentos: MouraGridViewJS;
    readonly btnVoltarAgendamento: MouraButton;
    Diarias: SiSMoura.Core.Entity.Animais_Hospedagem_Servico[];
    Diaria: SiSMoura.Core.Entity.Animais_Hospedagem_Servico;
    Servicos: SiSMoura.Core.Entity.Animais_Hospedagem_Servico[];
    Servico: SiSMoura.Core.Entity.Animais_Hospedagem_Servico;
    ProdutosConsumidos: SiSMoura.Core.Entity.Animais_Hospedagem_Produto_Petz[];
    ProdutoConsumido: SiSMoura.Core.Entity.Animais_Hospedagem_Produto_Petz;
    readonly txtValorUnitarioProdutoConsumido: MouraTextBox;
    readonly txtQuantidadeProdutoConsumido: MouraTextBox;
    Produto: SiSMoura.Core.Entity.Animais_Hospedagem_Produto_Petz;
    ServicosDiarias: SiSMoura.Core.Entity.Servico[];
    ServicosCarregadosBaia: SiSMoura.Core.Entity.Servico[];
    Produtos: SiSMoura.Core.Entity.Animais_Hospedagem_Produto[];
    Atendimentos: any[];
    ListasPrecosServicos: any[];
    ListasPrecosProdutos: any[];
    readonly grdAtendimentos: MouraGridViewJS;
    readonly btnConsultas: MouraButton;
    readonly btnCancelarHospedagem: MouraButton;
    readonly btnCheckout: MouraButton;
    readonly grdCheckListItens: MouraGridViewJS;
    readonly txtCheckListProcura: MouraTextBoxProcura;
    readonly txtProfissionalCheckList: MouraTextBoxProcura;
    readonly txtCheckList: MouraTextBox;
    readonly btnImprimirCheckList: MouraButton;
    readonly sgnCheckList: MouraSignaturePad;
    readonly btnAssinatura: MouraButton;
    readonly lstSemana: MouraCheckBoxList;
    DiasSemana: string[];
    readonly tabAvaliacoes: MouraTabPanel;
    readonly txtVeterinario: MouraTextBoxProcura;
    readonly txtAssunto: MouraTextBoxProcura;
    readonly cboModelo: MouraComboBox;
    readonly txtDataRetorno: MouraTextBoxData;
    readonly txtFichaClinica: MouraTextBoxProcura;
    readonly txtDescricaoFichaClinica: MouraTextBox;
    readonly txtDiagnostico: MouraTextBox;
    readonly txtExameFisico: MouraTextBoxProcura;
    readonly txtDescricaoExameFisico: MouraTextBox;
    readonly txtAnamnese: MouraTextBoxProcura;
    readonly txtDescricaoAnamnese: MouraTextBox;
    readonly btnSalvarConsulta: MouraButton;
    readonly mdlAdicDiariaDaycare: MouraModal;
    readonly cboTipoDiaria: MouraComboBox;
    readonly txtDataDiaria: MouraTextBoxData;
    readonly btnAdicionarDiariaAvulsa: MouraButton;
    readonly dlgAdicionalCheckout: MouraModal;
    readonly cboOpcaoAdicaoHoraCheckout: MouraComboBox;
    readonly btnConfirmarAcaoCheckout: MouraButton;
    readonly btnCancelarAcaoCheckout: MouraButton;
    readonly cboServicoAcaoCheckout: MouraComboBox;
    readonly lblValorAdicional: MouraLabel;
    readonly btnImprimirFicha: MouraButton;
    DiariaCalculada: SiSMoura.Core.Entity.Animais_Hospedagem_Servico;
    readonly txtDescontoDiaria: MouraTextBox;
    readonly txtDescontoPorcentDiaria: MouraTextBox;
    DadosAdicionaisPET: DadosAdicionaisPET;
    readonly txtVetRespPet: MouraTextBox;
    readonly txtFoneVetRespPet: MouraTextBoxTelefone;
    readonly cboRestricaoAlimentar: MouraComboBox;
    readonly txtRestricaoAlimentar: MouraTextBox;
    readonly txtRacaoPet: MouraTextBox;
    readonly txtQuantidadeRacao: MouraTextBox;
    readonly cboCarteiraVacinacao: MouraComboBox;
    readonly cboAtestado: MouraComboBox;
    readonly cboCastrado: MouraComboBox;
    readonly txtUsuarioAvaliacao: MouraTextBoxProcura;
    readonly cboFichaAvaliacao: MouraComboBox;
    readonly cboQuantidadeMesesDaycare: MouraComboBox;
    readonly grdFichaAvaliacao: MouraGridViewJS;
    readonly grdAvaliacoesRealizadas: MouraGridViewJS;
    readonly grdVisualizarFichaAval: MouraGridViewJS;
    readonly txtDataAvaliacao: MouraTextBoxData;
    readonly txtObservacaoFicha: MouraTextBox;
    readonly txtObsFichaVisualizar: MouraTextBox;
    readonly txtHoraAvaliacao: MouraTextBoxHora;
    FichasAvaliacao: SiSMoura.Core.Entity.Animais_Hospedagem_Ficha_Avaliacao[];
    readonly btnSalvarFicha: MouraButton;
    readonly mdlVisualizarFichaAval: MouraModal;
    protected OnAntesBuscarExistente(): void;
    protected Init(): void;
    protected OnLstSemanaItemChanged(s: any, e: any): void;
    private OnDepoisProcurouAnimal;
    private OnMsgBoxAlterandoDiasSemana;
    protected OnTxtDataEntradaLostFocus(): void;
    protected OnTxtDataSaidaLostFocus(): void;
    private AtualizarLabelQtdeDias;
    protected VerificarDatas(): boolean;
    private validarDataDaycare;
    private validarDataHotel;
    protected OnTxtCheckListProcuraProcurou(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnSalvouAssinatura(s: any, e: any): void;
    protected OnClickAssinatura(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickImprimirChecklist(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnMudouOptTipoHospedagem(s: any, e: MouraEventArgs): void;
    protected OnClickConsultas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnCancelarHospedagem(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    private onBtnMdlMotivoCancConfirmar;
    private onBtnMdlMotivoCancCancelar;
    protected CarregarServicosVinculadosBaias(): void;
    private PreencherServicosHospedagem;
    protected OnPesquisandoAnimal(s: any, e: MouraTextBoxProcuraPesquisandoEventArgs): void;
    protected OnSelecionouAtendimentoGrid(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    private OnValidandoProdutoGrade;
    private GetDataHoraEntrada;
    private GetDataHoraPrevisaoSaida;
    private SetHoraData;
    OnPageLoad(): void;
    protected OnExcluindoServicoGrade(s: any, e: MouraGridViewJSItemCancelavelEventArgs): void;
    protected OnExcluindoProdutoGrade(s: any, e: MouraGridViewJSItemCancelavelEventArgs): void;
    protected OnMsgBoxEcluirServicoGrade(resultado: MsgBoxResultEventArgs): void;
    protected OnMsgBoxEcluirProdutoGrade(resultado: MsgBoxResultEventArgs): void;
    private ValidarAdicionarServico;
    protected LimparCamposServico(): void;
    private LerParametrosURL;
    protected onMudouEmpresa(s: any, e: any): void;
    protected OnDepoisProcuraLocal(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected onAdicionarDiariaAvulsaDaycare(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected onAdicionarDiaria(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private adicionarDiariaHotel;
    private adicionarDiariaDayCare;
    private podeAdicionarDiaria;
    private GetNumeroDiariasGerar;
    private GetNumeroDiariasGerarDaycare;
    protected onRecalcularDias(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private RecalcularDiariasHotel;
    private RecalcularDiariasDayCare;
    protected validarAdicionarDiaria(): boolean;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Hospedagem): void;
    private LimparCamposProdutos;
    protected OnAntesGravar(): boolean;
    private LimparDiarias;
    private TratarEntidadeAntesGravar;
    private RetornarDiasSemana;
    protected OnMudouCodigo(s: any, e: any): void;
    protected OnDepoisBuscarExistente(Entidade: SiSMoura.Core.Entity.Animais_Hospedagem): void;
    protected OnDepoisGravar(): boolean;
    protected OnAntesSetEntidade(entidade: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Animais_Hospedagem>): void;
    protected OnGravouSucesso(s: any, e: MouraGravouSucessoEventArgs): void;
    protected OnExcluiuSucesso(s: any, e: any): void;
    protected PreencherInformacoesTela(entidade: SiSMoura.Core.Entity.Animais_Hospedagem): void;
    protected OnCboListaPreco_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboListaPrecoProduto_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboListaPrecoGotFocus(s: any, e: any): void;
    protected OnCboListaPrecoProdutoGotFocus(s: any, e: any): void;
    protected CalcularTotalServico(): void;
    protected OnTxtServicoProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnTxtDescontoProdutoChange(): void;
    protected OnTxtDescontoServicoChange(): void;
    protected OnTxtDescontoPorcentProdutoChange(): void;
    protected OnTxtDescontoPorcentServicoChange(): void;
    protected OnTxtQuantidadeServicoChange(): void;
    protected txtQuantidadeProdutoChange(): void;
    private validarDesconto;
    protected ReplicarServicos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected ReplicarProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected OnCancelarReplicar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnReplicarServicos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CalcularTotalProduto(): void;
    private LimparModalReplicarServico;
    private LimparModalReplicarProduto;
    protected OnTxtProdutoProcurou(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected OnAdicionarProduto(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnReplicarProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnCancelarReplicacaoProdutos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private ValidarAdicionarProduto;
    private VerificarPagamentoHospedagem;
    private FinalizarHotelDaycare;
    protected VerificarPermissaoCortesia(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnBtnOKCortesiaClick(s: MouraButton, e: MouraClickEventArgs): void;
    protected OnBtnCancelarCortesiaClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private GetQuantidadeHorasExcedidas;
    private FinalizarHotel;
    private ValidarFinalizacaoHotelDaycare;
    private CheckoutHospedagem;
    private FinalizarDayCare;
    private ValidacoesCheckout;
    private ValidacoesFinalizacaoDaycare;
    protected OnMesageBoxCheckoutAposDataPrevista(resultado: MsgBoxResultEventArgs): void;
    private AdicionarDiariaCheckout;
    protected CheckOut(): void;
    private AtualizarLabelStatus;
    private OnBtnAnexoClick;
    private OnBtnFichaClick;
    private OnBtnEmailClick;
    protected OnAtualizandoPresenca(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickBotaoLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnSelecinouOpcaoZanthus(e: MsgBoxResultEventArgs): void;
    protected OnCboBaiaGotFocus(s: any, e: any): void;
    protected OnCboBaia_comboBoxChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected PreencherBaias(codLocal: number): void;
    private MostrarOcultarCamposAvaliacao;
    protected OnAntesAbrirProcuraVeterinario(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnProcurouFichaClinica(s: any, e: any): void;
    protected OnProcurouExameFisico(s: any, e: any): void;
    protected OnProcurouAnamnese(s: any, e: any): void;
    OnBtnSalvarConsulta(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private ValidarCamposAvaliacaoAnimal;
    private LimparCamposAvaliacaoAnimal;
    protected habilitar(flag: boolean): void;
    private habilitarDesabilitarGridDiarias;
    private HabilitarDesabilitarCamposAvaliacaoFisica;
    private habilitarCamposDadosAdicionaisPET;
    protected OnMsgBoxAlterarBaia(resultado: MsgBoxResultEventArgs): void;
    private OnSelecionouLinhaDiaria;
    private IsHospedagemFinalizada;
    protected OnValidandoAlteracaoDiaria(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    private IniciarValoresAutomaticosDiaria;
    protected OnSetouItemDiaria(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAlterandoDiaria(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    private retornoComplementosItemServico;
    private getRetornoComplementoItemServico;
    protected OnSetouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private IniciarValoresAutomaticosServico;
    protected OnLimpouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAdiciouItemServico(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private perguntouAdicionarServicoDuplicado;
    private perguntouAdicionarProdutoDuplicado;
    private mostrouParticipantes;
    private mostrouConsulta;
    private mostrouFuncao;
    protected OnValidandoItemServico(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected AlterarCamposAtendimentoPago(isAtendimentopago: boolean): void;
    protected AlterarColunasEditaveisVenda(editavel: boolean): void;
    protected OnSelecionouOpcaoInserirServico(e: MsgBoxResultEventArgs): void;
    protected VerificarFuncaoAdmBloquearRetorno(retorno: MouraFuncoesAdministrativasRetorno): void;
    protected OnExcluindoItemServico(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnAlterandoItem(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnSetouItemProdutoConsumido(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    private IniciarValoresAutomaticosProdutosConsumidos;
    protected OnLimpouItemProdutoConsumido(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnAdiciouItemProdutoConsumido(s: any, e: MouraGridViewJSEditavelItemEventArgs): void;
    protected OnValidandoItemProdutoConsumido(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnExcluindoItemProdutoConsumido(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnMsgBoxEcluirProdutoConsumidoGrade(resultado: MsgBoxResultEventArgs): void;
    protected OnAlterandoItemProdutoConsumido(s: any, e: MouraGridViewJSEditavelItemValidandoEventArgs): void;
    protected OnTxtValorProdutoConsumidoChange(): void;
    protected txtQuantidadeProdutoConsumidoChange(): void;
    protected CalcularTotalProdutoConsumido(): void;
    private validarInformacoesAntesGravar;
    private OnValidandoInformacoesHospedagem;
    protected OnRespostaAvaliacaoComportamental(resultado: MsgBoxResultEventArgs): void;
    private alterarCamposTipoHospedagem;
    private calcularUltimoDiaMensalidadeDaycare;
    private mudarTipoDiaria;
    protected OnCboTipoDiariaChange(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    private podeAdicionarDiariaAvulsa;
    protected OnCboServicoAcaoCheckoutChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    private AtualizarCalculoHorasAdicionais;
    protected OnCboOpcaoAdicaoHoraCheckoutChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    OnBtnConfirmarAcaoCheckoutClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    OnBtnCancelarAcaoCheckoutClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private EnviarEmailHospedagem;
    private calcularDescontoPDiaria;
    private calcularDescontoDiaria;
    private onTxtDescontoDiariaLostFocus;
    private onTxtDescontoPorcentDiaria;
    private verificarDescontoMaxPermitido;
    protected OnCboServicoDiaria_SelectedIndexChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected OnCboQuantidadeMesesDaycare_SelectedIndexChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    private LimparCamposDesconto;
    protected OnCboFichaAvaliacaoChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
    protected onBtnSalvarFicha(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    private limparCamposFichaAvaliacao;
    private habilitarCamposFichaAvaliacao;
    private OnExcluindoFichaAvaliacao;
    private OnExcluirFichaAvaliacao;
    private OnSelecionouLinhaFichaAvaliacao;
    protected OnCboRestricaoAlimentar_SelectedIndexChanged(s: DevExpress.Web.Scripts.ASPxClientComboBox, e: DevExpress.Web.Scripts.ASPxClientEventArgs): void;
}
declare var c_HosCad_Angular: C_HosCad_Angular;
//# sourceMappingURL=C_HosCad_Angular.d.ts.map