declare class C_AtmExa extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Atendimento> {
    private PATH_DOCUMENTOS;
    readonly ProprietarioCadastrado: boolean;
    readonly AnimalCadastrado: boolean;
    Animal: SiSMoura.Core.Entity.Animais_Cadastro;
    Proprietario: SiSMoura.Core.Entity.Pessoa;
    ListaResultadosRecebidos: SiSMoura.Core.Entity.ExamesAtendimento[];
    ListaResultadosAlterados: SiSMoura.Core.Entity.ExamesAtendimento[];
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly txtClinica: MouraTextBoxProcura;
    readonly txtObservacaoCodigo: MouraTextBoxProcura;
    readonly grdResultado: MouraGridViewJS;
    readonly grdExames: MouraGridViewJS;
    readonly btnOkAnimal: MouraButton;
    readonly btnAnimal: MouraButton;
    readonly btnCancelarAnimal: MouraButton;
    readonly btnAnexo: MouraButton;
    readonly btnEmail: MouraButton;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly Tab: MouraTabPanel;
    readonly cboModelo: MouraComboBoxEmpresa;
    readonly dlgDadosAnimal: MouraModal;
    readonly dlgAnexo: MouraModalAnexo;
    readonly EnviarEmail: MouraEmail;
    readonly htmlEditor: MouraHTMLEditor;
    readonly btnImprimirGenerico: MouraButton;
    readonly btnImprimir: MouraButton;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnGrdgrdExamesSelecionouLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected CarregarExame(codExame: number): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Atendimento): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Animais_Atendimento): void;
    protected OnAntesSetEntidade(eventArg: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Animais_Atendimento>): void;
    protected OnAntesGravar(): boolean;
    private GetExames;
    private OnBtnOkAnimalClick;
    private OnBtnImprimirClick;
    private OnBtnImprimirGenericoClick;
    private OnBtnAnimalClick;
    private OnBtnCancelarAnimalClick;
    private OnBtnEmailClick;
    private OnBtnAnexoClick;
    imprimirExame(generico: boolean): void;
    private LimparDadosAnimais;
    private OnTxtObservacaoDescricaoPesquisou;
    private OnTxtClinicaPesquisou;
    private OnGrdResultadoValidandoItem;
    private atualizarGrids;
    private filtrarGridResultados;
    private getListaExames;
    private atualizarProprietario;
    private atualizarAnimal;
    private verificarProprietarioObrigatorio;
    private verificarAnimalObrigatorio;
    private inicializarAtendimentoEntity;
    private inicializarPessoaEntity;
    private inicializarAnimalEntity;
    private CalcularFormulas;
}
declare var c_AtmExa: C_AtmExa;
//# sourceMappingURL=C_AtmExa.d.ts.map