declare class C_AtmCon extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Veterinaria> {
    private PATH_DOCUMENTOS;
    ExamesSolicitados: SiSMoura.Core.Entity.AnimaisExameRetorno[];
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtPet: MouraTextBoxProcuraProprietarioAnimal;
    readonly grdInternacao: MouraGridViewJS;
    readonly btnNovainternacao: MouraButton;
    readonly btnVisualizarProtocolo: MouraButton;
    readonly btnSolicitarExames: MouraButton;
    readonly btnAtendimento: MouraButton;
    readonly btnAtendimentoContinuo: MouraButton;
    readonly btnVacinas: MouraButton;
    readonly btnPeso: MouraButton;
    readonly btnCarregarHistorico: MouraButton;
    readonly txtVeterinario: MouraTextBoxProcura;
    readonly txtHistorico: MouraTextBox;
    readonly txtReceita: MouraTextBoxProcura;
    readonly txtDescricaoReceita: MouraTextBox;
    readonly txtAnamnese: MouraTextBoxProcura;
    readonly txtDescricaoAnamnese: MouraTextBox;
    readonly txtExameFisico: MouraTextBoxProcura;
    readonly txtDescricaoExameFisico: MouraTextBox;
    readonly btnHistoricoImprimirMatricial: MouraButton;
    readonly btnHistoricoVisualizarWord: MouraButton;
    readonly btnImprimir: MouraButton;
    readonly btnAnexo: MouraButton;
    readonly grdPesos: MouraGridViewJS;
    readonly grdVacinasAgendadas: MouraGridViewJS;
    readonly grdVacinasAplicadas: MouraGridViewJS;
    readonly grdConsultas: MouraGridViewJS;
    readonly lblEndereco: MouraLabel;
    readonly lblFone: MouraLabel;
    readonly lblComplemento: MouraLabel;
    readonly lblEspecie: MouraLabel;
    readonly lblRaca: MouraLabel;
    readonly lblIdadeSexo: MouraLabel;
    readonly lblObsServico: MouraLabel;
    readonly lblCarteirinha: MouraLabel;
    readonly lblChip: MouraLabel;
    readonly cboModelo: MouraComboBox;
    readonly dlgAnexo: MouraModalAnexo;
    readonly txtHora: MouraTextBoxHora;
    readonly txtData: MouraTextBoxData;
    readonly mdDadosConsulta: MouraModal;
    readonly mdSolicitarExames: MouraModal;
    readonly btnFecharCons: MouraButton;
    readonly tbConsulta: MouraTabPanel;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly btnAbrirExames: MouraButton;
    readonly btnFecharExames: MouraButton;
    readonly txtLaboratorio: MouraTextBoxProcura;
    readonly txtSolicitante: MouraTextBoxProcura;
    readonly txtTipoExame: MouraTextBoxProcura;
    readonly btnAdicionarExame: MouraButton;
    readonly grdExamesSolicitados: MouraGridViewJS;
    readonly txtStatusExame: MouraTextBoxProcura;
    readonly txtResultadoExame: MouraTextBox;
    readonly txtCodigoTratamento: MouraTextBoxProcura;
    readonly txtTratamento: MouraTextBox;
    readonly txtFichaClinica: MouraTextBoxProcura;
    readonly txtDescricaoFichaClinica: MouraTextBox;
    readonly tab: MouraTabPanel;
    readonly mdAnexo: MouraModalAnexo;
    readonly txtDiagnostico: MouraTextBox;
    readonly txtCID: MouraTextBoxProcura;
    protected Init(): void;
    private pathCID;
    protected OntxtCidProcurou(s: any, e: any): void;
    protected OnSelecionouOpcaoCID(e: MsgBoxResultEventArgs): void;
    protected OnMudouData(): void;
    protected AlterarEntidadeData(): void;
    protected OnTxtDataChanged(): void;
    protected OnTxtHoraChanged(): void;
    OnPageLoad(): void;
    protected OnGrdExamesSolicitadosSelecionouLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnGrdExamesSolicitadosExcluirLinha(s: any, e: MouraGridViewJSItemCancelavelEventArgs): void;
    protected OnGrdConsultasSelecionouLinha(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnAntesSetEntidade(eventArg: MouraEntidadeCancelavel<SiSMoura.Core.Entity.Animais_Veterinaria>): void;
    private perguntarProtocolo;
    protected OnAntesBuscarExistente(): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Animais_Veterinaria): void;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Animais_Veterinaria): void;
    private LimparSolicitarExames;
    protected OnDepoisGravar(): boolean;
    protected OnTxtPetProcurouProprietario(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnTxtPetProcurouAnimal(s: MouraTextBoxProcuraProprietarioAnimal, e: MouraEventArgs): void;
    protected OnClickNovaInternacao(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickPesos(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAtendimento(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickAtendimentoContinuo(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoAbrirExames(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoFecharExames(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickBotaoAdicionarExame(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickProtocolo(s: any, e: MouraClickEventArgs): void;
    protected OnClickVacinas(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickSolicitarExames(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnHistoricoImprimirMatricialClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnAnexoClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnImprimirClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnBtnHistoricoVisualizarWordClick(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCarregarHistorico(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnProcurouReceita(s: any, e: any): void;
    protected OnProcurouAnamnese(s: any, e: any): void;
    protected OnProcurouTratamento(s: any, e: any): void;
    protected OnProcurouFichaClinica(s: any, e: any): void;
    protected OnProcurouExameFisico(s: any, e: any): void;
    protected OnProcurouTipoExame(s: any, e: any): void;
    protected OnClickFecharCons(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnAntesGravar(): boolean;
    protected OnAntesAbrirProcuraVeterinario(s: any, e: MouraTextBoxProcuraAntesAbrirProcuraEventArgs): void;
    protected OnClickImprimirInternacao(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
}
declare var c_AtmCon: C_AtmCon;
//# sourceMappingURL=C_AtmCon.d.ts.map