declare class BIVenda extends MouraPageRelacaoAngular {
    private BIVENDA;
    private BICOMPRAS;
    private BICONTASRECEBER;
    private BICONTASRECEBIDAS;
    private BICONTASPAGAR;
    private BICONTASPAGAS;
    private BIATENDIMENTOPET;
    readonly AccordionFiltros: MouraAccordion;
    readonly txtPeriodo: MouraTextBoxPeriodo;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly grdBI: MouraPivotGridJS;
    readonly cboTipoBI: MouraComboBox;
    readonly mdVenda: MouraModal;
    readonly grdVenda: MouraGridViewJS;
    readonly mdCompra: MouraModal;
    readonly grdCompra: MouraGridViewJS;
    readonly mdAtendimento: MouraModal;
    readonly grdAtendimento: MouraGridViewJS;
    readonly mdReceber: MouraModal;
    readonly grdReceber: MouraGridViewJS;
    readonly mdRecebido: MouraModal;
    readonly grdRecebido: MouraGridViewJS;
    readonly mdPagar: MouraModal;
    readonly grdPagar: MouraGridViewJS;
    readonly mdPago: MouraModal;
    readonly grdPago: MouraGridViewJS;
    OnPageLoad(): void;
    protected Init(): void;
    protected OnAlterouTipoBI(s: any, e: any): void;
    LimparCampos(): void;
    PreencherGrade(): void;
    protected CriarColunasGrade(): void;
    protected CriarColunasVenda(): void;
    protected CriarColunasCompras(): void;
    protected CriarColunasContasReceber(): void;
    protected CriarColunasContasRecebidas(): void;
    protected CriarColunasContasAPagar(): void;
    protected CriarColunasContasPagas(): void;
    protected CriarColunasAtendimentoPet(): void;
    protected gerarDados(): void;
    protected OnClicGerar(): void;
    private dadosGrade;
    protected DownloadDados(idLista: string, paginas: number, paginaAtual: number): void;
    private setDataSourceGridBI;
    private OnCellClick;
    protected SelecionouLinhaGrdVenda(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnFechouModalDetalhe(s: any, e: any): void;
    protected SelecionouLinhaGrdCompra(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected SelecionouLinhaGrdAtendimento(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected SelecionouLinhaGrdReceber(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected SelecionouLinhaGrdRecebidos(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected SelecionouLinhaGrdPagar(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected SelecionouLinhaGrdPago(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
}
declare var bIVenda: BIVenda;
//# sourceMappingURL=BIVenda.d.ts.map