declare class G_SPED_Angular extends MouraPageAngular {
    readonly grdInventario: MouraGridViewJS;
    readonly grdCartao: MouraGridViewJSEditavel;
    readonly txtVencimentoICMS: MouraTextBoxData;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboCodigoReceita: MouraComboBox;
    readonly cboPerfil: MouraComboBox;
    readonly cboTipoArq: MouraComboBox;
    readonly cboMotivoInventario: MouraComboBox;
    readonly cboDeposito: MouraComboBox;
    readonly txtMesAno: MouraTextBoxMesAno;
    readonly txtFornecedor: MouraTextBoxProcura;
    readonly txtValorDebito: MouraTextBox;
    readonly txtValorCredito: MouraTextBox;
    readonly txtValidacao: MouraTextBox;
    readonly txtDataEstoque: MouraTextBoxData;
    readonly txtDataSegundoEstoque: MouraTextBoxData;
    readonly chkNaoEnviar5929: MouraCheckBox;
    readonly chkDesconsiderarNFContinuo: MouraCheckBox;
    readonly chkEnviarConsumoInterno: MouraCheckBox;
    readonly chkEnviarDescontoEmbutido: MouraCheckBox;
    readonly chkEnviarInventario: MouraCheckBox;
    readonly chkEstoqueAtual: MouraCheckBox;
    readonly btnExportar: MouraButton;
    readonly btnGerarInventario: MouraButton;
    readonly btnLimparInventario: MouraButton;
    readonly btnAdicionar: MouraButton;
    readonly mdValidacao: MouraModal;
    readonly lstGrupo: MouraTextBoxProcuraComLista;
    readonly lstSubGrupo: MouraTextBoxProcuraComLista;
    readonly chkEnviarBlocoK: MouraCheckBox;
    OnPageLoad(): void;
    Init(): void;
    protected alterouEmpresa(): void;
    protected alterouData(): void;
    protected alterouComboPerfil(): void;
    protected PreencherComboCodigoReceita(): void;
    protected GetCodigosReceitaByUfCombo(MesAno: any, ufOrigem: any): void;
    protected PreencherGradeInventario(): void;
    protected PreencherGradeCartao(isManual: boolean): void;
    protected InserirCartaoSped(isManual: boolean, date: any): void;
    protected gerarGradeCartao(): void;
    protected AntesExportar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected ValidarExportacao(): boolean;
    protected Exportar(codReceita: number, dataInventario: any, motivoInventario: string): void;
    protected Gerar_Inventario(): boolean;
    protected LimparInventario(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): boolean;
    protected LimparCampos(): void;
    protected AposClicarBotaoGerar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected Gravar_Cartao_Manual(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected validarPerfil(): void;
    protected devExpressIniciado: boolean;
    protected DevExpressInit(): void;
}
declare const g_SPED_Angular: G_SPED_Angular;
//# sourceMappingURL=G_SPED_Angular.d.ts.map