declare class C_ConPdv extends MouraPageAngular {
    readonly grd: MouraGridViewJS;
    readonly btnSalvar: MouraButton;
    readonly btnCopiarConfig: MouraButton;
    readonly mdPdvs: MouraModal;
    readonly grdPdvs: MouraGridViewJS;
    readonly btnOKPdvs: MouraButton;
    readonly btnCancelarPdvs: MouraButton;
    readonly mdCopiarConfiguracoes: MouraModal;
    readonly txtEmpresaOrigem: MouraTextBoxProcura;
    readonly cboPdvOrigem: MouraComboBox;
    readonly grdPdvsDestino: MouraGridViewJS;
    readonly btnOKCopiar: MouraButton;
    readonly btnCancelarCopiar: MouraButton;
    readonly mdConfig: MouraModal;
    readonly hdnConfiguracao: HTMLInputElement;
    readonly hdnIdComponente: HTMLInputElement;
    readonly lblConfiguracao: MouraLabel;
    readonly txtValorAtual: MouraTextBox;
    readonly txtDica: MouraTextBox;
    readonly btnOK: MouraButton;
    readonly btnCancelar: MouraButton;
    readonly cboComboItemData: MouraComboBox;
    readonly cboComboListIndex: MouraComboBox;
    readonly cboComboText: MouraComboBox;
    readonly txtData: MouraTextBoxData;
    readonly txtTexto: MouraTextBox;
    readonly txtDecimal: MouraTextBox;
    readonly txtNumero: MouraTextBox;
    readonly cboSimNao: MouraComboBox;
    readonly txtMemo: MouraTextBox;
    protected Init(): void;
    OnPageLoad(): void;
    protected OnProcurouEmpresa(s: MouraTextBoxProcura, e: MouraEventArgs): void;
    protected CarregarPDVS(): void;
    protected OnGridSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected OnClickSalvar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCopiarConfig(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOKCopiarModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarCopiarModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOKPdvsModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarPdvsModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickOKModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickCancelarModal(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected CarregarConfiguracao(codConfiguracao: number): void;
    protected PreencherGrade(): void;
    protected OnGridCellPrepared(s: any, e: MouraGridViewJSCellPreparedEventArgs): void;
    protected IniciarCamposValores(): void;
    protected LimparCamposCopiar(): void;
    protected LimparCamposPdvs(): void;
    protected LimparCampos(): void;
    protected PreencherComboConfiguracao(lista: string[], cbo: MouraComboBox): void;
}
declare var c_ConPdv: C_ConPdv;
//# sourceMappingURL=C_ConPdv.d.ts.map