declare class C_AvalVetEntAdoc extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Animais_Entrada_Adocao_Avaliacao_Item> {
    private is_veterinario;
    readonly grdCheckListItens: MouraGridViewJSEditavel;
    ItemEntrada: SiSMoura.Core.Entity.Animais_Entrada_Adocao_Item;
    ItemCheckList: SiSMoura.Core.Entity.Animais_Checklist_Entrada_Adocao_Resposta;
    ItensCheckList: SiSMoura.Core.Entity.Animais_Checklist_Entrada_Adocao_Resposta[];
    readonly grdItensAvaliacaoComportamento: MouraGridViewJSEditavel;
    ItemAvaliacaoComportamento: SiSMoura.Core.Entity.Animais_Checklist_Comportamento_Entrada_Adocao_Resposta;
    ItensAvaliacaoComportamento: SiSMoura.Core.Entity.Animais_Checklist_Comportamento_Entrada_Adocao_Resposta[];
    readonly txtCodigoAvaliacaoEntradaItem: MouraTextBoxProcura;
    readonly txtMotivoReprovacao: MouraTextBox;
    readonly txtTratamentoAnterior: MouraTextBox;
    readonly txtAlteracaoExameFisicoCompormental: MouraTextBox;
    readonly cboStatusAvaliacao: MouraComboBox;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboAlteracaoExameFisicoComportamento: MouraComboBox;
    readonly txtExameFisico: MouraTextBoxProcura;
    readonly txtExameFisicoResultado: MouraTextBox;
    readonly dlgDicasComportamento: MouraModal;
    readonly imgAjuda: HTMLImageElement;
    readonly tab: MouraTabPanel;
    readonly grdVacinasAplicadas: MouraGridViewJSEditavel;
    VacinaRealizada: SiSMoura.Core.Entity.Animais_Entrada_Adocao_Item_Vacinas;
    VacinasRealizadas: SiSMoura.Core.Entity.Animais_Entrada_Adocao_Item_Vacinas[];
    readonly txtServicoVacina: MouraTextBoxProcura;
    readonly txtMicroChip: MouraTextBox;
    readonly IsPetReprovadoOuNaoCompareceu: boolean;
    protected Init(): void;
    private OnCboStatusAvaliacaoChenged;
    private OnGravouSucesso;
    protected OntxtServicoVacinaProcurou(s: any, e: any): void;
    protected OnProcurouExameFisico(s: any, e: any): void;
    private OnAlterouSituacaoEntradaItem;
    OnPageLoad(): void;
    private preencherDadosAvaliacao;
    private OnGrdVacinasAplicadasAlterandoItem;
    private OnGrdCheckListItensAlterandoItem;
    protected OnDepoisLimpar(entidade: SiSMoura.Core.Entity.Animais_Entrada_Adocao_Avaliacao_Item): void;
    protected OnAntesGravar(): boolean;
    private validarMicrochip;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisBuscarExistente(entidade: SiSMoura.Core.Entity.Animais_Entrada_Adocao_Avaliacao_Item): void;
    private OnAjudaClick;
    private HabilitarDesabilitarCampos;
    private OnAlterouCboAlteracaoExameFisicoComplementar;
    private getListUlHtml;
}
declare const c_AvalVetEntAdoc: C_AvalVetEntAdoc;
//# sourceMappingURL=C_AvalVetEntAdoc.d.ts.map