declare class C_CotacCF extends MouraPageCadastroAngular<SiSMoura.Core.Entity.Cotacao_Cotefacil_Remessa> {
    readonly btnGerarArquivoBase: MouraButton;
    readonly btnGerarPedido: MouraButton;
    readonly btnDownload: MouraButton;
    readonly btnExportar: MouraButton;
    readonly btnFechar: MouraButton;
    readonly hdnCaminhoSessao: HTMLInputElement;
    readonly hdnRemessa: HTMLInputElement;
    readonly hdnTipo: HTMLInputElement;
    readonly lblSituacao: MouraLabel;
    Produto: any;
    Produtos: any[];
    RetornoImportado: SiSMoura.Core.Entity.Cotacao_Cotefacil_Retorno[];
    readonly Grid: MouraGridViewJSEditavel;
    readonly grdRetorno: MouraGridViewJS;
    readonly txtProduto: MouraTextBoxProcura;
    readonly txtCodigo: MouraTextBoxProcura;
    readonly txtCodigoBarras: MouraTextBox;
    readonly lstEmpresa: MouraListBoxEmpresa;
    readonly txtQuantidade: MouraTextBox;
    readonly txtPrecoReferencia: MouraTextBox;
    readonly txtFabricante: MouraTextBoxProcura;
    readonly fpXML: MouraFileUploadJS;
    PathImportado: string;
    readonly hdnNomeArquivo: HTMLInputElement;
    readonly gridDetalhes: MouraGridViewJS;
    readonly mdDetalhes: MouraModal;
    protected Init(): void;
    protected OnGridSelecionouItem(s: any, e: MouraGridViewJSClickBotaoLinhaEventArgs): void;
    protected Preencher_Grade_Detalhes(cotacao: any): void;
    protected OnFileUploadCompleted(s: any, e: any): void;
    protected OnClickGerar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickGerarPedido(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected LimparCamposImportar(): void;
    protected CarregarRetorno(fileName: string): void;
    protected OnClickFechar(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected OnClickGerarRemessa(s: any, e: DevExpress.Web.Scripts.ASPxClientButtonClickEventArgs): void;
    protected LimparProduto(): void;
    protected OnExcluindoItem(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnSelecionouItem(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    private digitouProcura;
    protected OnKeyPressProduto(): void;
    protected OnProcurouProduto(): void;
    protected OnValidando(s: any, e: MouraGridViewJSEditavelItemCancelavelEventArgs): void;
    protected OnRepostaQuantidade(result: MsgBoxResultEventArgs): void;
    protected OnAntesGravar(): boolean;
    protected OnDepoisGravar(): boolean;
    protected OnDepoisLimpar(Entity: SiSMoura.Core.Entity.Cotacao_Cotefacil_Remessa): void;
    protected FazerDownload(): void;
    protected PreencherEmpresa(): void;
    protected OnDepoisBuscarExistente(Entity: SiSMoura.Core.Entity.Cotacao_Cotefacil_Remessa): boolean;
    protected CotacaoConcluida(): boolean;
    protected GetCadastrados(): void;
}
declare const c_CotacCF: C_CotacCF;
//# sourceMappingURL=C_CotacCF.d.ts.map