declare class C_ComCot extends MouraPageAngular {
    private menor;
    private menorPrazo;
    private pintar;
    private sublinhar;
    Produto: any;
    Produtos: any[];
    Item: any;
    Itens: any[];
    ItemPedido: any;
    ItensPedido: any[];
    readonly btnLimparCampos: MouraButton;
    readonly btnLimpar: MouraButton;
    readonly btnBuscarProdutos: MouraButton;
    readonly btnComparar: MouraButton;
    readonly btnMontar: MouraButton;
    readonly btnGerarPedido: MouraButton;
    readonly mdProdutos: MouraModal;
    readonly mdPedido: MouraModal;
    readonly gridProdutos: MouraGridViewJSEditavel;
    readonly gridPedido: MouraGridViewJSEditavel;
    readonly grid: MouraGridViewJSEditavel;
    readonly txtProduto: MouraTextBoxProcura;
    readonly cboEmpresa: MouraComboBoxEmpresa;
    readonly cboDeposito: MouraComboBox;
    readonly cboFormaPagamento: MouraComboBox;
    OnPageLoad(): void;
    protected Init(): void;
    private LimparCampos;
    private LimparCamposProduto;
    private LimparCamposPedido;
    private ClicouLimparCampos;
    private ClicouLimparProduto;
    private ClicouAdicionarProduto;
    private ClicouCompararProdutos;
    private ClicouMontarPedido;
    private ValidarCamposPedido;
    private ValidarEmpresaFornecedor;
    private ClicouGerarPedido;
    private OnClicouAdicionar;
    private AdicionarProduto;
    private VerificaCotacaoMenorEntrada;
    private VerificaCamposProdutos;
    private OnSelecionouItem;
    private OnSelecionouPedido;
    private AlteraCorValor;
    private VerificaSublinhar;
    private OnCellPrepared;
    private GridProdutoOnCellPrepared;
    private FechouModalPedido;
    private AlterouItemPedido;
    private LimpouItemPedido;
    protected OnEmpresaChanged(s: any, e: MouraEventArgs): void;
    private AlteraDeposito;
}
declare const c_ComCot: C_ComCot;
//# sourceMappingURL=C_ComCot.d.ts.map